### ISSUE TITLE
IP discover tools not working on WIFI subnet

### ISSUE THREAD

**Issue by mzulfahmy** [OCSInventory-NG/WindowsAgent#100]
### General information
Operating system :  Windows 7

### OCS Inventory information
Windows agent version : 2.3.1

### Problem's description
IP discover tools not working on WIFI but working on LAN 

LAN connection details 
![1](https://user-images.githubusercontent.com/4937448/45132640-425e9000-b1c4-11e8-8bbd-b8359e59bb1c.PNG)

On LAN
![on lan](https://user-images.githubusercontent.com/4937448/45132790-d4ff2f00-b1c4-11e8-90a1-ac9e24c0533a.png)

WIFI connection details
![2](https://user-images.githubusercontent.com/4937448/45132862-24ddf600-b1c5-11e8-9d14-9cc6fa9968ca.PNG)

On WIFI
![on wifi](https://user-images.githubusercontent.com/4937448/45132877-2efff480-b1c5-11e8-8f2f-4206217c7105.png)

How to check is there any IPDiscover blockage on wifi network? IP discover doesn't catch the WIFI IP at all.

**Comment by hafhauzer** [comment]
Hello. Our ocs inventory setup also has this problem.. Wifi and Lan are on the same subnet, but only LAN attached pc's/laptops are getting inventoried. the connection isn't the issue, because the deployment tool is able to install the files remotely..

**Comment by Eon9D** [comment]
"Wifi and Lan are on the same subnet, but only LAN attached pc's/laptops are getting inventoried. the connection isn't the issue"
OP says version 2.3.1. I just want to say that I am currently using IPDisconver with the same setup (LAN / WLAN same subnet) and it is working. Actually quite the opposite (see #67). It scans LAN and WIFI computers without issues. Only difference is that I am using the latest version.
Are you on the latest verison? Can you ping the WIFI client from the elected client?

**Comment by hafhauzer** [comment]
Hello,

this is solved. It had nothing to do with ocs. We needed to adjust the
policies on the wireless controller separately.

Thanks for the reply
Daniel

Op za 14 dec. 2019 19:27 schreef Eon9D <notifications@github.com>:

**Comment by Eon9D** [comment]
Can you close please. Thanks

**Comment by hafhauzer** [comment]
> Can you close please. Thanks

I'm not the author.
Regards
