### ISSUE TITLE
Error while Compiling: libcurl.dll -> files not found

### ISSUE THREAD

**Issue by nataraj1296** [OCSInventory-NG/WindowsAgent#101]
### General information
Operating system :  Windows 7 Enterprise

### OCS Inventory information
Windows agent version : 2.1.1.1

### Problem's description
*I'm using NSIS to build an exe installer for OCS Windows Agent (2.1.1.1). 
Now I'm stuck at the error where the compiler does not find the libcurl.dll file.
What can I do to proceed with the compilation?*

### Inventory log file ( optional )
*Call "Write_Log"
File: "..\Release\libcurl.dll" -> no files found.
Usage: File [/nonfatal] [/a] ([/r] [/x filespec [...]] filespec [...] |
   /oname=outfile one_file_only)
Error in script "C:\Users\[Username]\Downloads\WindowsAgent-master\NSIS_agent_setup\OCS-NG_Windows_Agent_Setup.nsi" on line 1550 -- aborting creation process
*

**Comment by charleneauger** [comment]
Hi @nataraj1296 ,
Agent version 2.1.1.1 is too old and is no longer maintained by our team, I'm sorry and thank you for your comprehension.

Regards,
Charlene Auger
