### ISSUE TITLE
Upgrading issue (not all files has been rewrited)

### ISSUE THREAD

**Issue by drTr0jan** [OCSInventory-NG/WindowsAgent#103]
The problem is actually from 2.3.0.0 release till nowadays (2.4.0.0).
Upgrade to new release works incorrectly on some PCs.
Sometimes some files hasn't been rewrited after the upgrade:
- libeay32.dll
- OCSInventory Front.dll
- OcsSystray.exe
- OcsWmi.dll
- SysInfo.dll
- zlib1.dll

It's needed to rewrite the files manually after upgrade on some PCs.

Operating system :  Win7, Win8, Win10
Windows agent version : 2.3.0.0, 2.4.0.0

[OCS-NG-Windows-Agent-Setup.log](https://github.com/OCSInventory-NG/WindowsAgent/files/2395684/OCS-NG-Windows-Agent-Setup.log)

**Comment by charleneauger** [comment]
Hi @drTr0jan ,

This bug has been fixed on the last PR #138 

Best regards,
Charlene Auger
