### ISSUE TITLE
building Windows Agent did not work

### ISSUE THREAD

**Issue by Spanni26** [OCSInventory-NG/WindowsAgent#106]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General information
Operating system :   Win10

### OCS Inventory information
Windows agent version : actual source from git

### Problem's description
The agent can't be built. A lot of errors in build log .
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2248	'ATL::CA2WEX<128>::CA2WEX': cannot access private member declared in class 'ATL::CA2WEX<128>'	SysInfo	c:\users\ds\downloads\ocs-windows-agent\windowsagent\sysinfo\edid.cpp	591	
Error	C4839	non-standard use of class 'ATL::CA2WEX<128>' as an argument to a variadic function	SysInfo	c:\users\ds\downloads\ocs-windows-agent\windowsagent\sysinfo\edid.cpp	590	
Error	C2248	'ATL::CA2WEX<128>::CA2WEX': cannot access private member declared in class 'ATL::CA2WEX<128>'	SysInfo	c:\users\ds\downloads\ocs-windows-agent\windowsagent\sysinfo\edid.cpp	590	
Error	C4839	non-standard use of class 'ATL::CA2WEX<128>' as an argument to a variadic function	SysInfo	c:\users\ds\downloads\ocs-windows-agent\windowsagent\sysinfo\edid.cpp	591	
Error	C4839	non-standard use of class 'ATL::CA2WEX<128>' as an argument to a variadic function	SysInfo	c:\users\ds\downloads\ocs-windows-agent\windowsagent\sysinfo\edid.cpp	594	
Error	C2248	'ATL::CA2WEX<128>::CA2WEX': cannot access private member declared in class 'ATL::CA2WEX<128>'	SysInfo	c:\users\ds\downloads\ocs-windows-agent\windowsagent\sysinfo\edid.cpp	594	
Error	C4839	non-standard use of class 'ATL::CA2WEX<128>' as an argument to a variadic function	SysInfo	c:\users\ds\downloads\ocs-windows-agent\windowsagent\sysinfo\edid.cpp	596	
Error	C2248	'ATL::CA2WEX<128>::CA2WEX': cannot access private member declared in class 'ATL::CA2WEX<128>'	SysInfo	c:\users\ds\downloads\ocs-windows-agent\windowsagent\sysinfo\edid.cpp	596	
Error	C4839	non-standard use of class 'ATL::CA2WEX<128>' as an argument to a variadic function	SysInfo	c:\users\ds\downloads\ocs-windows-agent\windowsagent\sysinfo\edid.cpp	680	
Error	C2248	'ATL::CA2WEX<128>::CA2WEX': cannot access private member declared in class 'ATL::CA2WEX<128>'	SysInfo	c:\users\ds\downloads\ocs-windows-agent\windowsagent\sysinfo\edid.cpp	680	
Error	C4839	non-standard use of class 'ATL::CA2WEX<128>' as an argument to a variadic function	SysInfo	c:\users\ds\downloads\ocs-windows-agent\windowsagent\sysinfo\edid.cpp	681	
Error	C2248	'ATL::CA2WEX<128>::CA2WEX': cannot access private member declared in class 'ATL::CA2WEX<128>'	SysInfo	c:\users\ds\downloads\ocs-windows-agent\windowsagent\sysinfo\edid.cpp	681	
Error	C4839	non-standard use of class 'ATL::CA2WEX<128>' as an argument to a variadic function	SysInfo	c:\users\ds\downloads\ocs-windows-agent\windowsagent\sysinfo\edid.cpp	684	
Error	C2248	'ATL::CA2WEX<128>::CA2WEX': cannot access private member declared in class 'ATL::CA2WEX<128>'	SysInfo	c:\users\ds\downloads\ocs-windows-agent\windowsagent\sysinfo\edid.cpp	684	
Error	C4839	non-standard use of class 'ATL::CA2WEX<128>' as an argument to a variadic function	SysInfo	c:\users\ds\downloads\ocs-windows-agent\windowsagent\sysinfo\edid.cpp	686	
Error	C2248	'ATL::CA2WEX<128>::CA2WEX': cannot access private member declared in class 'ATL::CA2WEX<128>'	SysInfo	c:\users\ds\downloads\ocs-windows-agent\windowsagent\sysinfo\edid.cpp	686	
Error	C4839	non-standard use of class 'ATL::CA2WEX<128>' as an argument to a variadic function	SysInfo	c:\users\ds\downloads\ocs-windows-agent\windowsagent\sysinfo\iphelper.cpp	495	
Error	C2248	'ATL::CA2WEX<128>::CA2WEX': cannot access private member declared in class 'ATL::CA2WEX<128>'	SysInfo	c:\users\ds\downloads\ocs-windows-agent\windowsagent\sysinfo\iphelper.cpp	495	
Error	C1083	Cannot open include file: 'zlib.h': No such file or directory	OCSInventory Front	c:\users\ds\downloads\ocs-windows-agent\windowsagent\ocsinventory front\flate.cpp	15	
Error	C4839	non-standard use of class 'ATL::CA2WEX<128>' as an argument to a variadic function	OCSInventory Front	c:\users\ds\downloads\ocs-windows-agent\windowsagent\ocsinventory front\markup.cpp	428	
Error	C2248	'ATL::CA2WEX<128>::CA2WEX': cannot access private member declared in class 'ATL::CA2WEX<128>'	OCSInventory Front	c:\users\ds\downloads\ocs-windows-agent\windowsagent\ocsinventory front\markup.cpp	428	
Error	C4839	non-standard use of class 'ATL::CA2WEX<128>' as an argument to a variadic function	OCSInventory Front	c:\users\ds\downloads\ocs-windows-agent\windowsagent\ocsinventory front\markup.cpp	452	
Error	C2248	'ATL::CA2WEX<128>::CA2WEX': cannot access private member declared in class 'ATL::CA2WEX<128>'	OCSInventory Front	c:\users\ds\downloads\ocs-windows-agent\windowsagent\ocsinventory front\markup.cpp	452	
Error	C4839	non-standard use of class 'ATL::CA2WEX<128>' as an argument to a variadic function	OCSInventory Front	c:\users\ds\downloads\ocs-windows-agent\windowsagent\ocsinventory front\markup.cpp	552	
Error	C2248	'ATL::CA2WEX<128>::CA2WEX': cannot access private member declared in class 'ATL::CA2WEX<128>'	OCSInventory Front	c:\users\ds\downloads\ocs-windows-agent\windowsagent\ocsinventory front\markup.cpp	552	
Error	C4839	non-standard use of class 'ATL::CA2WEX<128>' as an argument to a variadic function	OCSInventory Front	c:\users\ds\downloads\ocs-windows-agent\windowsagent\ocsinventory front\markup.cpp	561	
Error	C2248	'ATL::CA2WEX<128>::CA2WEX': cannot access private member declared in class 'ATL::CA2WEX<128>'	OCSInventory Front	c:\users\ds\downloads\ocs-windows-agent\windowsagent\ocsinventory front\markup.cpp	561	
Error	C4839	non-standard use of class 'ATL::CA2WEX<128>' as an argument to a variadic function	OCSInventory Front	c:\users\ds\downloads\ocs-windows-agent\windowsagent\ocsinventory front\markup.cpp	565	
Error	C2248	'ATL::CA2WEX<128>::CA2WEX': cannot access private member declared in class 'ATL::CA2WEX<128>'	OCSInventory Front	c:\users\ds\downloads\ocs-windows-agent\windowsagent\ocsinventory front\markup.cpp	565	
Error	C1083	Cannot open include file: 'openssl/evp.h': No such file or directory	OCSInventory Front	c:\users\ds\downloads\ocs-windows-agent\windowsagent\ocsinventory front\ocsutils.cpp	18	
Error	C1083	Cannot open include file: 'openssl/aes.h': No such file or directory	ComHTTP	c:\users\ds\downloads\ocs-windows-agent\windowsagent\comhttp\httpcrypt.h	20	
Error	C1083	Cannot open include file: 'openssl/aes.h': No such file or directory	ComHTTP	c:\users\ds\downloads\ocs-windows-agent\windowsagent\comhttp\httpcrypt.h	20	
Error	C1083	Cannot open include file: 'openssl/aes.h': No such file or directory	ComHTTP	c:\users\ds\downloads\ocs-windows-agent\windowsagent\comhttp\httpcrypt.h	20	
Error	C1083	Cannot open include file: 'openssl/aes.h': No such file or directory	ComHTTP	c:\users\ds\downloads\ocs-windows-agent\windowsagent\comhttp\httpcrypt.h	20	
Error	LNK1181	cannot open input file 'C:\Users\ds\Downloads\ocs-windows-agent\WindowsAgent\Release\OCSInventory Front.lib'	Download	C:\Users\ds\Downloads\ocs-windows-agent\WindowsAgent\Download\LINK	1	
Error	C4839	non-standard use of class 'ATL::CA2WEX<128>' as an argument to a variadic function	Agent	c:\users\ds\downloads\ocs-windows-agent\windowsagent\agent\capexecute.cpp	110	
Error	C2248	'ATL::CA2WEX<128>::CA2WEX': cannot access private member declared in class 'ATL::CA2WEX<128>'	Agent	c:\users\ds\downloads\ocs-windows-agent\windowsagent\agent\capexecute.cpp	110

**Comment by gillesdubois** [comment]
Hi,

Which VS version are you using ?

Regards,
Gilles Dubois.

**Comment by Spanni26** [comment]
Visual Studio 2017

**Comment by gillesdubois** [comment]
We're still on the VS2015. Please try with this version.
2017 support will come later this year

**Comment by Spanni26** [comment]
Ok, thanks. Will try it.

**Comment by Spanni26** [comment]
Ok, with VS 2015 it also did not work. But different error. curl.h cannot be found. Where is curl.h from, where is the right place for this file and how does it copy to that place?

**Comment by Spanni26** [comment]
Ok, have to change a lot of pathes in the agent-project.
VS2015 is not complaining about missing files anymore.
But still errors:

Severity	Code	Description	Project	File	Line	Suppression State
Error	C2664	'int EVP_CIPHER_CTX_reset(EVP_CIPHER_CTX *)': cannot convert argument 1 from 'int *' to 'EVP_CIPHER_CTX *'	ComHTTP	C:\Users\ds\Downloads\WindowsAgent-master\WindowsAgent-master\ComHTTP\HTTPCrypt.cpp	283	
Error (active)		incomplete type is not allowed	OCSInventory Front	c:\Users\ds\Downloads\WindowsAgent-master\WindowsAgent-master\OCSInventory Front\OcsUtils.cpp	384	
Error	C2079	'ctx' uses undefined struct 'evp_md_ctx_st'	OCSInventory Front	C:\Users\ds\Downloads\WindowsAgent-master\WindowsAgent-master\OCSInventory Front\OcsUtils.cpp	384	
Error	C2664	'int EVP_DigestInit(EVP_MD_CTX *,const EVP_MD *)': cannot convert argument 1 from 'int *' to 'EVP_MD_CTX *'	OCSInventory Front	C:\Users\ds\Downloads\WindowsAgent-master\WindowsAgent-master\OCSInventory Front\OcsUtils.cpp	393	
Error	C2664	'int EVP_DigestUpdate(EVP_MD_CTX *,const void *,std::size_t)': cannot convert argument 1 from 'int *' to 'EVP_MD_CTX *'	OCSInventory Front	C:\Users\ds\Downloads\WindowsAgent-master\WindowsAgent-master\OCSInventory Front\OcsUtils.cpp	399	
Error	C2664	'int EVP_DigestFinal(EVP_MD_CTX *,unsigned char *,unsigned int *)': cannot convert argument 1 from 'int *' to 'EVP_MD_CTX *'	OCSInventory Front	C:\Users\ds\Downloads\WindowsAgent-master\WindowsAgent-master\OCSInventory Front\OcsUtils.cpp	403	
Error	LNK1181	cannot open input file 'C:\Users\ds\Downloads\WindowsAgent-master\WindowsAgent-master\Release\OCSInventory Front.lib'	Download	C:\Users\ds\Downloads\WindowsAgent-master\WindowsAgent-master\Download\LINK	1	
Error	C2079	'oEncCtx' uses undefined struct 'evp_cipher_ctx_st'	ComHTTP	C:\Users\ds\Downloads\WindowsAgent-master\WindowsAgent-master\ComHTTP\HTTPCrypt.cpp	124	
Error	C2664	'int EVP_CIPHER_CTX_reset(EVP_CIPHER_CTX *)': cannot convert argument 1 from 'int *' to 'EVP_CIPHER_CTX *'	ComHTTP	C:\Users\ds\Downloads\WindowsAgent-master\WindowsAgent-master\ComHTTP\HTTPCrypt.cpp	156	
Error	C2664	'int EVP_EncryptInit_ex(EVP_CIPHER_CTX *,const EVP_CIPHER *,ENGINE *,const unsigned char *,const unsigned char *)': cannot convert argument 1 from 'int *' to 'EVP_CIPHER_CTX *'	ComHTTP	C:\Users\ds\Downloads\WindowsAgent-master\WindowsAgent-master\ComHTTP\HTTPCrypt.cpp	157	
Error	C2664	'int EVP_EncryptUpdate(EVP_CIPHER_CTX *,unsigned char *,int *,const unsigned char *,int)': cannot convert argument 1 from 'int *' to 'EVP_CIPHER_CTX *'	ComHTTP	C:\Users\ds\Downloads\WindowsAgent-master\WindowsAgent-master\ComHTTP\HTTPCrypt.cpp	174	
Error	C2664	'int EVP_EncryptFinal_ex(EVP_CIPHER_CTX *,unsigned char *,int *)': cannot convert argument 1 from 'int *' to 'EVP_CIPHER_CTX *'	ComHTTP	C:\Users\ds\Downloads\WindowsAgent-master\WindowsAgent-master\ComHTTP\HTTPCrypt.cpp	184	
Error	C2664	'int EVP_CIPHER_CTX_reset(EVP_CIPHER_CTX *)': cannot convert argument 1 from 'int *' to 'EVP_CIPHER_CTX *'	ComHTTP	C:\Users\ds\Downloads\WindowsAgent-master\WindowsAgent-master\ComHTTP\HTTPCrypt.cpp	203	
Error	C2079	'oEncCtx' uses undefined struct 'evp_cipher_ctx_st'	ComHTTP	C:\Users\ds\Downloads\WindowsAgent-master\WindowsAgent-master\ComHTTP\HTTPCrypt.cpp	209	
Error	C2664	'int EVP_CIPHER_CTX_reset(EVP_CIPHER_CTX *)': cannot convert argument 1 from 'int *' to 'EVP_CIPHER_CTX *'	ComHTTP	C:\Users\ds\Downloads\WindowsAgent-master\WindowsAgent-master\ComHTTP\HTTPCrypt.cpp	242	
Error	C2664	'int EVP_DecryptInit_ex(EVP_CIPHER_CTX *,const EVP_CIPHER *,ENGINE *,const unsigned char *,const unsigned char *)': cannot convert argument 1 from 'int *' to 'EVP_CIPHER_CTX *'	ComHTTP	C:\Users\ds\Downloads\WindowsAgent-master\WindowsAgent-master\ComHTTP\HTTPCrypt.cpp	243	
Error	C2664	'int EVP_DecryptUpdate(EVP_CIPHER_CTX *,unsigned char *,int *,const unsigned char *,int)': cannot convert argument 1 from 'int *' to 'EVP_CIPHER_CTX *'	ComHTTP	C:\Users\ds\Downloads\WindowsAgent-master\WindowsAgent-master\ComHTTP\HTTPCrypt.cpp	260	
Error	C2664	'int EVP_DecryptFinal_ex(EVP_CIPHER_CTX *,unsigned char *,int *)': cannot convert argument 1 from 'int *' to 'EVP_CIPHER_CTX *'	ComHTTP	C:\Users\ds\Downloads\WindowsAgent-master\WindowsAgent-master\ComHTTP\HTTPCrypt.cpp	270	
Error	LNK1181	cannot open input file 'C:\Users\ds\Downloads\WindowsAgent-master\WindowsAgent-master\Release\ComHTTP.lib'	Agent	C:\Users\ds\Downloads\WindowsAgent-master\WindowsAgent-master\Agent\LINK	1

**Comment by Spanni26** [comment]
Sorry for beeing so annoying, but I need an agent with debug output for curl and im only an administrator, not a programmer. 
Atm I can#T provide any packages via ocs cause I only get an error about an SSL error.

**Comment by charleneauger** [comment]
Hi @Spanni26 ,

Windows Agent's code have been updated to be compile with VS2017.
See PR #123 #132 #133 

Best Regards,
Charlene Auger
