### ISSUE TITLE
Motherboard information display problem (serial, manufacturer, model)

### ISSUE THREAD

**Issue by PaveLGIL** [OCSInventory-NG/WindowsAgent#107]
### General information
Operating system :  Windows 10

### OCS Inventory information
Windows agent version : 2.3.1.1

### Problem's description
Problem with display motherboard information (serial, manufacturer, model). 
![image-2018-07-16-12-00-07-035](https://user-images.githubusercontent.com/15833990/48405357-330b3e00-e743-11e8-85b4-f1bc092abac6.png)

**Comment by charleneauger** [comment]
Hi @PaveLGIL ,
This bug has been fix with PR [https://github.com/OCSInventory-NG/OCSInventory-Server/pull/161](url) on the OCS server.
Regards,
Charlene Auger

**Comment by PaveLGIL** [comment]
Unfortunately, I still see problem(
![screen shot 2019-01-09 at 12 33 15](https://user-images.githubusercontent.com/15833990/50890205-cfcc1e00-140a-11e9-93f4-05f7d123a6a5.png)

Server updated, agent updated
