### ISSUE TITLE
Not all printers are listed

### ISSUE THREAD

**Issue by AnaelMobilia** [OCSInventory-NG/WindowsAgent#11]
Hello,

Network printers are not listed on OCS (agent v2.1.1.1)
See on a W10 64 bits computer, also on many (>25) computers on W7 pro 32 & 64 bits
On windows :
![windows](https://cloud.githubusercontent.com/assets/6187125/13535592/69533dec-e23b-11e5-842f-425d42f72a4b.PNG)
On OCS :
![ocs](https://cloud.githubusercontent.com/assets/6187125/13535593/6957e5fe-e23b-11e5-8d0e-87a7ae6fdd47.PNG)

Regards,
Anael

**Comment by damienbelliard** [comment]
Hi, 

Can you give me your printer configuration ?

How printers are installed ? ( local , network or sharing ? ) 

Regards

Damien Belliard

**Comment by AnaelMobilia** [comment]
Hi,

Printers are installed through a print server.
These are networks printers installed on the print server.
Installed on the local computer with the windows functionnality to add a printer (listed in Active Directory)

Regards,
Anael

**Comment by damienbelliard** [comment]
Hi @AnaelMobilia 

There are a plugin to inventory network printer 
https://github.com/PluginsOCSInventory-NG/listprinters

Regards

**Comment by gitmais** [comment]
Hello,
Ticket fermé mais au cas ou...
Si tu fais un "ocsinventory /xml", vois-tu tes imprimantes réseaux manquantes ? J'ai le même problème
