### ISSUE TITLE
Installation date not present for most software

### ISSUE THREAD

**Issue by sokatra** [OCSInventory-NG/WindowsAgent#110]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General information
Server - ocsinventory 2.5.0 under Debian 9

    PHP Version :
    Web Server :
    Database Server :
    Version OCSReports:

    7.0.30
    Apache/2.4.25 (Debian)
    Debian 9.6 version 10.1.37-MariaDB-0+deb9u1
    2.5

Operating system :  
Windows 7 - 64 bit 
### OCS Inventory information
Windows agent version : 
2.4.0
### Problem's description
Windows agent does not report the installation date for most of the programs! example is the software handbrake - in windows 7 in add/remove control panel i see the installaton date
On the server Webinterface i see only 0000-00-00 00:00:00

Bug is very old
http://ask.ocsinventory-ng.org/784/installation-date-not-showing

### Inventory log file ( optional )
*Use github cloud or trusted upload website*

**Comment by charleneauger** [comment]
Hi @sokatra ,
The current recovery method (WMI and Registry) of this data does not make it possible to recover reliable data.

Regards,
Charlene Auger
