### ISSUE TITLE
Agent 2.1.1.3 isn't compatible with XP

### ISSUE THREAD

**Issue by gillesdubois** [OCSInventory-NG/WindowsAgent#12]
@sokatra

Agent with Version 2.1.1.2 and 2.1.1.3 and 2.1.1.4 (2.2 alpha) arent compatible with Windows XP

Service can't be installed -

if i start
ocsinventory.exe /SAVE_CONF

i will get immediatly a graphical windows with the following errorcode

C:\Program Files\Ocsinventory Agent\OCSInventory.exe is not a valid win32 application

**Comment by gillesdubois** [comment]
Hi,

2.1.1.3 and 2.2 Alpha will not support windows XP.
If you want to use the new agent functionalities you will have to upgrade your operating system.
However 2.1.1.2 is still compatible with XP and can be found here on our website.

Regards, 
Gilles Dubois.

**Comment by sokatra** [comment]
My version of 2.1.1.2 also didn't work  - i can't find a old version here - perhaps my version of 2.1.1.2 is different from yours 

sorry

**Comment by sokatra** [comment]
perhaps - it can fixed for all 2.x version - even the compatibilty matrix promises that 2.x Agent version  are fully compatible . Nobody expects that a minor subversions which is just bugfixed breaks the compatibilty.
http://www.ocsinventory-ng.org/en/about/features/supported-os.html
especially because it can be installed without error on xp (but doesn't work).
But anyway thanks for the great work on this great project

**Comment by phil-davis** [comment]
Yes, I am surprised about this also. I would have thought that all 2.1.*.* would keep having the same OS compatibility. Then 2.2 could change to not support older OS.

**Comment by doudz** [comment]
The last Windows XP compatible release is 2.1.0.3

**Comment by nerijus** [comment]
Not only XP, the same problem with Windows Server 2003.

**Comment by nerijus** [comment]
Where can I download an older working version?

**Comment by gillesdubois** [comment]
Hi,

> Not only XP, the same problem with Windows Server 2003.
XP and 2003 server are using the same dependencies so yeah if XP doesn't work 2003 dosen't work.

You can use the launchpad.
However, i just added an older version on github : https://github.com/OCSInventory-NG/WindowsAgent/releases/download/2.0.5.3/OCSNG-Windows-Agent-2.0.5.zip

This version should be fine with XP and below.
Regards , Gilles Dubois

**Comment by nerijus** [comment]
I found a newer working version here - https://launchpad.net/ocsinventory-windows-agent/+download
OCSNG-Windows-Agent-2.1.1.zip works OK on 2003 server. Could you please upload it to the github as well?

**Comment by gillesdubois** [comment]
I'm uploading older release atm 
2.1.0.3 : https://github.com/OCSInventory-NG/WindowsAgent/releases/download/2.1.0.3/OCSNG-Windows-Agent-2.1.zip

2.1.1 on the way :)

Thanks for your contribution
Regards, Gilles Dubois.

**Comment by gillesdubois** [comment]
2.1.1 -> https://github.com/OCSInventory-NG/WindowsAgent/releases/download/2.1.1.1/OCSNG-Windows-Agent-2.1.1.zip
