### ISSUE TITLE
Motherboard information display problem (serial, manufacturer, model)2

### ISSUE THREAD

**Issue by PaveLGIL** [OCSInventory-NG/WindowsAgent#120]
**General information**
Operating system : Windows 10

**OCS Inventory information**
Windows agent version : 2.4.0.0

**Problem's description**
Problem with display motherboard information (serial, manufacturer, model).
![screen shot 2019-01-09 at 12 33 15](https://user-images.githubusercontent.com/15833990/50890343-10c43280-140b-11e9-953c-3d879383b42c.png)

I created the same issue earlier but it, wasn't fixed.
https://github.com/OCSInventory-NG/WindowsAgent/issues/107

Server and agent updated to latest version

**Comment by gillesdubois** [comment]
Hi,

Our tests has been made on a lot of platforms and it work. What do you mean by "last serveur version ?" 
The modification is not in the 2.6RC but in the trunk which mean that no released version have the fix yet.

The last nightly should have the modification : 
http://download.ocsinventory-ng.org/nightly/OCSNG_UNIX_SERVER_2.5-nightly-2019-01-09.zip

Regards,
Gilles Dubois.

**Comment by PaveLGIL** [comment]
Yes, it works, thank you!
