### ISSUE TITLE
Agent windows 2.4 ne demarre pas

### ISSUE THREAD

**Issue by seijilo** [OCSInventory-NG/WindowsAgent#121]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General information
Operating system :  windows 10 pro 1809

### OCS Inventory information
Windows agent version : 2.4
Server : 2.4.1

### Problem's description
code erreur 1062, le service ne demarre pas
Je possède un pc portable HP probook G4 et l'installation de OCS agent microsoft fonctionne parfaitement.
Pendant plusieurs jours, le pc client remonte l'inventaire sur le serveur OCS puis j'ai un problème de démarrage du service.
La solution est de reinstaller l'agent et le service reprend.
J'utilise un certificat nommé cacerts pour la connexion au serveur.
Il n'y a aucun log dans C:\ProgramData\OCS Inventory NG\Agent car le service ne demarre même pas.
Je ne vois pas de log dans Event viewer de mon W10.
Je posterai plus de detail lorsque le problème refera surface dans quelque jours.

### Inventory log file ( optional )
*Use github cloud or trusted upload website*

**Comment by charleneauger** [comment]
Bonjour @seijilo ,

Avez-vous un antivirus d'installé sur votre PC ?

Cordialement,
Charlène Auger

**Comment by gubic76** [comment]
Bonjour,

J'ai le même problème sur des serveurs windows, le service est lancé dans la console mais dans le gestionnaire Evènement j'ai le message :

Can't Launch OSC AGENT NG

Si je lance OCSInventory.exe il tourne parfaitement.

**Comment by charleneauger** [comment]
Bonjour,

Pouvez-vous me dire si le problème persiste avec la version 2.7 ?

Cordialement,
Charlène Auger

**Comment by seijilo** [comment]
Bonjour,
vous pouvez clôturer ce problème, je ne peux pas tester.
je n'ai jamais su pourquoi, mais pour ne pas avoir de problème j'ai
réinstallé le poste complètement.
Cordialement UEMURA Seijilo

Le ven. 10 juil. 2020 à 09:36, Charlène Auger <notifications@github.com> a
écrit :
