### ISSUE TITLE
 How to Change Server URL Quickly?

### ISSUE THREAD

**Issue by jackadam1981** [OCSInventory-NG/WindowsAgent#122]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General information
Operating system :  Windows

### OCS Inventory information
Windows agent version : 2.4

### Problem's description
*Describe your problem here*
I want to change the server URL of a batch of clients.
 How to Change Server URL Quickly?

### Inventory log file ( optional )
*Use github cloud or trusted upload website*

**Comment by lhchin** [comment]
a) stop the service and update the server address in the following file and startup service.
C:\ProgramData\OCS Inventory NG\Agent\ocsinventory.ini 
server=

b) force update defining server address in command switch
C:\Program Files (x86)\OCS Inventory Agent\OCSInventory.exe /force /server=

**Comment by charleneauger** [comment]
Hi @jackadam1981 @lhchin ,

Thank you @lhchin  for your answer !

@jackadam1981, as said above, there are two ways to change the server address:

- change the value in ocsinventory.ini in C:\ProgramData\OCS Inventory NG\Agent\
- Force update defining server address with command line : C:\Program Files (x86)\OCS Inventory Agent\OCSInventory.exe /force /server=http://your_address/ocsinventory

Best Regards,
Charlene Auger
