### ISSUE TITLE
plugins not loaded

### ISSUE THREAD

**Issue by Parnoud** [OCSInventory-NG/WindowsAgent#125]
### General information
Operating system : Win 10 (1709) 64 bits / Win 7  32bits

### OCS Inventory information
Windows agent version : 2.4.0.0
### Problem's description
Hello,
i have trouble with plugins (Agent side).
When i add plugins .vbs, .ps1 .. in my folder "C:\Program Files (x86)\OCS Inventory Agent\plugins" and i restart the "OCS Inventory Service" (With the debug mode on), nothing is loaded :
AGENT => Loading plug-in(s)
	DLL PLUGIN => Searching for Plug-in DLL(s) in folder <C:\Program Files (x86)\OCS Inventory Agent\plugins>
	DLL PLUGIN => 0 DLL Plug-in(s) successfully loaded on 0 DLL(s) found
The service want dll, if i try to rename my vbs or ps1 to DLL, the plugins is found but not loaded (because i just rename ps1/vbs to dll).

Thanks in advance,
Pierre

**Comment by charleneauger** [comment]
Hi @Parnoud ,

DLL plugins are loaded at the beginning of the inventory unlike the vbs and ps1 that are loaded in the middle.
In your log file do you have these lines below that appear ?

> EXECUTABLE PLUGIN => Searching for VBS script(s) in folder <C:\Program Files (x86)\OCS Inventory Agent\plugins>
 EXECUTABLE PLUGIN => Searching for PS1 script(s) in folder <C:\Program Files (x86)\OCS Inventory Agent\plugins>
 EXECUTABLE PLUGIN => Found executable plugin <PluginName.ps1>

Best Regards,
Charlene Auger

**Comment by Parnoud** [comment]
In logs Nothing appear.

**Comment by fbomj** [comment]
Hi,
plugins have been correctly stored in the correct location? They must be placed in C:\Program Files (x86)\OCS Inventory Agent\Plugins on 32 bits systems. On 64 bits the is C:\Program Files\OCS Inventory Agent\Plugins.

Regards
