### ISSUE TITLE
Option to add Company Logo?

### ISSUE THREAD

**Issue by sokatra** [OCSInventory-NG/WindowsAgent#127]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General information
Operating system :  
Windows 7- 64bit
### OCS Inventory information
Windows agent version : 
2.4.0

### Problem's description
Add a small company logo to the agent would be great. It happens so often that new users think the popping up OCS screen is a Virus and sometimes crying for helpdesk or even worse force the computer shutdown by pressing the power button for more then 5 seconds.

### Inventory log file ( optional )
*Use github cloud or trusted upload website*

**Comment by charleneauger** [comment]
Hi @sokatra ,

Your request is not planned in the Roadmap Agent. You can rebrand the agent yourself by compiling it and changing the images. Also, subscribing to the  OCS professional services offer theses kind of customization.

Best regards,
Charlene Auger
