### ISSUE TITLE
Don't regenerate deviceid when network interfaces change

### ISSUE THREAD

**Issue by hschletz** [OCSInventory-NG/WindowsAgent#13]
I frequently get mysterious duplicates in the database during normal operation. Some investigation led me to this agent log message:

```
DID_CHECK => MAC Address changed new:<00:00:5E:00:53:01> old:<00:00:5E:00:53:0100:00:00:00:00:0000:00:00:00:00:0000:00:00:00:00:0000:00:5E:00:53:0100:00:5E:00:53:0100:00:5E:00:53:01>
DID_CHECK => Generating new unique ID for device <HOSTNAME>
```

This led me to the code in Deviceid.cpp which is responsible for generating a new DEVICEID string whenever network interfaces are added or removed. Whatever the cause for the interface changes is, generating a new deviceid makes no sense. I don't see any logical connection between the event and the reaction. In fact, network interfaces coming and going is a pretty normal event, causes including
- Plugging/unplugging a USB network adapter
- Using the switch or key combination on a laptop
- Activating/deactivating virtual interfaces (VPN etc.)

This does not justify the trouble that is caused by a new deviceid. The server's automatic duplicate removal feature is only a partial solution - simply covering up faulty agent behavior fights symptoms, not the cause.

The UNIX agent only regenerates the deviceid if a hostname change is detected (which does make sense as it's part of the ID string), and the Windows agent should behave the same way.

**Comment by gillesdubois** [comment]
Hi,

The new windows agent version will come with this enhancement, this has been added to the roadmap.

Regards, Gilles Dubois.

**Comment by hschletz** [comment]
Still present in 2.3 RC.

**Comment by charleneauger** [comment]
Hi @hschletz ,

Your problem is fixed, look at 25b2e95f6823d8b8a88d4d8c195d6ce0cee5f1a4.

Regards, 
Charlene Auger

**Comment by hschletz** [comment]
The mentioned commit seems to fix deviceid regeneration in some cases (interface going up/down between invocations), but as I understand it, would still regenerate the ID if interfaces are added/removed entirely. My initial post lists some everyday situations where this may happen, still causing a big mess.

I don't see a reason for regenerating the ID at all. If it is found in the agent config, it should be used and never touched again. IMHO that's the whole point of the ID.

**Comment by sokatra** [comment]
hy "hschletz", i also think that the device id should not change after generated .. the change causes much trouble. 
dymamic groups are re calculated .. you must deduplicate the computers by name etc.

it is only useful if a device is cloned or similar situations.

**Comment by hschletz** [comment]
> it is only useful if a device is cloned or similar situations.

Even in that case, you would almost certainly rename the computer after cloning, which would cause device ID regeneration anyway. Still no reason to bother with MAC addresses.
