### ISSUE TITLE
Systray icon missing after upgrade

### ISSUE THREAD

**Issue by fbomj** [OCSInventory-NG/WindowsAgent#137]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General information
Operating system :  Windows 7/10

### OCS Inventory information
Windows agent version : 2.4.0

### Problem's description
After upgrade with /upgrade option the systray icon is missing in the task bar. The command used for upgrade is : OCS-NG-Windows-Agent-Setupe.exe /UPGRADE /S /server=<url_server>/ocsinventory

**Comment by drTr0jan** [comment]
Please check #103 - OcsSystray.exe version after upgarde.

**Comment by charleneauger** [comment]
Hi @fbomj ,

After upgrading the agent with the /UPGRADE option, the Systray icon only appears when the machine is restarted.

Best regards,
Charlene Auger
