### ISSUE TITLE
The SSL, the curl and cacert.pem

### ISSUE THREAD

**Issue by FatCyclone** [OCSInventory-NG/WindowsAgent#14]
Hi,

I have some issue here.
I wasn't able to comunicate with my OCS server because of this error : 

`WARNING *** COM SERVER => Failed to send HTTP Post request <Problem with the SSL CA cert (path? access rights?)>`

The cacert.pem file exists, and available in `%programdata%\OCS Inventory NG\Agent` directory.
In my configuration file, i've tried absolute and relative pathes to certificate, but error is stil there.

Thanks for your time.
FatCyclone

Infos : Windows 10 Pro, OCS Agent Version 2.1.1.3, Wildcard cacert from some CA authority.
EDIT : All is working with mac OSX (Same config, and same cacert.pem file).

**Comment by damienbelliard** [comment]
Hi,
Your certificate need to be created with the OCS server FQDN.
I think your Wildcard cacert can't work with the OCS Windows agent

Please try a new certificate with OCS serveur FQDN for CN attribut.

Regards

**Comment by FatCyclone** [comment]
Same result with an FQDN certificate.

**Comment by roll4life** [comment]
@FatCyclone if you are using a 3rd Party signed certificate you can use the CA certificates extracted from mozilla, provided by curl.
https://curl.haxx.se/docs/caextract.html
https://curl.haxx.se/ca/cacert.pem

this is what I had to do, in order to get the ocs windows agents working with a 3rd Party signed wildcard certificate on windows.

@damienbelliard 
Has the OCS team considered shipping this or a similar cacert.pem with the default windows installer?

**Comment by damienbelliard** [comment]
@FatCyclone Do you have a wildcard certificate ?

You can use this old documentation for SSL. 
http://wiki.ocsinventory-ng.org/index.php?title=Howtos:Install_OCS_on_debian

Our team works to update all OCS documentation and the SSL part

**Comment by FatCyclone** [comment]
@roll4life Thanks, i'll try that.

@damienbelliard Like I said, yes.

**Comment by fgentner** [comment]
Same issue with error: "ERROR *** AGENT => Failed to send Prolog <SSL connect error>"
Windows 10 Pro with OCS Agent Version 2.1.1.3, Wildcard cacert from some CA authority on Debian server. Works fine from Linux and MacOS clients.
ocsinventory.ini
[OCS Inventory Agent]
ComProvider=ComHTTP.dll
Debug=0
Local=
NoSoftware=0
HKCU=0
NoTAG=0
IpDisc=
[HTTP]
Server=https://ocs-ng.xxx.xx
SSL=1
CaBundle=cacert.pem
AuthRequired=0
User=
Pwd=
ProxyType=0
Proxy=
ProxyPort=0
ProxyAuthRequired=0
ProxyUser=
ProxyPwd=
[OCS Inventory Service]
TTO_WAIT=1260

**Comment by gillesdubois** [comment]
Hi,

Could you try with the 2.3.0.0 RC of the agent ( need a 2.3 server tho )
Some ssl certificats weren't compatible because of the OpenSSL version shipped in the agent. ( TLS 1.2 + )

Thanks for your contribution.
Regards,
Gilles Dubois.

**Comment by phillip-white-sociomantic** [comment]
@gillesdubois I am receiving the ssl error too:
```
Starting OCS Inventory NG Agent on Friday, February 10, 2017 11:05:28.
AGENT => Running OCS Inventory NG Agent Version 2.3.0.0
AGENT => Using OCS Inventory NG FrameWork Version 2.3.0.0
AGENT => Loading plug-in(s)
AGENT => Using network connection with Communication Server
AGENT => Using Communication Provider <OCS Inventory NG cURL Communication Provider> Version <2.3.0.0>
AGENT => Sending Prolog
ERROR *** AGENT => Failed to send Prolog <Problem with the SSL CA cert (path? access rights?)>
AGENT => Unloading communication provider
AGENT => Unloading plug-in(s)
AGENT => Execution duration: 00:00:01.
```

We have a 2.3 server with a wildcard ssl cert, and i am trying with `ssl=1` on the 2.3 agent. I don't have any cacert.pem in the directory and I don't specify one. I would have thought the agent validates the ssl cert based on the OS root certificates? The same way browsers do?

Or does the agent not yet support wildcard ssl certs?

**Comment by gillesdubois** [comment]
Hi,

If you have the SSL option set to 1, you need to put a cacert.pem on the agent.
If you don't put certificate on the agent this won't work.

Regards,
Gilles Dubois.

**Comment by arthur-thebear** [comment]
Hi,

got the same issue with the 2.3 server and agent, self-signed SSL with correct FQDN. How that could be resolved?

**Comment by gillesdubois** [comment]
Hi @arthur-thebear ,

Take a look at this issue that may help you on this problem : https://github.com/OCSInventory-NG/WindowsAgent/issues/31

Curl have a different behavior on windows and some certificates aren't managed properly.
More a curl issue than an agent one.

Regards,
Gilles Dubois.

**Comment by arthur-thebear** [comment]
Hi Gilles,

thank you for the advise, it is working now.

**Comment by vollkommenIrrelevant** [comment]
What was the solution? I'm using the IP insteead a FQDN and having the same problem...

**Comment by phillip-white-sociomantic** [comment]
@vollkommenIrrelevant Wildcard is not supported, so `ssl=1` will throw the error. You need to use `ssl=0` in the config files. `ssl=1` is for self signed certs. To make it more secure. Use HTTPS, block HTTP, setup htaccess username and password, and a realm for the https access to the server.

**Comment by kapouik** [comment]
NEVER USE ssl=0 IN PRODUCTION !

ssl=0 disable all ssl verification and your communication will be secure like in http. It's better to use a self signed certificate than disable ssl (OCS don't care about the CA). Today, OCS don't support SNI and wildcard but this will be add in the future.

**Comment by vollkommenIrrelevant** [comment]
@phillip-white-sociomantic 
I know.
The certificat for ocs is issued for the IP of the server and validated with a trusted wildcard certificate in top of chain.

Could it be a problem?

**Comment by phillip-white-sociomantic** [comment]
@kapouik Are you sure? OCS in prod with `ssl=0` is fine if you block port 80 for `Location /ocsinventory`, and only use https in the connection string. Then there is no unencrypted information like in http. That's the work around i've seen when we need to use wildcards.

@vollkommenIrrelevant I ran into issues when using IP in the cert. I used FQDN and had no issues

**Comment by kapouik** [comment]
@phillip-white-sociomantic Yes, I'm sure. ssl=0 disable CN verification : whitout it, anybody can do a man in the middle with any bad SSL certificat. 
As it, if you put this in production, there is a major risk on all your computer because OCS can control all of them (that"s why deployement is not possible without ssl).

**Comment by phillip-white-sociomantic** [comment]
@kapouik Thanks. We have disabled deployment until it works over https.

**Comment by arthur-thebear** [comment]
@vollkommenIrrelevant I just used the SSL of the CA and not of the OCS server

**Comment by vollkommenIrrelevant** [comment]
ok, interesting... I'm not shure, but with a self-signed certificate (to hostname insteead of IP) everything is fine. I will check with a valid one....

**Comment by vollkommenIrrelevant** [comment]
Ok, freaky...
If i make a (trusted) x.509 with windows, it's not working. 
I made all parts at Windows so there should be no problem. Maybe its because its "issuedby: *.xyz.com".

If i make a (nontrusted) x.509 in Ubuntu, it's working!

**Comment by rosada** [comment]
So wildcard SSL is imposible for OCS?
Or we still can use it with ssl=0 on an agent config?
So it was better using Self sign than wildcard?

**Comment by vollkommenIrrelevant** [comment]
yes, no wildcard ssl... SelfSign is working, but I didn't get the autoinstallation over groupPolicys.

**Comment by roll4life** [comment]
From my experience wildcard certificates signed by 3rd Party Root CA are not impossible. But per the post above by @gillesdubois they are not supported.  
Here is what worked for us on a mix of windows, ubuntu, and MacOS machines.   
Go to https://curl.haxx.se/docs/caextract.html grab the most recent cacert.pem open the file as text and verify that the entity who issued your CA is listed it should look something like this:
```
DigiCert Global Root CA
=======================
-----BEGIN CERTIFICATE-----
```
If it is listed then you can use the cacert.pem that you just downloaded.  
Otherwise if public key for your CA is **not** listed then your wildcard certificate will **not** work.  
**ssl=0 should never be used in production**  
if you are unable to get your wildcard certificate to work with ssl=1, then yes a self signed certificate would be a better option.

**Comment by stefjoe12** [comment]
Why is wildcard certificate not supported ? Will there be any support in the future for wildcard certificates ?

**Comment by sandaliero** [comment]
@stefjoe12 wildcard certificates are working, you only need to put the complete certificate chain in the cacert.pem file, first your wildcard certificate, then the intermediate certificate and third the root CA certificate. OCS Agent uses libcurl which can neither take certificates from the Windows storage nor download them itself, so you must have them all in place.
Open https://your_ocs_server/ocsinventory in Firefox, click on the SSL certificate icon (green lock), View Certificate - Details, than export all from Certificate Hierarchy, concatenate them from the last to the first one and put as cacert.pem in ProgramData\OCS Inventory NG\Agent and restart OCS Inventory Service. Check the log, should work fine.

**Comment by stefjoe12** [comment]
@sandaliero Thanks a lot, this resolved my issue. Have a nice weekend!

**Comment by Slyjohns** [comment]
@helicrenz 
Hello,
Have you solved your problem ?
I have an authority certification in my infrastructure, and i'm not able to find a cacert configuration who work for me ...

My schema is ROOT CA / INTERMEDIATE CA / MYSERVER CERTIF

**Comment by helicrenz** [comment]
Hello @Slyjohns ,

I decide to just use it without cert and use self-sign certificate. Since wildcard certificate will be use to your other domain i think its not secure that i can be access when you install ocs agent.

Regards,

Romeo

**Comment by therkd** [comment]
> Hello @stefjoe12 ,
> 
> How did you manage to make it work?
> 
> -----BEGIN RSA PRIVATE KEY----- (Your Private Key: your_domain_name.key) -----END RSA PRIVATE KEY----- -----BEGIN CERTIFICATE----- (Your Primary SSL certificate: your_domain_name.crt) -----END CERTIFICATE----- -----BEGIN CERTIFICATE----- (Your Intermediate certificate: DigiCertCA.crt) -----END CERTIFICATE----- -----BEGIN CERTIFICATE----- (Your Root certificate: TrustedRoot.crt) -----END CERTIFICATE-----
> 
> ?

Yes, this was exactly what ended up working for me on windows agent.
key-cert-intermediary-root in that order
