### ISSUE TITLE
[FEATURE REQUEST] report appx in software inventory

### ISSUE THREAD

**Issue by StCyr** [OCSInventory-NG/WindowsAgent#143]
AFAIK, the ocsi agent doesn't report installed appx (https://en.wikipedia.org/wiki/Universal_Windows_Platform_apps).

With the raise of these kind of software, it would be good if ocsi agent could report these in its inventories.

Getting the list of such installed softwares can be done with the following powershell one-liner:

`Get-AppxPackage -AllUsers`

**Comment by StCyr** [comment]
Sad to not read any comment on all those closed issues :-(

**Comment by gillesdubois** [comment]
Hi @StCyr ,

You created and sent us a plugin that why I didn't write any messages :) 
https://github.com/PluginsOCSInventory-NG/universalWindowsPlatformsApps

I through you created the plugin to overcome this issue.

Regards,
Gilles.

**Comment by StCyr** [comment]
Oh yes, that's true :-)

Plugin is good enough idd

Though, you've closed many other issues today, without comments most of the time :(

**Comment by gillesdubois** [comment]
No problems on that.

Most of the issues closed without comments are linked to a Pull Request OR we didn't get any anwser.

Regards,
Gilles.
