### ISSUE TITLE
Windows Agent 2.6.0 64 Bit and 32 Bit Windows

### ISSUE THREAD

**Issue by sokatra** [OCSInventory-NG/WindowsAgent#144]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General information
Operating system :  
Win 7- 32 Bit
### OCS Inventory information
Windows agent version : 
2.6.0
### Problem's description
OCS-Inventory Agent 2.6.0 is installable on 32 Bit System

### Inventory log file ( optional )

The installer doesn't exit on 32 Bit System - it just installs the Agent - but as expected the OCS-Inventory Service can't run - if i manually try to start the service i will get Error 216:0xd8.
it looks like that the client uses NSIS as Installer. NSIS is able to detect the Client Platform - so it should be possible to implement a client platform detection in OCS-Inventory Agent setup.
I also can Install the OCS Agent on XP - the setup should exit with an errorcode on platforms where they can't run.

Kind regards
Soktra

**Comment by drTr0jan** [comment]
Windows agent 2.6 doesn't support x86_32 architecture. But you can build it yourself.
Windows XP is not supported from 2.2 version.

**Comment by charleneauger** [comment]
Hi @sokatra ,

Windwos Agent 2.7 have an installer for 32 Bit system.

Best regards,
Charlene Auger
