### ISSUE TITLE
SSL agent 2.4 certificate issue

### ISSUE THREAD

**Issue by monkeydelufy** [OCSInventory-NG/WindowsAgent#146]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General information
Operating system :  Centos 7

### OCS Inventory information
Windows agent version : 2.4

### Problem's description
Hi,

i facing issue when i try to configure agent using ssl 
Starting OCS Inventory NG Agent on Monday, July 15, 2019 16:26:40.
AGENT => Running OCS Inventory NG Agent Version 2.4.0.0
AGENT => Using OCS Inventory NG FrameWork Version 2.4.0.0
AGENT => Loading plug-in(s)
AGENT => Using network connection with Communication Server
AGENT => Using Communication Provider <OCS Inventory NG cURL Communication Provider> Version <2.4.0.0>
AGENT => Sending Prolog
ERROR *** AGENT => Failed to send Prolog <Peer certificate cannot be authenticated with given CA certificates>
AGENT => Unloading communication provider
AGENT => Unloading plug-in(s)
AGENT => Execution duration: 00:00:00.
<Peer certificate cannot be authenticated with given CA certificates>

i try everything use .crt or use .pem still not working, but web to index.php working with this ssl,
any miss configuration please need help and advice.

Thanks. 

### Inventory log file ( optional )
*Use github cloud or trusted upload website*

**Comment by monkeydelufy** [comment]
please some one can help me to fix this, access to web browser already ssl but agent cannot communicated using ssl what i miss need advice..


Thanks.

**Comment by monkeydelufy** [comment]
`Starting OCS Inventory NG Agent on Tuesday, July 16, 2019 11:46:56.
AGENT => Running OCS Inventory NG Agent Version 2.4.0.0
AGENT => Using OCS Inventory NG FrameWork Version 2.4.0.0
AGENT => Loading plug-in(s)
	DLL PLUGIN => Searching for Plug-in DLL(s) in folder <C:\Program Files (x86)\OCS Inventory Agent\plugins>
	DLL PLUGIN => 0 DLL Plug-in(s) successfully loaded on 0 DLL(s) found
AGENT => Using network connection with Communication Server
	COM PROVIDER => Loading Communication Provider <C:\Program Files (x86)\OCS Inventory Agent\ComHTTP.dll>
AGENT => Using Communication Provider <OCS Inventory NG cURL Communication Provider> Version <2.4.0.0>
AGENT => Sending Prolog
	DID_CHECK => Read DeviceID <DESKTOP-MP3SHHM-2019-07-07-17-18-20> and MACs <F8:63:3F:C9:87:3A00:50:56:C0:00:0802:05:85:7F:EB:8010:E7:C6:E6:8C:D200:50:56:C0:00:0100:FF:F3:4A:42:6B> in file <ocsinventory.dat>
	COM SERVER => Initializing cURL library for sendRequest
	COM SERVER => Using cURL without server authentication
	COM SERVER => Disabling cURL proxy support
	COM SERVER => Enabling cURL SSL server validation support using CA Bundle <cacert.pem>
	COM SERVER => Sending HTTP Post request to URL <https://inventory.local.com/ocsinventory>
	WARNING *** COM SERVER => Failed to send HTTP Post request <Peer certificate cannot be authenticated with given CA certificates>
	COM SERVER => Cleaning cURL library
ERROR *** AGENT => Failed to send Prolog <Peer certificate cannot be authenticated with given CA certificates>
AGENT => Unloading communication provider
AGENT => Unloading plug-in(s)
AGENT => Execution duration: 00:00:01.`

**Comment by monkeydelufy** [comment]
how i can fix this any one please advice...

**Comment by monkeydelufy** [comment]
configuration
```
[OCS Inventory Agent]
ComProvider=ComHTTP.dll
Debug=1
Local=
NoSoftware=0
HKCU=0
NoTAG=0
IpDisc=
[HTTP]
Server=https://inventory.local.com/ocsinventory
SSL=1
CaBundle=cacert.pem
AuthRequired=0
User=
Pwd=
ProxyType=0
Proxy=
ProxyPort=0
ProxyAuthRequired=0
ProxyUser=
ProxyPwd=
[OCS Inventory Service]
TTO_WAIT=9000
INVENTORY_ON_STARTUP=1
PROLOG_FREQ=24
OLD_PROLOG_FREQ=24
```

**Comment by ewanoomen** [comment]
Try using SSL=0 instead of SSL=1. SSL=1 enables server certificate validation and requires a CA certificate. See https://wiki.ocsinventory-ng.org/03.Basic-documentation/Setting-up-the-Windows-Agent-2.x-on-client-computers/

**Comment by charleneauger** [comment]
Hi @monkeydelufy,

Can you try with 2.7 version ?

Regards,
Charlene Auger

**Comment by monkeydelufy** [comment]
hi @charleneauger 

its working now thanks for reply

**Comment by edgardau13** [comment]
hi @XCNBX 
How did you manage to solve this? I have the same problem.
thx
