### ISSUE TITLE
2.6 still not showing last logged in user.

### ISSUE THREAD

**Issue by bigben386** [OCSInventory-NG/WindowsAgent#148]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General information
Operating system :  Windows 10 pro

### OCS Inventory information
Windows agent version : 2.6.0.0

### Problem's description
*Describe your problem here* We have many computers that were upgraded from 2.4 to the 2.6 agent but still OCS does not correctly show the last logged in user. It seems like we have less systems without users but still the number is way higher than we had pre 2.4 agent.

### Inventory log file ( optional )
[OCSInventory.log](https://github.com/OCSInventory-NG/WindowsAgent/files/3596391/OCSInventory.log)

*Use github cloud or trusted upload website*

**Comment by pchamo** [comment]
I installed ocsagent 2.6 in two windows 10 computers. In one of them is not showing the connected user  anymore, so I reinstalled the agent 2.4 :(

**Comment by bigben386** [comment]
> I installed ocsagent 2.6 in two windows 10 computers. In one of them is not showing the connected user anymore, so I reinstalled the agent 2.4 :(

You do not have any issue with 2.4? We have had this issue every since we upgraded the agents from 2.2.

**Comment by pchamo** [comment]
As far as I can remember I have no issues with 2.4.

**Comment by DanaSaracut** [comment]
We have this issue with both 2.4 as 2.6 agents. Is anyone aware of a fix?
