### ISSUE TITLE
 Windows Agent data not inventoried, no errors in log

### ISSUE THREAD

**Issue by TTAK** [OCSInventory-NG/WindowsAgent#149]
### General information
Operating system :  
Windows 10 professionnal
### OCS Inventory information
Windows agent version : 
2.6
### Problem's description
The comptuter is not inventoried despite the comunication with the ocs server seems fine :
On a fresh install of OCS server 2.6 on Debian 10 and a fresh install of OCS agent 2.6.
I have an HTTP to HTTPS redirect on glpi.myprodserver.com
On a windows 10 computer I forced a manual inventory on the agent : 
Apache2 errors logs are empty

Apache2 acess log : 
```
glpi.myprodserver.com:443 client-ip - - [23/Sep/2019:19:49:38 +0200] "POST /ocsreports HTTP/1.1" 301 3657 "-" "OCS-NG_WINDOWS_AGENT_v2.6.0.0"
glpi.myprodserver.com:443 client-ip - - [23/Sep/2019:19:49:38 +0200] "GET /ocsreports/ HTTP/1.1" 200 6702 "-" "OCS-NG_WINDOWS_AGENT_v2.6.0.0"
```

/var/log/ocsinventory-server is empty

/etc/apache2/conf-available/z-ocsinventory-server.conf :
```
  # Master Database settings
  # Replace localhost by hostname or ip of MySQL server for WRITE
  PerlSetEnv OCS_DB_HOST localhost
  # Replace 3306 by port where running MySQL server, generally 3306
  PerlSetEnv OCS_DB_PORT 3306
  # Name of database
  PerlSetEnv OCS_DB_NAME ocs
  PerlSetEnv OCS_DB_LOCAL ocs
  # User allowed to connect to database
  PerlSetEnv OCS_DB_USER ocs
  # Password for user
  PerlSetVar OCS_DB_PWD XXXXXXXXXXXXXX
  [...]
  PerlSetEnv OCS_OPT_DBI_PRINT_ERROR 1
  [...]
  PerlSetEnv OCS_OPT_LOGLEVEL 1
```
Mod_Perl is up and running but it feel like PERL is not doing its thing at all...

### Inventory Agent log file
https://pastebin.com/EkKHLZSF

### Inventory Agent config :
```
[OCS Inventory Agent]
ComProvider=ComHTTP.dll
Debug=2
Local=
NoSoftware=0
HKCU=0
NoTAG=0
IpDisc=
[HTTP]
Server=https://glpi.myprodserver.com/ocsreports
SSL=0
CaBundle=cacert.pem
AuthRequired=0
User=
Pwd=
ProxyType=0
Proxy=
ProxyPort=0
ProxyAuthRequired=0
ProxyUser=
ProxyPwd=
[OCS Inventory Service]
PROLOG_FREQ=10
INVENTORY_ON_STARTUP=0
OLD_PROLOG_FREQ=10
TTO_WAIT=35400
```

**Comment by fbomj** [comment]
Hi,

Change the url in ocsinventory.ini file. Set Server=https://glpi.myprodserver.com/**ocsinventory** instead of Server=https://glpi.myprodserver.com/ocsreports. 
Stop service, Make the change and restart service. 
Regards
