### ISSUE TITLE
Send network shares

### ISSUE THREAD

**Issue by AnaelMobilia** [OCSInventory-NG/WindowsAgent#15]
Hi,

The agent inventories the local hard drives.
It doesn't provide network drives (mounted as a drive on the computer).

Is it possible to list these too ?
It will allow IT to check if all drives are correctly connected

Regards,
Anael

**Comment by gillesdubois** [comment]
Hi,

A plugin already exist for this : http://wiki.ocsinventory-ng.org/index.php/Plugins:SharedFolders/fr (Only in french unfortunately)
This one is going to be implemented in 2.2 soon.

Regards,
Gilles Dubois.
