### ISSUE TITLE
Compile Plugins when WSH is off

### ISSUE THREAD

**Issue by sokatra** [OCSInventory-NG/WindowsAgent#153]
### General information
Operating system :  
Windows 10
### OCS Inventory information
Windows agent version :  2.6.0

### Problem's description
All Plugin which i know are scripts - like the uptime plugin
This is a big problem if a company want's to disable the windows scripting host for security reasons.
here is how many companys disable the WSH
https://blog.f-secure.com/how-to-disable-windows-script-host/

I tried to convert a simple vb script with vbsedit to an exe file
https://www.vbsedit.com/
The exe is executed even if the WSH is disabled, because the exe file is using COM (Component Object Model) whic does't need the WSH.

It might be possible that you recommend a easy free way to compile all the plugins?
So companys can disable WSH and use AppLocker to only execute files with a signature
https://en.wikipedia.org/wiki/AppLocker
It will also be more secure if not the default temp folder is used on the windows client, because if some files can be executed in temp folder you can't use path rules in AppLocker which deies the execution of files in the temp folder.
This is necessary because of all the Virus Threats

### Inventory log file ( optional )
*Use github cloud or trusted upload website*

**Comment by gillesdubois** [comment]
Hi,

Plugins are now in powershell, most of the remaining scripts in VBS  will be soon deleted from our plugins repository.
We don't plan to implement an other way than powershell since GPO / AD allow you to have a strict policy that will still allow PS execution.

Regards,
Gilles Dubois.
