### ISSUE TITLE
OCS Inventory NG No muestra nombre de usuario

### ISSUE THREAD

**Issue by SoporteBios** [OCSInventory-NG/WindowsAgent#154]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General information
Operating system :  Windows 10 pro x64 Bits

### OCS Inventory information
Windows agent version : 2.1.1

### Problem's description
*In some computers of OCS Inventory does not show the username, It happens regardless of the operating system or hardware of the equipment, 32 or 64bit computers are affected equally
![Screenshot_8](https://user-images.githubusercontent.com/45672038/73451492-8072cb80-4346-11ea-9544-0721f0965f33.png)
*

### Inventory log file ( optional )
*Use github cloud or trusted upload website*

**Comment by gillesdubois** [comment]
Hi,

Please update your server and agents. Your server version is more than 6 years old ! 

Regards,
Gilles Dubois.
