### ISSUE TITLE
Agent OCS Windows 2.4  - Duplicate device

### ISSUE THREAD

**Issue by etiennep56** [OCSInventory-NG/WindowsAgent#156]
sur ma plateforme, plusieurs machines remontent régulierement en multiple exemplaire.
A chaque fois un nouveau deviceid est créé.
Sur le client on a ce type de message:
DID_CHECK => MAC Address changed new:<XX:XX:XX:XX:XX:XXYY:YY:YY:YY:YY:YY> old:<ZZ:ZZ:XX:XX:XX:XXDD:DD:XX:XX:XX:XXYY:YY:YY:YY:YY:YY>
DID_CHECK => Generating new unique ID for device <MMMMMMMM>

Et une nouvelle occurence de la ma machine apparait en base avec les mêmes infos sauf le deviceid.
Ce problème a déjà été remonté mais semblait être résolu en avec l'agent windows 2.4. Pour nous non.
Machine client en windows 7 32 bits.

Quelqu'un a--t-il une piste?

**Comment by sokatra** [comment]
I think this has something to do with this fix
https://github.com/OCSInventory-NG/WindowsAgent/pull/79/commits/d9e089fbda43514918bc0422ae70a154aa711f0d
