### ISSUE TITLE
Request: OCS WindowsAgent IPv6 support for OCS server access and communication.

### ISSUE THREAD

**Issue by joopmartens** [OCSInventory-NG/WindowsAgent#16]
For our mobile clients we're using Microsoft DirectAccess technology for them to be connected with the corporate network.

Initially DirectAccess has been designed as an IPv6 based service only but newer releases allow clients to connect to internal IPv4 resources. In this situation the DirectAccess clients are configured with a DNS name resolution policy to use the DirectAccess server as a DNS service for the corporate internal domains only. The DirectAccess Windows client now automatically uses the DirectAccess DNS server to resolve the internal domains. 

In case a client resolves a target that is IPv4 only the DirectAccess DNS server provides a "generated" IPv6 address to the client and takes care of 6to4 address translation.

This limits DirectAccess clients to only connect to internal IPv4 resources using their FQDN instead of their IPv4 IP address.
For local corporate systems and servers to initiate a connection towards a DirectAccess client native IPv6 is still required.

The OCS Windows agent (2.1.1.3) currently cannot send the Prolog to the internal OCS server for DirectAccess connected clients since it always seems to "resolve" to the internal IPv4 IP address (That is not accessible on IP bases for a DirectAccess client) though the OCS agent has been configured to use the FQDN.

The OCS Agent like any other application or CLI should simply use the IPv6 AAAA record in case one exists for the FQDN of the OCS servers or it should respect the DNS name resolution policy and use the DirectAccess server as a DNS server to acquire an IPv6 address and allow 6to4 address translation.

Normally this mechanism is automatically being done by the Windows client network layer. I'm not sure why this does not happen for the OCS Windows client. (Maybe because it does not support IPv6 at all for this process or it caches the IP address when the client is directly IPv4 connected to the internal corporate network?)

In general I can imagine that the requirement for future IPv6 implementations is raising in spite of the use of DirectAccess.

Thanks in advance for your support and thank you for providing this great product!

**Comment by frouxel** [comment]
Hello,

We have the same behavior on OCSAgent 2.0.5.0, despite we can navigate on ocsreports Web Url from the direct Access client. Here is the log message :
ERROR *** AGENT => Failed to send Prolog <Couldn't resolve host name>

Is there some work on progress for this case ?
Thanks a lots for the job on OCSInventory

**Comment by pilch-cit** [comment]
Hello,

we also are very interested in IPv6 support for the OCS Windows agent.
The current version cannot communicate over IPv6 or collect IPv6 addresses from the host.
Maybe the agent uses some old library for communication. The log says the agent could'nt resolve the hostname.

We implemented an powershell script to collect IPv6 information from the host but in my opinion this is only a temporary solution (especially because we need an vb script to run the ps script).

You can get addresses and prefixes from wmi or netsh.  AFAIK wmi is already used by the ocs agent so maybe wmi is the easiest way to get IPv6 information from the host.

Best Regards

**Comment by charleneauger** [comment]
Hi @joopmartens @frouxel @pilch-cit ,

The IPV6 network support is now available on our agent ! :)

Regards,
Charlene Auger
