### ISSUE TITLE
get user installed software

### ISSUE THREAD

**Issue by sokatra** [OCSInventory-NG/WindowsAgent#163]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General information
Operating system :  
CentOS 8
### OCS Inventory information
OCS-Inventory Server 2.7
Windows agent version : 2.0.5

### Problem's description
Users often Install Software on their own, but this software isn't reported in OCS-Inventory

### Inventory log file ( optional )
*Use github cloud or trusted upload website*

It would be really nice if we can get all software which is installed as user (chrome, opera , dropbox for example)

here some links which perhaps helps a programmer to develop such a Feature

What your traditional software inventory solution does not tell you
https://blog.applixure.com/en/what-your-traditional-software-inventory-solution-does-not-tell-you

Find/Inventory Applications Installed in AppData (User's Profile folder)
https://www.reddit.com/r/SCCM/comments/ecwt60/findinventory_applications_installed_in_appdata/fbgwgc5/

Detecting installed programs via registry
https://stackoverflow.com/questions/429738/detecting-installed-programs-via-registry

How To: Get user installed software on Windows 7 in KACE Inventory
https://www.itninja.com/blog/view/how-to-get-user-install-software-on-a-windows-7-in-kace-inventory

Detect Software Installed at User Level
https://www.neteye-blog.com/2014/10/ocs-inventory-detect-software-installed-at-user-level/

Load user registry hive in regedit
http://www.zeda.nl/index.php/en/load-user-registry-hive-in-regedit

Modifying the Registry for All Users with PowerShell
https://www.pdq.com/blog/modifying-the-registry-of-another-user/
if you can modify the keys - you can also report the keys

Kind regards Sokatra

**Comment by sokatra** [comment]
Get-ChildItem -Path HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall | Get-ItemProperty | Where-Object {$_.DisplayName -match 'Chrome' } | Select-Object -Property DisplayName, UninstallString

to find any user installed software uninstall string

 Get-ChildItem -Path HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall | Get-ItemProperty | Where-Object {$_.DisplayName -like '*' } | Select-Object -Property DisplayName, UninstallString

**Comment by charleneauger** [comment]
Hi @sokatra ,

Recently we developed a plugin which allows to inventory software installed by users.
Here the link : https://github.com/PluginsOCSInventory-NG/userinstalledapps/releases/tag/2.0

Best regards,
Charlene
