### ISSUE TITLE
Computername is limited to 15 characters

### ISSUE THREAD

**Issue by sciolto** [OCSInventory-NG/WindowsAgent#164]
### General information
Operating system :  Any Windows version 

### OCS Inventory information
Windows agent version : 2.6 and  2.4

### Problem's description
The Agent registers the computer name using its NetBIOS name, which is limited to 15 characters. It would be great if the agent would allow to save the FQDN as computer name.

**Comment by gillesdubois** [comment]
Hi,

We don't plan on implementing this kind of behavior since we already register the domain name.
having the FQDN machine name is not a plus for us.

Regards,
Gilles Dubois.
