### ISSUE TITLE
library missing in WindowsAgent 2.7.0.0

### ISSUE THREAD

**Issue by KazimierzSyncron** [OCSInventory-NG/WindowsAgent#166]
### General information
Operating system :  Windows 10 2004 x64 Pro

### OCS Inventory information
Windows agent version : 2.7.0.0

### Problem's description
OCS Agent (GUI & service) is not starting because vcruntime140_1.dll is not provided with the installation. It works only, if you upgrade it from previous version (2.6.0.1).
Please include vcruntime140_1.dll in the 2.7.0.0 installer.

**Comment by charleneauger** [comment]
Hi @KazimierzSyncron ,

Thanks for your report ! The installer has been updated on the release archive.

Best regards,
Charlene Auger
