### ISSUE TITLE
upgrade openssl library

### ISSUE THREAD

**Issue by hawkmud99** [OCSInventory-NG/WindowsAgent#17]
Windows agent installs with ssleay32 & libeay32 from openssl 1.0.0s which doesn't support tls1.2.  Is it possible to get this upgraded the openssl library to 1.0.2 to support tls1.2 communication?

**Comment by gillesdubois** [comment]
Hi,

I re-opened your issue in the right section.
An upgrade of openssl lib will be made on the 2.2 version of windows agent

Regards,
Gilles Dubois.

**Comment by gillesdubois** [comment]
Hi,

I just compile openssl 1.0.2  and update the dependencies script.
https://github.com/OCSInventory-NG/WindowsAgent/commit/4517a321fa7c9af505036dd47979b4bf54c8cd47

Openssl 1.0.2 will be available in the 2.2 agent
