### ISSUE TITLE
issue installing agent 2.6 on server 2012r2

### ISSUE THREAD

**Issue by killmasta93** [OCSInventory-NG/WindowsAgent#172]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General information
Operating system :  windows

### OCS Inventory information
Windows agent version : 2012r2

### Problem's description
*Describe your problem here*
install the agent but get the error on api-ms-win-crt-string-l1-1-0.dll
i check and i dont see the server

### Inventory log file ( optional )
*Use github cloud or trusted upload website*

********************************************************
Starting OCS Inventory NG Agent 2.6.0.1 setup on 11/07/2020 at 16:50:49
Checking if setup not already running...OK.
Checking Operating System...OK, Windows 2000 or higher.
Command line is: "\\192.168.1.200\shares\publica\sistemas\inventory\OCS-NG-Windows-Agent-Setup.exe" 
Parsing command line arguments...OK.
Checking for silent mode...Disabled.
Checking for splash screen...Enabled.
Checking if logged in user has Administrator privileges...OK.
Creating directory <C:\ProgramData\OCS Inventory NG\Agent>...
SetACL allowing Users / Power users read/write permissions on <C:\ProgramData\OCS Inventory NG\Agent>...Result: error
SetACL propagating inherited permissions on <C:\ProgramData\OCS Inventory NG\Agent\Download>...Result: error
Trying to determine if service was previously installed...No.
Trying to stop service and kill processes...
Trying to kill process OcsSystray.exe...Result: 603
Trying to kill process OcsService.exe...Result: 603
Trying to kill process OCSInventory.exe...Result: 603
Trying to kill process download.exe...Result: 603
Trying to kill process inst32.exe...Result: 603
Waiting 10 seconds for processes to terminate...
Copying new files to directory <C:\Program Files\OCS Inventory Agent>...
Windows XP or higher detected, installing default cURL library and MS CRT/MFC 9.0...
Copying new files status is ;-)
Writing TAG <inmorro> into <C:\ProgramData\OCS Inventory NG\Agent\admininfo.conf> file...
Writing agent configuration file by launching ocsinventory.exe /SAVE_CONF...Result: -1073741515
Windows Advanced Firewall is not available (Vista or higher). Skip adding custom rules.
[/NOW] used, so launching "C:\Program Files\OCS Inventory Agent\ocsinventory.exe"...Result: -1073741515
Creating startup menu shortCut <C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Startup\OCS Inventory NG Systray.lnk> to start Systray applet...
Checking if service OCS Inventory Service is registered into Windows Service Manager...No
No service installed, so no need to unregister OCS Inventory Service from Windows Service Manager.
Registering OCS Inventory Service into Windows Service Manager...Result: -1073741515.
SUCCESS: OCS Inventory NG Agent 2.6.0.1 successfully installed on 11/07/2020 at 16:51:37
;-)

**Comment by drTr0jan** [comment]
Try to install later windows updates.
I've faced with same issue on 2.7.0.1. But the agent has been installed correctly after windows updates installation.

**Comment by killmasta93** [comment]
thanks for the reply, which windows update? a specific update? the issue is that running blindly windows updates on a server is not the best option for me

**Comment by charleneauger** [comment]
Hi @killmasta93 ,

We recommend  to install all important windows updates. 

Regards,
Charlene Auger
