### ISSUE TITLE
error code 1053 when running show inventory informations

### ISSUE THREAD

**Issue by slasse** [OCSInventory-NG/WindowsAgent#173]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General information
Operating system :  
windows 10 x64

### OCS Inventory information
Windows agent version : 2.6.0 and 2.7.0

### Problem's description
when running show inventory informations after about a minute or so i get a message with error code 1053 about the service not answering a command correctly:

![image](https://user-images.githubusercontent.com/5870570/87300788-cd221b80-c50e-11ea-9a68-c145cc23ddd3.png)

### Inventory log file ( optional )
nothing is written to the log with this action, only about sending the report to the server which is working fine.
even with debug on in the ini file

**Comment by charleneauger** [comment]
Hi,

A new version 2.7.0.1 of the windows agent is available ! Please, try with it and reopen an issue if the problem persist.

Best regards,
Charlene Auger
