### ISSUE TITLE
2.7.0.0 Not installing windows service

### ISSUE THREAD

**Issue by bigben386** [OCSInventory-NG/WindowsAgent#175]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General information
Operating system :  Windows 10 Pro x64 1909 and 2004

### OCS Inventory information
Windows agent version : 2.7.0.0 x64

### Problem's description
*Describe your problem here*
I have many new computers that we have deployed the OCS agent to that are not sending inventory. We deploy the agent with the following switches: /S /NOSPLASH /NO_SYSTRAY /NOW /notag /server=https://<server> /ssl=1 /ca="<path to ca file>"

So the agent is not sending the inventory /NOW and also there is no OCS service registered on the machines. I have tried manually installing the agent through the gui and it also has the same behavior with no errors shown.

The config file seems to be either incomplete or corrupted (extension changed for upload)

### Inventory log file ( optional )
*Use github cloud or trusted upload website*
[ocsinventory.ini.txt](https://github.com/OCSInventory-NG/WindowsAgent/files/4938733/ocsinventory.ini.txt)

**Comment by loderunner84** [comment]
Same on  Microsoft Windows 7 Professional   6.1.7601 Service Pack 7601
install log:
********************************************************
Starting OCS Inventory Agent 2.7.0.0 setup on 24/07/2020 at 11:37:45
Checking if setup not already running...OK.
Checking Operating System...OK, Windows 2000 or higher.
Command line is: OCS-Windows-Agent-Setup.exe  /S /NOSPLASH /NOW /SSL=0 /SERVER=http://server/ocsinventory /DEBUG=1 /NO_SYSTRAY 
Parsing command line arguments...OK.
Checking for silent mode...Enabled.
Checking for splash screen...Disabled.
Checking if logged in user has Administrator privileges...OK.
Creating directory <C:\ProgramData\OCS Inventory NG\Agent>...
SetACL allowing Users / Power users read/write permissions on <C:\ProgramData\OCS Inventory NG\Agent>...Result: error
SetACL propagating inherited permissions on <C:\ProgramData\OCS Inventory NG\Agent\Download>...Result: error
Trying to determine if service was previously installed...No.
Trying to stop service and kill processes...
Trying to find process OcsSystray.exe...Result: No
Trying to kill process OcsSystray.exe...Result: No
Trying to kill process OcsService.exe...Result: 603
Trying to kill process OCSInventory.exe...Result: 603
Trying to kill process download.exe...Result: 603
Trying to kill process inst32.exe...Result: 603
Waiting 10 seconds for processes to terminate...
Copying new files to directory <C:\Program Files\OCS Inventory Agent>...
Windows XP or higher detected, installing default cURL library and MS CRT/MFC 9.0...
Copying new files status is ;-)
Writing agent configuration file by launching ocsinventory.exe /SAVE_CONF...Result: -1073741515
Windows Advanced Firewall is not available (Vista or higher). Skip adding custom rules.
[/NOW] used, so launching "C:\Program Files\OCS Inventory Agent\ocsinventory.exe"...Result: -1073741515
[/NO_SYSTRAY] used, so removing Systray applet startup menu shortcut <C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Startup\OCS Inventory NG Systray.lnk>...
Checking if service OCS Inventory Service is registered into Windows Service Manager...No
No service installed, so no need to unregister OCS Inventory Service from Windows Service Manager.
Registering OCS Inventory Service into Windows Service Manager...Result: -1073741515.
SUCCESS: OCS Inventory Agent 2.7.0.0 successfully installed on 24/07/2020 at 11:38:26
;-)
 
is only one PC get that issue

**Comment by charleneauger** [comment]
Hi,

A new version 2.7.0.1 of the windows agent is available ! We fixed the bug with the previous version.

Best regards,
Charlene Auger

**Comment by loderunner84** [comment]
have the same result with 2.7.0.1
********************************************************
Starting OCS Inventory NG Agent 2.7.0.1 setup on 27/07/2020 at 9:31:35
Checking if setup not already running...OK.
Checking Operating System...OK, Windows 2000 or higher.
Command line is: "C:\ProgramData\OCS Inventory NG\Agent\OCS-Windows-Agent-Setup-x64.exe"  /S /NOSPLASH /SERVER=http://ocs.ukdina.local/ocsinventory /S /NOSPLASH /NOW /SSL=0 /CA=cacert.pem /DEBUG=1 /NO_SYSTRAY
Parsing command line arguments...OK.
Checking for silent mode...Enabled.
Checking for splash screen...Disabled.
Checking if logged in user has Administrator privileges...OK.
Creating directory <C:\ProgramData\OCS Inventory NG\Agent>...
SetACL allowing Users / Power users read/write permissions on <C:\ProgramData\OCS Inventory NG\Agent>...Result: error
SetACL propagating inherited permissions on <C:\ProgramData\OCS Inventory NG\Agent\Download>...Result: error
Trying to determine if service was previously installed...Yes.
Trying to stop service and kill processes...
Is Service <OCS Inventory Service> running...No.
Trying to stop Service <OCS Inventory Service>...Служба не запущена.

Is Service <OCS Inventory Service> running...No - Waiting 1 second(s) for Service to stop...
Trying to find process OcsSystray.exe...Result: Yes
Trying to kill process OcsSystray.exe...Result: Yes
Trying to kill process OcsService.exe...Result: 603
Trying to kill process OCSInventory.exe...Result: 603
Trying to kill process download.exe...Result: 603
Trying to kill process inst32.exe...Result: 603
Waiting 10 seconds for processes to terminate...
Copying new files to directory <C:\Program Files\OCS Inventory Agent>...
Windows XP or higher detected, installing default cURL library and MS CRT/MFC 9.0...
Copying new files status is ;-)
Writing agent configuration file by launching ocsinventory.exe /SAVE_CONF...Result: -1073741515
Windows Advanced Firewall is not available (Vista or higher). Skip adding custom rules.
[/NOW] used, so launching "C:\Program Files\OCS Inventory Agent\ocsinventory.exe"...Result: -1073741515
[/NO_SYSTRAY] used, so removing Systray applet startup menu shortcut <C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Startup\OCS Inventory NG Systray.lnk>...
Checking if service OCS Inventory Service is registered into Windows Service Manager...Yes
Service is installed, so unregistering OCS Inventory Service from Windows Service Manager...Result: -1073741515.
Registering OCS Inventory Service into Windows Service Manager...Result: -1073741515.
Starting OCS Inventory Service...Служба не ответила на запрос своевременно.
.
SUCCESS: OCS Inventory NG Agent 2.7.0.1 successfully installed on 27/07/2020 at 9:32:22
;-)
 install from agent deployment tool

**Comment by bigben386** [comment]
2.7.0.1 did resolve my issue related to service installation.

**Comment by loderunner84** [comment]
I think it is OS issue not OCS Agent in my case. But, "SUCCESS: OCS Inventory NG Agent 2.7.0.1 successfully installed" may be misleading.
