### ISSUE TITLE
Update Documentation for Agent Compilation

### ISSUE THREAD

**Issue by HassanAkbar** [OCSInventory-NG/WindowsAgent#181]
We need to update the documentation for Agent Version 2.7.0.0 & 2.7.0.1 (as new versions support Windows 32 as well).
http://wiki.ocsinventory-ng.org/03.Basic-documentation/Setting-up-the-Windows-Agent-2.x-on-client-computers/
http://wiki.ocsinventory-ng.org/12.Developers/HOWTO-compile-OCS-Windows-Agent/

I can open a PR for that. But I have two questions before I proceed for 2.7.0.0/2.7.0.1 Build generation?

1. For ZipArchive.sln, did you use `Release Unicode STL MD DLL for platform for Win32` [`like in old versions`](https://github.com/OCSInventory-NG/WindowsAgent/blob/2.4.0.0/README.TXT#L54)  for both 32 and 64 bit machines?
2. Are you building main solution with `x86` for both 32 and 64 bit machines?

@charleneauger @gillesdubois your feedback is appreciated.

**Comment by gillesdubois** [comment]
Hi @HassanAkbar , 

* For 32Bits machines we use the 32 Bits version of ZipArchive "Release Unicode STL MD DLL"
* For 64Bits machines we use the 64 Bits version of ZipArchive. Please note that this version need to be paid to the editor.
* Each agent version is compiled with their corresponding architecture

Regards,
Gilles Dubois.
