### ISSUE TITLE
OCS Agent wont unzip files from package (store option)

### ISSUE THREAD

**Issue by yild** [OCSInventory-NG/WindowsAgent#182]
### General information
Operating system :  
Windows 10 PRO (agent machine)
Debian 10 (ocs server 2.7)

### OCS Inventory information
Windows agent version : 2.7.0.1

### Problem's description
While preparing deploy packages for additional OCS plugins, unzip function failed, file wasn't created on destination machine.
Deployed file was standard single file in root folder of zipped file.

I have tried multiple destination folders: OCS agent installation, other partitions, etc.

Deployed package info file:
`<?xml version="1.0" encoding="UTF-8"?>
<DOWNLOAD ID="1597914960" PRI="0" ACT="STORE" DIGEST="cb74c48165f11e6604eafce4bb31c8e9" PROTO="HTTPS" FRAGS="0" DIGEST_ALGO="MD5" DIGEST_ENCODE="Hexa" PATH="e:\" NOTIFY_USER="0" NOTIFY_TEXT="" NOTIFY_COUNTDOWN="" NOTIFY_CAN_ABORT="0" NO$
`
After changing FRAGS to "1", file was correctly unziped into destination folder.

While files wasn't unziped there was return info as SUCCESS

DOWNLOAD => Package <1597914960> built successfully
DOWNLOAD => Executing action <STORE> for package <1597914960>
PACKAGE => Unzipping data to folder <e:\> for package <1597914960> on <Thursday, August 20, 2020 11:19:49>
PACKAGE => Package <1597914960> successfully stored to folder <e:\>
PACKAGE => No post execution command provided for package <1597914960>
DOWNLOAD => Sending result code <SUCCESS> for package <1597914960>

This can be related to OCS Server Build function that incorrectly creating 'info' files.

**Comment by gillesdubois** [comment]
Hi,

The issue was related to the server and is now fixed in the master branch.
You can try out the nightly if you want to remove the problem.

The 2.8 is coming mid september in the case you want to wait for a stable version :) 

Regards,
Gilles Dubois.
