### ISSUE TITLE
Additional files inside installation exe file

### ISSUE THREAD

**Issue by yild** [OCSInventory-NG/WindowsAgent#184]
### OCS Inventory information
Windows agent version : 2.7

### Problem's description

How could I add additional files to agent installation exe file, i.e. new certificate file or install ocs agent with additional plugins files without creating deployment (without need to change certificate) - my environment is mixed with AD connected machines, standalone machines in remote offices, etc.

**Comment by gillesdubois** [comment]
Hi,

Please check our documentation before posting.

http://wiki.ocsinventory-ng.org/07.OCS-Tools/OCS-Windows-Packager/

Regards,
Gilles Dubois.
