### ISSUE TITLE
error code 1053 when running show inventory informations

### ISSUE THREAD

**Issue by slasse** [OCSInventory-NG/WindowsAgent#187]
It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.

re-opening of issue #173
after updating to the latest version of the agent as requested in the previous issue the issue persists

General information
Operating system :
windows 10 x64

OCS Inventory information
Windows agent version : 2.6.0 and 2.7.0 and 2.7.1

Problem's description
when running show inventory informations after about a minute or so i get a message with error code 1053 about the service not answering a command correctly:

Inventory log file ( optional )
nothing is written to the log with this action, only about sending the report to the server which is working fine.
even with debug on in the ini file

**Comment by windshaman** [comment]
Hello, please try to uninstall Agent and delete manually leftover files in : 

- C:\ProgramData\OCS Inventory NG

- C:\Program Files\OCS Inventory Agent

Reboot your computer and try to install Agent again as Administrator (right click -> Install as Administrator). It solved the issue on some computers.

**Comment by charleneauger** [comment]
Hi @slasse ,

Thanks @techlifejacket for the solution.
I close this issue.

Regards,
Charlene
