### ISSUE TITLE
Not all installed softwares are listed

### ISSUE THREAD

**Issue by link89** [OCSInventory-NG/WindowsAgent#19]
I found that softwares in OCS installed software list is less than the ones in control panel's add/remove softwares. In SysInfo/SysInfo.cpp I found this function BOOL CSysInfo::getInstalledApplications(CSoftwareList *pList, BOOL hkcu) use WMI to fetch installed softwares, which according to http://stackoverflow.com/questions/673233/wmi-installed-query-different-from-add-remove-programs-list, only show softwares installed by msi. I was wondering if it's a better solution to fetch software list from Uninstall Registry Key?

**Comment by dpthakar** [comment]
I am facing same issue, 
software like utorrent is not listed, one of nice use of this tool to track if any unwanted software is installed.
It would be nice to have all installed software being reported to ocs-server.

**Comment by link89** [comment]
@gillesdubois great to know you start handle this issue :-)  Is it possible to include this fix in next release?

**Comment by hd74** [comment]
Are there a way to manually add files you want to inventory? Like a list:
"C:\Program Files\MyApp\Main.EXE" = "My Own App"
And then the agent could search for those files and add to the software list.

**Comment by link89** [comment]
@hd74 You can just hack CSysInfo::getInstalledApplications(CSoftwareList *pList, BOOL hkcu) in SysInfo/SysInfo.cpp to read your configuration files.

**Comment by hd74** [comment]
@link89 Thank you for the tip! But I first need to add a system to the WebGUI to manage the file inventory list, and then figure out the best place to add the function the the agent. Too bad there is no such function already available.

Now I use a workaround by adding a fake software to the add/remove software list in Windows when I create a software package with a software that doesn't have a native entry in this list. This way, OCS can inventory and list the software.

**Comment by gillesdubois** [comment]
Hi,

Indeed somes installed softwares are not listed but that because they are not using a conventional way for it installation.
After reading the agent's code we use the registry and WMI to inventory installed softwares but some softwares don't use the conventional registry diretory for it inventory.
You can inventory them using the registry key functionnality.

Regards,
Gilles Dubois.

**Comment by hd74** [comment]
That's great! Thank you Gilles for that great tip!

Does anyone know how to turn the "Enable query registry feature" on? The thumbnails in the docs seems gone?:
http://wiki.ocsinventory-ng.org/index.php?title=Documentation:Administration#Enable_query_registry_feature

**Comment by hd74** [comment]
Well, it wasn't so hard figuring out how to enable the registry feature after all, but it still would be a good idea to update the wiki thumbnails. Me myself could not create a wiki login account, so I guess someone else might be able to put up some nice thumbnails? ;)

**Comment by gillesdubois** [comment]
Hi,

Currently our wiki if under rework, you can check out the new one at this link ( WIP ) : https://github.com/OCSInventory-NG/Wiki

At least screens should be there :)
