### ISSUE TITLE
OCS-Inventory Agent 2.8 missing  (32 bit installer )api-ms-win-crt-runtime-l1-1-0.dll

### ISSUE THREAD

**Issue by sokatra** [OCSInventory-NG/WindowsAgent#193]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General information
Operating system :  
windows 7 64 Sp1 -32 bit - not completly patched with alle windows updates
### OCS Inventory information
Windows agent version : 
2.8 -32 bit
### Problem's description
after installing .. a message appears (OCSsystray.exe - System Error"
OCS-Inventory Agent 2.8 missing  (32 bit installer )api-ms-win-crt-runtime-l1-1-0.dll

**Comment by sokatra** [comment]
on 64 bit windows - the 64 bit insaller of agent 2.8.0 does not writes an error .. but if i go to 
C:\Program Files\OCS Inventory Agent and doubleclik on ocsnotify.user.exe 
the same message appears
https://ibb.co/CH6bF8j
which let me think that thios dll is also missing
Kind regards
Sokatra

**Comment by sokatra** [comment]
after installing Visual C++ Redistributable für Visual Studio 2015 i have a systray icon .. but now if i click in thios to get the report a message similar to
can't connect to ocs-inventory-serfice.. error code 1060 = the named service is not an installed service.
This was a translated message , becuase i use windows with another language 

i can tell you that i reinstalled the agent and now it works .. so a missing Visual C++ Redistributable für Visual Studio 2015 isn't enough if installed afterwards.

**Comment by charleneauger** [comment]
Hi @sokatra ,

The Windows Agent x86 and x64 has been tested on a fully updated Windows 7 SP1 32 bits and 64 bits. Since Windows 7 has been around for a long time we didn't check every update of the system. In your case the 2.8 version should work without any problems on a fully updated instance. 

Regards,
Charlène.

**Comment by sokatra** [comment]
Thanks , it works with a fully patched win 7 Sp1 -  32 Bit Machine (so no error settings) .. bu for some reason i get "failed sending control message to OCS Inventory Service.. Error code 1053 = The service did not respond to the start or control request in a timely fashion," when i klick on "show inventory informations".
network was disabled .. i installed the agent with default settings.

**Comment by charleneauger** [comment]
Hi @sokatra ,

I close this issue because the dll problem has been fixed.

Best regards,
Charlene Auger
