### ISSUE TITLE
Bad installation directory

### ISSUE THREAD

**Issue by pintyoke** [OCSInventory-NG/WindowsAgent#203]
### General information
Operating system :  Windows 10 (up to date)

### OCS Inventory information
Windows agent version : 2.8.0.0 (64bit)

### Problem's description
If I install it on a workstation that doesn't have an old ocs agent, everything is fine. If I want to upgrade from version 2.1.1.1 to version 2.8.0.0, the 64-bit version will be placed in the "C:\Program Files (x86)" directory.

**Comment by olivier-david** [comment]
I have the same problem.
