### ISSUE TITLE
OCSLogon didn't find 64bit agent and installs on every call

### ISSUE THREAD

**Issue by ggzengel** [OCSInventory-NG/WindowsAgent#209]
### General information
Operating system :  Windows

### OCS Inventory information
Windows agent version : 2.8.0 64bit
I still use OCSLogon 2.3.1.1 but there is no change for 64bit in the code since this release.

### Problem's description
I use always ocslogon to deploy OCSAgent. After switching to 64bit I have big problems because OCSLogon can't handle 64bit.
> Searching OCS Inventory NG Agent installed version...OK (0.0.0.0)

```
C:\>wmic service "OCS Inventory Service" get pathname
PathName
"C:\Program Files\OCS Inventory Agent\OcsService.exe"

C:\>"D:\work\ocs installer2.noscan\OLD\OCSNG-Windows-Agent-2.3.1.1\OcsLogon.exe"

C:\>type c:\tmp\OcsLogon.log
********************************************************
Starting OCS Inventory NG Logon Installer 2.3.1.1 on 31/01/2021 at 19:05:50
Checking if not already running...OK
Parsing command line arguments...OK
Searching OCS Inventory NG Agent installed version...OK (0.0.0.0)
OCS Inventory NG Agent does not seems to be installed, setup version  required..
Download timeout is set to <60000> millisecond.
Download does not use HTTP proxy server.
Downloading file <http://ocsinventory-ng/ocsinventory/deploy/OCS-NG-Windows-Agent-Setup.exe> without server authenticati
on...OK (c:\tmp\OCS-NG_Agent_Setup.exe)
Starting OCS Inventory NG Agent installer...OK (exit code is 0)
Windows automatically starts OCS Inventory NG Service, no need to launch Agent.
All done, exiting ;-)

```

**Comment by kvolk2git** [comment]
Try the installation using the following method. Create install.cmd and run script on logon on logout windows over GPO

`
@echo off
set "prog=C:\Program Files (x86)\OCS Inventory Agent\OCSInventory.exe"
if not exist "%prog%" (
    \\hostname\share_with_OCS\OCS-Windows-Agent-Setup-x86.exe /S /server=http://domain_or_ip_server_ocs/ocsinventory /ssl=0
)
`

**Comment by ggzengel** [comment]
That's no solution, because we have multiple domains and no single UNC path. We use OCSlogon for bootstrapping the newest installer from OCS server.
For years we never updated OCSlogon. For some standalone systems we start OCSlogon with autostart.

I would like to have a new OCSlogon which I can download with old OCSlogon and this will install OCSagent.

**Comment by charleneauger** [comment]
Hi,

This file is no longer needed. You can check out our new documentation.

OcsLogon was generating a lot of false positive on antivirus which prevented some IT Services to install our software.

Regards,
Charlene
