### ISSUE TITLE
add column serial number in my groups

### ISSUE THREAD

**Issue by bluedark** [OCSInventory-NG/WindowsAgent#212]
hello, 
I would like to add columns like "serial number" when I go to my groups. 
On the other hand, I can add it when I am in "all computers". 
Thank you in advance!

**Comment by bluedark** [comment]
up
thanks!

**Comment by bluedark** [comment]
nobody ?
:'(

**Comment by charleneauger** [comment]
Hi @bluedark ,

This is an OCS Ivnetory Reports issue, please reopen your issue on the correct project.

Regards,
Charlene
