### ISSUE TITLE
2.9.0.0 HTTP Post response received <HTTP Status Code #400>

### ISSUE THREAD

**Issue by bigben386** [OCSInventory-NG/WindowsAgent#217]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General information
Operating system :  Windows 10 Pro x64 20H2

### OCS Inventory information
Windows agent version :  2.9.0.0

### Problem's description
*Describe your problem here*
I am not able to get agent 2.9.0.0 to communicate with our inventory server. "HTTP Post response received <HTTP Status Code #400>" is logged in the ocsinventory.log file. This is when running inventory in standalone mode. The exact same options work with agent 2.8.0.1 and prior.

### Inventory log file ( optional )
*Use github cloud or trusted upload website*
==============================================================================
Starting OCS Inventory Agent on Friday, June 25, 2021 12:08:11.
AGENT => Running OCS Inventory Agent Version 2.9.0.0
AGENT => Using OCS Inventory FrameWork Version 2.9.0.0
AGENT => Loading plug-in(s)
	DLL PLUGIN => Searching for Plug-in DLL(s) in folder <C:\Program Files\OCS Inventory Agent\plugins>
	DLL PLUGIN => 0 DLL Plug-in(s) successfully loaded on 0 DLL(s) found
AGENT => Using network connection with Communication Server
	COM PROVIDER => Loading Communication Provider <C:\Program Files\OCS Inventory Agent\ComHTTP.dll>
AGENT => Using Communication Provider <OCS Inventory cURL Communication Provider> Version <2.9.0.0>
AGENT => Sending Prolog
	DID_CHECK => Read DeviceID <xyz> and MACs <MACs> in file <ocsinventory.dat>
	COM SERVER => Initializing cURL library for sendRequest
	COM SERVER => Using cURL without server authentication
	COM SERVER => Disabling cURL proxy support
	COM SERVER => Enabling cURL SSL server validation support using CA Bundle <c:\programdata\roots.pem>
	COM SERVER => Sending HTTP Post request to URL <https://serverfqdn/ocsinventory>
	COM SERVER => HTTP Post response received <HTTP Status Code #400>
	COM SERVER => Cleaning cURL library
================= TRACE START ===============

================= TRACE STOP ===============
ERROR *** AGENT => Failed to send Prolog <HTTP Status Code #400>
AGENT => Unloading communication provider
AGENT => Unloading plug-in(s)
AGENT => Execution duration: 00:00:01.

Does the agent require the server to also be on 2.9.0.0 which does not seem to be released yet?

This is our standalone inventory command: OCSInventory.exe /notag /server=https://serverfqdn/ocsinventory /ssl=1 /ca="c:\programdata\roots.pem"

**Comment by charleneauger** [comment]
Hi @bigben386 ,

Can you provide me the server error log when the agent send his inventory ?

Regards,
Charlene

**Comment by bigben386** [comment]
Hey @charleneauger . Is the activity.log the one you are asking about? I have honestly never had to review the log on the server so I want to make sure that is the one you are asking for. This is the contents of that file. Looks like my guess about the agent being too new is likely the problem.

```
Tue Jun 29 16:58:44 2021;1493;400;-2021-06-29-16-49-43;OCS-NG_WINDOWS_AGENT_v2.9.0.0;useragent;Bad agent or agent version too recent for server !!
Tue Jun 29 16:58:44 2021;1493;106;-2021-06-29-16-49-43;OCS-NG_WINDOWS_AGENT_v2.9.0.0;prolog;stopped by module
Tue Jun 29 16:58:44 2021;1493;515;-2021-06-29-16-49-43;OCS-NG_WINDOWS_AGENT_v2.9.0.0;end;bad_request

```

**Comment by charleneauger** [comment]
Hi @bigben386 ,

Yes, it is this file :-) 
Has your server been updated from RPMs ?

If yes, we have some issues with rpm files on the latest version. Can you refer to this issue https://github.com/OCSInventory-NG/OCSInventory-ocsreports/issues/1215 and tell me if you have the same troubleshoot ? 

Best regards,
Charlene

**Comment by bigben386** [comment]
@charleneauger We install from source since we are running the server on Ubuntu. We have many Ocsinventory.pm files on our server:

> find / -iname Ocsinventory.pm
/usr/local/share/perl/5.8.7/Apache/Ocsinventory.pm
/usr/local/share/perl/5.8.8/Apache/Ocsinventory.pm
/usr/local/share/perl/5.10.1/Apache/Ocsinventory.pm
/usr/local/share/perl/5.14.2/Apache/Ocsinventory.pm
/usr/local/share/perl/5.18.2/Apache/Ocsinventory.pm
/usr/local/share/perl/5.22.1/Apache/Ocsinventory.pm
/root/OCSNG_UNIX_SERVER-1.02/Apache/Ocsinventory.pm
/root/OCSNG_UNIX_SERVER-1.02/Apache/blib/lib/Apache/Ocsinventory.pm

> perl -e "print qq(@INC)"
/etc/perl /usr/local/lib/i386-linux-gnu/perl/5.22.1 /usr/local/share/perl/5.22.1 /usr/lib/i386-linux-gnu/perl5/5.22 /usr/share/perl5 /usr/lib/i386-linux-gnu/perl/5.22 /usr/share/perl/5.22 /usr/local/lib/site_perl /usr/lib/i386-linux-gnu/perl-base


The current perl version on our server is 5.22.1. Line 42 of that file shows:
`$Apache::Ocsinventory::VERSION = '2.8.1';`

**Comment by charleneauger** [comment]
@bigben386 ,

Oh OK :-) 
The agent version must be less or equal than the server version. 
Please, update your server to 2.9 version and that should work like a charm ! ;-)

Best regards,
Charlene

**Comment by bigben386** [comment]
Is there some ETA on that? https://github.com/OCSInventory-NG/OCSInventory-Server/releases

**Comment by charleneauger** [comment]
The server release is available only on the OCSInventory-ocsreports project, here : https://github.com/OCSInventory-NG/OCSInventory-ocsreports/releases

**Comment by bigben386** [comment]
Sweet. Thanks @charleneauger
