### ISSUE TITLE
Security issue? public download Folder

### ISSUE THREAD

**Issue by sokatra** [OCSInventory-NG/WindowsAgent#218]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General information
Operating system :  win 10

### OCS Inventory information
Windows agent version : 2.05

### Problem's description
Isn't it a security problem that that all packages are downloaded to 
C:\ProgramData\OCS Inventory NG\Agent\Download
?
I was able to exchange the build.zip file during the time ocs-inventory  ask me to allow to install a program.
(the question was set by ocs-inventory server (warn user)
The deployment wasn't sucessfull after exchanging the zip file with a malicious file, but in principle i would feel better if the folders wasn't readable by a normal user.
the zip file hash should be checked or something similar.

I hope there was some sort of security mechanism that protects the files .. a do not allow exchanged files to be executed.

Kind regards
Sokatra

**Comment by sokatra** [comment]
package error after unsucessfull deplyoment ERR_BAD_DIGEST
so i think there was some sort of checking against this attack.

**Comment by charleneauger** [comment]
Hi @sokatra ,

Since version 2.10.1.0, the ProgramData\OCS Inventory NG\Agent folder is not accessible by a non-admin user.

Best regards,
Charlene
