### ISSUE TITLE
Renamed computers create duplicates in OCS

### ISSUE THREAD

**Issue by cconard96** [OCSInventory-NG/WindowsAgent#220]
### General information
Operating system :  Windows 10 20H2

### OCS Inventory information
Windows agent version : 2.8.0

### Problem's description
When you rename a computer, the old computer remains in the OCS server and a duplicate gets added with the new name. I assume it is partially an agent issue since the device ID uses the host name. This adds a ton of work on our end to manually clean up OCS, and fix the links in GLPI when we are trying to reassign a batch of 1000 computers (computer named for the user).

### Inventory log file ( optional )

I can open an issue on the communication server repo if needed.

**Comment by jackburton79** [comment]
You can configure the auto merging option to ignore the computer name (and only take into account the MAC address / ID).

**Comment by cconard96** [comment]
The last time I looked, it was already configured (I think by uuid).

Possibly unrelated, random computers are duplicated every time they check in. For those it seems to mostly be the 2.1.3 client but some are on the latest available.

The duplication uses up a lot of ID'S in the OCS and GLPI tables.

**Comment by charleneauger** [comment]
Hi @cconard96 ,

As @jackburton79 clarified, you can configure the auto merging on the server.
I think is more a communication server issue than a Windows agent issue.
Can you tell me what is your server version ?

Regards,
Charlene Auger

**Comment by cconard96** [comment]
Auto-merging is not really a solution when some computers have new entries created every single day (or check-in). The link with GLPI may be OK if it merges the new information into the oldest entry, but it would still be going through IDs in OCS like crazy. Then, if there are issues with orphaned data in table when computers are deleted we are greatly increasing the DB size and make it much worse than if it properly updated the existing computer without creating another first. This has happened before with software inventory to the point where it made our old OCS server unusable.

OCS Server is 2.9 currently but this has happened in our old server too. The only difference is that for some reason it would create the new entry and automatically delete the old one which is the complete opposite of what is desired. After the server became unusable from all the orphaned data we started fresh on a new server with the latest server version at the time. I don't remember the version for the old server but it was a few years old.

The OCS client versions doesn't seem to matter much as we have seen it occur with v2.1.1.3 (Client installed when we used the old server) and v2.8.0. It seems to happen less with the newer client but we also have it installed on less computers currently.

Auto merge config has "Serial" and "UUID" checked on the new server. On the old, I believe it was based on Serial and MAC.

**Comment by cconard96** [comment]
After some more investigation, I've found that the device ID is being changed once or twice a day for some of these computers.
The agent seems to get confused about the new virtual adapters added by our VPN client.

New additions when the VPN client is enabled:
```xml
<NETWORKS>
	<ID>357865</ID>
	<DESCRIPTION>CKMobile</DESCRIPTION>
	<TYPE>Dialup</TYPE>
	<TYPEMIB>ppp</TYPEMIB>
	<SPEED>866 Mb/s</SPEED>
	<MTU />
	<MACADDR>00:00:00:00:00:00</MACADDR>
	<STATUS>Up</STATUS>
	<IPADDRESS>172.17.129.64</IPADDRESS>
	<IPMASK>255.255.255.255</IPMASK>
	<IPGATEWAY>0.0.0.0</IPGATEWAY>
	<IPSUBNET>172.17.129.64</IPSUBNET>
	<IPDHCP />
	<VIRTUALDEV>0</VIRTUALDEV>
</NETWORKS>
```

```xml
<NETWORKS>
	<ID>357861</ID>
	<DESCRIPTION>Microsoft Wi-Fi Direct Virtual Adapter #2</DESCRIPTION>
	<TYPE>Other (see MIB)</TYPE>
	<TYPEMIB>Radio Spread Spectrum (802.11)</TYPEMIB>
	<SPEED>0 b/s</SPEED>
	<MTU />
	<MACADDR>86:FD:D1:C1:9A:76</MACADDR>
	<STATUS>Down</STATUS>
	<IPADDRESS>0.0.0.0</IPADDRESS>
	<IPMASK>0.0.0.0</IPMASK>
	<IPGATEWAY>0.0.0.0</IPGATEWAY>
	<IPSUBNET>0.0.0.0</IPSUBNET>
	<IPDHCP />
	<VIRTUALDEV>0</VIRTUALDEV>
</NETWORKS>
```
For some reason, neither are detected as a virtual device.
While looking for why/when the device ID is changed I found ff5cc2a488b57daf3b01b35a1ad395989dde8559 which seems to force the device ID to get changed when:
- Hostname changes (Not desired for us, but not terrible)
- There is only 1 MAC and it changes
- 2 MAC addresses are different between inventories when there are more than 1 present.

The last case here seems to be the problem.

The UUID and Serial don't change between the inventory data for two of the duplicates so I don't know why the auto-merge doesn't work at all...

**Comment by cconard96** [comment]
But then I have a Hyper-V VM on v2.8.0 of the windows agent that has nothing different between inventories other than the removal of a virtual DVD drive and it felt the need to change the device ID so I don't know.

**Comment by cconard96** [comment]
I no longer work with this company. I fully believe the main issue was the IT Director refused to finish updating the agents to the newer version on all our computers and servers and misconfigured the OCS inventory server.

I'll close this issue now as I don't have this issue personally anymore.
