### ISSUE TITLE
[OCS Agent 2.9.0.0 - Server 2.9.1] Problem HTTP Status Code #400 

### ISSUE THREAD

**Issue by cp61** [OCSInventory-NG/WindowsAgent#221]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General information
Operating system :  Windows 10 21h1

### OCS Inventory information
Windows agent version : 2.9.0.0
OCS Server : 2.9.1

### Problem's description
ERROR *** AGENT => Failed to send Prolog <HTTP Status Code #400> with Agent version 2.9.0.0

With the same computer and agent 2.8.0.0, any problem

**Comment by gillesdubois** [comment]
Hi,

I think your communication server didn't update properly.
Error 400 mean the server version is lower than the agent's.

Could you check the content of the file named "Ocsinventory.pm" on your server ?
There should be a reference to the version on the first lines.

Regards,
Gilles.

**Comment by cp61** [comment]
Hi Gilles

$Apache::Ocsinventory::VERSION = '2.9.1';

**Comment by gillesdubois** [comment]
Did you restart the apache server after performing the update ?

**Comment by cp61** [comment]
Thanks Gilles.

I restarted my server and everything is ok

Sorry for the inconvenience. instead of looking for times, let's keep it simple :)
