### ISSUE TITLE
Last 32bits agent compatibility

### ISSUE THREAD

**Issue by tempman5** [OCSInventory-NG/WindowsAgent#226]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General information
Operating system :  Windows 7/10

### OCS Inventory information
Windows agent version : 2.9

### Problem's description
I see in this table: https://wiki.ocsinventory-ng.org/03.Basic-documentation/Setting-up-the-Windows-Agent-2.x-on-client-computers/ that 2.4 agent version is the last 32bits compatible release, but I've for downloading the 2.9 version for 32bits. So, it isn't clear... What is the last version for 32bits that I have to use in W7 or W10 client computers?

Thanks beforehand.

### Inventory log file ( optional )
*Use github cloud or trusted upload website*

**Comment by charleneauger** [comment]
Hi @tempman5 ,

Indeed, our documentation is not up to date  for this part. Since 2.7.0.0 agent version, we decided to put the 32-bit versions back in place. So the last version that you have to use is the 2.9.0.0.
I will update the documentation soon as possible. 

Best regards,
Charlene Auger
