### ISSUE TITLE
Exit_code_32 in Windows 10 Agent

### ISSUE THREAD

**Issue by fleisis** [OCSInventory-NG/WindowsAgent#23]
Hi,

Im trying to deploy a .bat which contains a .exe installation with OCS (for example winrar.exe). This .bat file basically copy my ".exe" file from a shared folder in the remote PC & then execute it with runas /user:domain\administrador command.

I'd tryed this with action->execute & action->launch .bat but anyway it failed. I get the exit_code_32 on my w10 agent...
Here the logs:

File -> ocsinventory.log
> ==============================================================================
> 
>     Starting OCS Inventory NG Agent on Sunday, December 18, 2016 19:45:31.
>     AGENT => Running OCS Inventory NG Agent Version 2.1.1.3
>     AGENT => Using OCS Inventory NG FrameWork Version 2.1.1.3
>     AGENT => Loading plug-in(s)
>     AGENT => Using network connection with Communication Server
>     AGENT => Using Communication Provider <OCS Inventory NG cURL Communication Provider> Version <2.1.1.3>
>     AGENT => Sending Prolog
>     AGENT => Prolog successfully sent
>     SUPPORT => No support detected, Registration key : N/A
>     AGENT => Inventory required
>     AGENT => Launching hardware and software checks
>     AGENT => Communication Server ask for IpDiscover
>     AGENT => Sending Inventory
>     INVENTORY => Inventory changed since last run
>     AGENT => Inventory successfully sent
>     AGENT =>  Communication Server ask for Package Download
>     DOWNLOAD => Package <1482084428> added to download queue
>     DOWNLOAD => Download and setup tool successfully started
>     AGENT => Unloading communication provider
>     AGENT => Unloading plug-in(s)
>     AGENT => Execution duration: 00:00:40.

File -> download.log

> ==============================================================================
> Starting OCS Inventory NG Package Download and Setup Tool on Sunday, December 18, 2016 19:46:11.
> DOWNLOAD => Running OCS Inventory NG Download Version 2.1.1.3
> DOWNLOAD => Using OCS Inventory NG FrameWork Version 2.1.1.3
> DOWNLOAD => Using network connection with Communication Server
> DOWNLOAD => Using Communication Provider <OCS Inventory NG cURL Communication Provider> Version <2.1.1.3>
> DOWNLOAD => Starting new period of 10 cycles
> DOWNLOAD => Parsing directory <C:\ProgramData\OCS Inventory NG\Agent\download> for packages
> DOWNLOAD => Package <1482084428> verified and added to process queue
> DOWNLOAD => Downloading package fragment <1482084428-1>
> DOWNLOAD => Building package <1482084428>
> DOWNLOAD => Executing action <LAUNCH> for package <1482084428>
> ERROR *** DOWNLOAD => Will not register package <1482084428> in history: result <EXIT_CODE_32> not a success
> DOWNLOAD => Sending result code <EXIT_CODE_32> for package <1482084428>
> DOWNLOAD => Starting new period of 10 cycles
> DOWNLOAD => Parsing directory <C:\ProgramData\OCS Inventory NG\Agent\download> for packages
> DOWNLOAD => No package found, exiting
> DOWNLOAD => Unloading communication provider
> DOWNLOAD => Execution duration: 00:10:27.

I've SSL enabled on my server & i can see the download page in my W10 agent.

Any ideas? 
Thanks & Regards.

**Comment by gillesdubois** [comment]
Hi,

EXIT CODES of the agent are basically windows exit error code.

If you check your error on this page : https://msdn.microsoft.com/en-us/library/windows/desktop/ms681382(v=vs.85).aspx 

```
ERROR_SHARING_VIOLATION
32 (0x20)
The process cannot access the file because it is being used by another process.
```

That why you got an error ocs agent can't acces your file because it's already used by another process.

Regards,
Gilles Dubois.
