### ISSUE TITLE
Can't see my machines on my OCS - AGENT => Failed to send Prolog <HTTP Status Code #400>

### ISSUE THREAD

**Issue by Ouille85** [OCSInventory-NG/WindowsAgent#231]
Hello Everyone, I hope you can help

I'm having an issue, my OCS is well configured, everything os working, except one thing : The computers I installed the agent on are not shown on OCS.

The server and the computers can communicate.
The log I have on the agent is this one, and there is an error with HTTP it seems but I don't know how to fix it.

ERROR *** AGENT => Failed to send Prolog <HTTP Status Code #400>

Full log : 
```Starting OCS Inventory Agent on Wednesday, January 05, 2022 12:44:02.
AGENT => Running OCS Inventory Agent Version 2.9.0.0
AGENT => Using OCS Inventory FrameWork Version 2.9.0.0
AGENT => Loading plug-in(s)
AGENT => Using network connection with Communication Server
AGENT => Using Communication Provider <OCS Inventory cURL Communication Provider> Version <2.9.0.0>
AGENT => Sending Prolog
ERROR *** AGENT => Failed to send Prolog <HTTP Status Code #400>
AGENT => Unloading communication provider
AGENT => Unloading plug-in(s)
AGENT => Execution duration: 00:00:01.
```

OS : CentOS 7
Windows agent version : 2.9.0.0

Thank you very much

**Comment by charleneauger** [comment]
Hi @Ouille85 ,

Indeed, the version of the agents must be lower or equal to that of the server otherwise they cannot communicate. :-)

Best regards,
Charlene Auger
