### ISSUE TITLE
Affichage OS Windows 8 x86 64 bits pour  certains Windows 10 21H2 sans raisons

### ISSUE THREAD

**Issue by FraBza** [OCSInventory-NG/WindowsAgent#232]
**OCS Inventory version**
Version : 2.9.1

Description du Soucis:

Faisant un inventaire de tout nos poste et prétend un attention réel aux version de nos OS, nous avons remarqué que certains de nos postes passant en 21H2 était afficher en tant que Windows 8 32Bits dans OCS, apres un inventaire ou redémarrage du poste le soucis à l'air régler.  Ceci n'est pas systématique. Mais dans une salle avec 20 PC exactement du meme model, 1 va avoir ce soucis.

Ce n'est pas un grave soucis mais à voir si il y à des choses à faire. 

![image](https://user-images.githubusercontent.com/89842037/148514480-08a860bf-65bc-4a6f-9616-0a8ca4d5d9da.png)

Merci

**Comment by FraBza** [comment]
Bonjour @charleneauger ,

La version de nos agents est la 2.9.0.0.

**Comment by fgendorf** [comment]
We have two deskptops with this problem.

**Comment by StCyr** [comment]
We have this issue too (with 2 desktops also)

**Comment by StCyr** [comment]
on at least one of the 2 machines, the command `wmic OS get OSArchitecture` returns an error ("OS - Alias not found")

**Comment by charleneauger** [comment]
Hi @FraBza @fgendorf @StCyr,

Seems like these specific devices may be having wmi issues.

Would you be able to check on this machine which OS Name and OS Version is returned ?
Using powershell, you'll be able to see the OS name using `(Get-WmiObject Win32_OperatingSystem).Caption`

Can you set the Agent debug level to 2 in the ocsinventory.ini file ?
Next, send the inventory and a sysinfo.log will be created in OCS Inventory programdata folder.
This file log all WMI calls made by the agent.

Best regards,
Charlene

**Comment by charleneauger** [comment]
Hi,

Since there was no answer, I'll close this issue now.

Regards

**Comment by Neustradamus** [comment]
Dear @OCSInventory-NG team, @gillesdubois, @kapouik, @damienbelliard, @paullepetit, @RudyLaurent, @charleneauger, @Atineon,

I wish you a Happy New Year 2025!

Have you progressed on it?

Linked to:
- https://github.com/OCSInventory-NG/WindowsAgent/issues/196
- https://github.com/OCSInventory-NG/WindowsAgent/issues/278
