### ISSUE TITLE
Suggest: agent sending inventory by polling.

### ISSUE THREAD

**Issue by keyone78** [OCSInventory-NG/WindowsAgent#24]
Isn't possible to trigger an event from OCS web server to initiate agent(s) to sent it inventory.

**Comment by gillesdubois** [comment]
Hi,

Atm, you can't push data / actions to the agent from the server.
There is actually a debate in the ocs team about the push functionnality.

If this feature is accepted it will be implemented in the newer versions of ocsinventory ng :)
Stay tuned to the ocsinventory-ocreports github repo.

Regards,
Gilles Dubois.
