### ISSUE TITLE
cant communicate after update agent to 2.9.1.0

### ISSUE THREAD

**Issue by ajavor** [OCSInventory-NG/WindowsAgent#241]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General information
Operating system :  Win10 Pro

### OCS Inventory information
Windows agent version : 2.9.1.0 64bit
Server: OCS 2.9.2

### Problem's description
After silently upgrading the agent to version 2.9.1.0 (from version 2.9.0.0) using the deployment package, the agents stopped communicating with the server.
There are errors in the windows logs at the station:

`Service encounter error <Can't get OCS Inventory Agent exit code>.`

If I run the OCSInventory.exe agent manually, I get the error:

```
Procedure entry point not found:
?setWmiFlagMode@CConfig@QEAAXPEB_W@Z in library C:\Program Files\OCS Inventory Agent\OCSInventory.exe.
```

Update:

If I install manually from .exe or from OCS Inventory NG Agent Deployment Tool - then it works fine.
If I use the command on deployment package (identical to what worked so far):

`OCS-Windows-Agent-Setup-x64.exe /S /UPGRADE /NOSPLASH /NO_SYSTRAY /NOW /SSL=1 /SERVER=https://xxxxxxx/ocsinventory`
- the problem is as above.

Has the update command from the command line changed since the last agent version?

**Comment by LMS235** [comment]
Same error here... 

We had to manually reinstall the agents that received the update directly via software distribution with PSEXEC, very messy.

**Comment by fgendorf** [comment]
Same problem here, I just tried upgrade by deployment in 3 machines, when I see that doens't work I abort the update.

**Comment by LMS235** [comment]
> Same problem here, I just tried upgrade by deployment in 3 machines, when I see that doens't work I abort the update.
> 
> In my case a always used the follow parameters: OCS-Windows-Agent-Setup-x64.exe /S /UPGRADE /debug=2 /notag /force /SSL=0 /server=https://xxxxxx.xxxx.xx/ocsinventoryauth /user= /pwd= /now /nosplash

/SSL=0 and then /server=https:// ???

**Comment by fgendorf** [comment]
Sure, /SSL=0, according to documentation is for validation server, and using /SSL=1 you must indicate the certca.pem, not necessary in my case.

**Comment by LMS235** [comment]
> Sure, /SSL=0, according to documentation is for validation server, and using /SSL=1 you must indicate the certca.pem, not necessary in my case.

but then you can forget about SSL (https) directly. Since "anyone" can pretend to be the OCS server.

Works, but should be reconsidered for security reasons, just as a tip. ;)

**Comment by fgendorf** [comment]
HI @LMS235, the https are used for no plain text communications, my server use a valid buyed SSL certificate, anyone can have the CA.crt of it. If somebody atack between  client and server pretending be the OCS server, the data from OCS is not so sensitive...
But thanks for you consideration, my problem now is that clients updated from deployment to version 2.9.1.0 don't comunicate at all. :-P

**Comment by LMS235** [comment]
@fgendorf The problem is not the OCS data. It is more about the fact that someone can simply deploy a software package (e.g. with a virus) if deploy is active.

**Comment by charleneauger** [comment]
Hi @ajavor ,

Since the 2.9 server version, we recommend to update the windows agent using the deployment engine. See documentation : [Windows deployment templates](http://wiki.ocsinventory-ng.org/05.Deployment/Windows/Summary/#update-windows-agent )
The /UPGRADE option is not used anymore and is considered as depreciated.

Best regards,
Charlene

**Comment by fgendorf** [comment]
Hi @charleneauger, this mean OCS Server deployment doesn't works to update Windows Ocs Agent anymore?

**Comment by LMS235** [comment]
@charleneauger Here, however, there is a need for adaptation in the docu - https://wiki.ocsinventory-ng.org/07.OCS-Tools/OCS-Windows-Packager/

![image](https://user-images.githubusercontent.com/8693550/156985410-8bb2fa93-06ca-48a6-84f4-3bd1b33c5a21.png)

and then here - http://wiki.ocsinventory-ng.org/05.Deployment/Windows/Summary/#update-windows-agent

![image](https://user-images.githubusercontent.com/8693550/156985492-21f3cc3f-c62d-45df-8af7-a69f37d13245.png)

**Comment by ajavor** [comment]
@charleneauger

Ok, but in OCSPackager I have to use the command line anyway.
![obraz](https://user-images.githubusercontent.com/32665748/159474931-df54e3f0-6ed8-43cb-8f27-b3539301a219.png)

So what will the command line to update the Windows agent like below be like now? 
`OCS-Windows-Agent-Setup-x64.exe /S /NOSPLASH /NO_SYSTRAY /NOW /SSL=1 /SERVER=https://xxxxxxx/ocsinventory`

The documentation is unclear. Can the script code "scheduledupdateagent.ps1" be exposed? 
![obraz](https://user-images.githubusercontent.com/32665748/159475219-7223502c-4a6b-4b95-a2d1-4147ccf5e939.png)

**Comment by charleneauger** [comment]
Hi @fgendorf, no, it just means the /UPGRADE option is no longer used.

Hi @LMS235, indeed our documentation on OcsPackager is not up to date. We will update it as soon as possible to match the agent's update documentation.

Hi @ajavor, in the packager you can use your usual command lines except /UPGRADE as it is deprecated.
The scheduledupdateagent.ps1 script programs a scheduled task that will uninstall the old agent properly and install the new agent by executing the setup packager that you will have generated.
The different scripts are located in your ocsreports/config/teledeploy/script folder if you want to see the different actions they perform.

Regards,
Charlene

**Comment by ajavor** [comment]
Thank you @charleneauger.
Now everything is clear, I close the topic.
