### ISSUE TITLE
User display does not work

### ISSUE THREAD

**Issue by ScriptHash** [OCSInventory-NG/WindowsAgent#242]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General information
Operating system :  Clients : Windows 10 | Server : Debian 10

### OCS Inventory information
Windows agent version :  2.9.0

### Problem's description
I have the problem that the agent does not read the current user, or with some clients it does, but with others the column remains empty. 

What is the reason ?

![image](https://user-images.githubusercontent.com/52527330/156515121-044cfbac-6363-49ab-ba4b-ca8f4d89dfae.png)

**Comment by ajavor** [comment]
The field "User" is blank when the user is not logged in to the station.

**Comment by ScriptHash** [comment]
However, the field also becomes empty when the user is logged in. And then times a question, should the agent start automatically or best automatically with delay ?

**Comment by ajavor** [comment]
If you have ocs agent running as service, then set the connection frequency, eg. every 1h, and the next time the agent is synchronized with the server, the "User" field should be updated automatically.

**Comment by LMS235** [comment]
@ScriptHash We have set all our agents to "Autostart (delay)" and no Problems

**Comment by charleneauger** [comment]
Hi @ScriptHash ,

The connected user is empty or system if the Windows agent sends inventory when no one is logged on the machine.

Regards,
Charlene Auger

**Comment by Scrik** [comment]
> LMS23

как вы это исправили?

**Comment by Scrik** [comment]
> "Autostart (delay)"

How to set "Autostart (delay)" in agent? witout bat and other?
My computers are not in a domain and it is very problematic to connect to them. Is there a ready one .exe with this fix?
server ocs 2.7, agent 2.7.0.1

**Comment by LMS235** [comment]
@Scrik As far as I know, this is only possible via script. However, you can have this done directly during the update. So I don't see any problem with the implementation here.
