### ISSUE TITLE
Software date information bad formated

### ISSUE THREAD

**Issue by GrogyLbn** [OCSInventory-NG/WindowsAgent#244]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General information
Operating system :  Detect on Windows server 2016 Standard

### OCS Inventory information
Windows agent version : 2.8

### Problem's description
For some software the install date is wrong and bad formated, mostly for microsoft corp software
exemple: Microsoft Visual Studio Tools for Applications 2015
Output date 0000//0/0/00

During the uploald ocs server don`t find the format wanted, so every day put the day of last inventory as install date

Perhaps due that information is not available in registry

Regard`s
Gregory

**Comment by charleneauger** [comment]
Hi @GrogyLbn ,

We're sorry for this inconvenience.

Unfortunately on many software Microsoft doesn't fill in a correct date format and the solution was to save the current date instead.

Regards,
Charlene
