### ISSUE TITLE
OCSInventory Agent installation with GData antivirus on W10 (startup script)

### ISSUE THREAD

**Issue by Sam-ghub** [OCSInventory-NG/WindowsAgent#245]
### General information
Operating system :  
Windows 10
### OCS Inventory information
Windows agent version : 2.9.1.0
### Instalation methon:
Deploy by startup script with OCSpacker.
### Problem's description
On Windows 10 installations with GData antivirus installed, the service can't finish installing. Stuck after trying to execute Saas.ps1. The process is kept by GDScan.exe and can't finnish installation.
Uninstaller is missing from ProgramFiles folder. 
### Inventory log file ( optional )
Inventory on log it's completed, but last line on the log:
> EXECUTABLE PLUGIN => Found executable plugin <Saas.ps1>
### Screenshots
![Screenshot 2022-03-26 at 00 43 39](https://user-images.githubusercontent.com/73297888/160237939-e766be46-9dfe-4cdd-86ee-15d23eb63c26.png)
![Screenshot 2022-03-26 at 00 48 58](https://user-images.githubusercontent.com/73297888/160237936-af50598a-2d3c-4730-81e4-19e6c5787ccf.png)
![Screenshot 2022-03-26 at 01 32 49](https://user-images.githubusercontent.com/73297888/160237966-b184c088-425e-45e0-b7a7-eb8c43b1c021.png)
![Screenshot 2022-03-26 at 12 55 04](https://user-images.githubusercontent.com/73297888/160238210-5c8cd818-0884-4a63-a36b-3417d48733dc.png)

### Temporary manual Solution
If I kill cmd.exe  or the powershell script, the installation finnish succesful. Windows 7 installations with antivirus install without issues. Executing manualy the .exe as admin after boot works too.
The antivirus isn't logging about blocking OCS installer.

**Comment by Sam-ghub** [comment]
Doing this fixes the problem:
https://user-images.githubusercontent.com/73297888/160238498-d6d0801d-a57b-4e86-9c72-339b186ef49c.mov

**Comment by neverstopdreaming** [comment]
same issue here but only on some PCs.
killing the powershell fix let the process start but on the next reboot it get stuck again.
It's not related to the latest release of the agent only. I saw this at lease since 2.8

**Comment by Sam-ghub** [comment]
> 

I kept adding the files to whitelist on the antivirus, but nothing helps. I just bruteforce it. Created a GPO to launch a script to uninstall reboot, install ocs, reboot, reinstall anvirius.  Fixes the issue.

The problem is when it tries to launch the SaaS.ps1.

**Comment by neverstopdreaming** [comment]
On my installations I found that the "AMSI antimalaware protection" is the one that is blocking the script.
Disabling that on the guardian seems to solve the issue.

**Comment by Sam-ghub** [comment]
> On my installations I found that the "AMSI antimalaware protection" is the one that is blocking the script. Disabling that on the guardian seems to solve the issue.

You have to completely disable AMSI on the guardian I couldn't find an option to whitelist a shared folder or local folder. 
I'll try to disable it on guardian, then reboot all the machines, and test if it works.
Did you try to contact G-data?

**Comment by neverstopdreaming** [comment]
> Did you try to contact G-data?
Nope, I should have done but I didn't. Did it fix the issue to you as well?

**Comment by thenextuser** [comment]
Hello all,

I have the same configuration 'GDDATA Endpoint Protection' and 'OCS Inventory'.
Service, inventory and installation work only with AMSI function turned off.

I contacted GDATA support and evaluated the problem via log data.
With some DLL files adapted by GDATA 'OCS Inventory' works again as usual with switched on AMSI function.

According to support, the changes to the program code will be included in one of the next updates.
However, a release date could not be given yet.
Please keep an eye on the change logs (https://www.gdata.help/display/BS/Changelog).
The current program version 15.3.0.777 still contains the bug.

I think the issue here can be closed.
Many greetings.
