### ISSUE TITLE
upgrade agents with the packager

### ISSUE THREAD

**Issue by bluedark** [OCSInventory-NG/WindowsAgent#246]
Hello,
I just updated my server to version 2.9.2.
For all my clients, I had deployed the 2.8 agents by gpo thanks to the packager with which I had generated a package.
I would like to update them to 2.9.1 still in gpo and regenerating the agent with the packager.
But on the wiki, it's noted "don't use OCSPackager to upgrade OCS Inventory Windows Agent.
Create deployment package with "OCS-NG-Windows-Agent-Setup.exe" on zip file and launch with command example: OCS- NG-Windows-Agent-Setup.exe /S /UPGRADE /SERVER=ocs_server_address".
I don't understand this note... I can't use the packager to update the agents?
Thanks !

**Comment by charleneauger** [comment]
Hi @bluedark ,

Indeed, our documentation concerning the update of the agent is not up to date.
You can use OcsPackager to update your agents but the /UPDATE parameter is no longer used.

Regards,
Charlene

**Comment by bluedark** [comment]
so, to be sure: can i use ocspackager to generate a package with the latest version of the ocs agent ?
No need to use /UPDATE or /UPGRADE in ocspackager ?
thanks !

**Comment by charleneauger** [comment]
Hi @bluedark 

Yes, you can use ocspackager without /UPDATE or /UPGRADE :-) 

Regards,
Charlene
