### ISSUE TITLE
Package download - repetition forever on client

### ISSUE THREAD

**Issue by sokatra** [OCSInventory-NG/WindowsAgent#247]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General information
Operating system :  Win 10

### OCS Inventory information
Windows agent version : 2.05

### Problem's description
Hy, i have a client computer which has status notified , but the client was not able to download the file because the package detected as a virus (it is just an eicar test virus). So i decided to remove the client from package notified on server side. But the client tries to download the package again and again.

Is there a retry count for "bad" packages .. or does the client with ocs agent 2.05 does this until the end of the days?

I do not want to remove something on the client download folder and i do not have access to every client directly.

I expect that after for example 10 retries the client gives up an does not retries to download a package.
perhaps the client should check again if the server wants the client to download a package. 
If i remove the package for this specific pc on server side the client should notice that i think.
The only solution is perhaps to unactivate the complete package on server side until all clients recognize that.

Kind regards

Sokatra
### Inventory log file ( optional )
*Use github cloud or trusted upload website*

**Comment by gillesdubois** [comment]
Hi,

There is a parameter named DOWNLOAD_TIMEOUT (in days) that will put a package in timeout if the delay of processing is exceeded.

Tbh I dont know if the 2.0.X take into account the download timeout variable.

Regards,
Gilles.
