### ISSUE TITLE
Compiling Agent gives Error

### ISSUE THREAD

**Issue by QTFsniper** [OCSInventory-NG/WindowsAgent#25]
![capture](https://cloud.githubusercontent.com/assets/25048308/21835608/5ad29460-d78c-11e6-8394-ceffc52c4f26.JPG)
Hi All,

Trying to build the Agent Project - Gives the following Errors in CapSnmp.cpp

Severity	Code	Description	Project	File	Line	Suppression State
Error (active)		identifier "CSnmpRequest" is undefined	Agent	\Agent\CapSnmp.cpp

Severity	Code	Description	Project	File	Line	Suppression State
Error (active)		identifier "pSnmp" is undefined	Agent	Agent\CapSnmp.cpp	51

**Comment by gillesdubois** [comment]
Hi @QTFsniper ,

Sorry for the delay.
Which configuration did u used to compile your agent ?

Regards,
Gilles Dubois.

**Comment by charleneauger** [comment]
Hi !
Your problem has been solved.
Please check the following commit : #579a58830c3f49df412b28945ec00d333e1e8c85

Regards,
Charlene Auger.
