### ISSUE TITLE
duplicates after renaming

### ISSUE THREAD

**Issue by bluedark** [OCSInventory-NG/WindowsAgent#250]
hello, 
when i rename computers, why it gets duplicated in ocs ?
Why the computer does not automatically rename itself in ocs?
I updated server and agents to 2.9.2. But still the same...
Thanks !

**Comment by charleneauger** [comment]
Hi @bluedark ,

OCS use the computer name for the uniq machine id. 
You can manage the level of duplicate in your ocsreports configuration to merge automatically the machine with the same serial number and macaddress for example.

Regards,
Charlene
