### ISSUE TITLE
The command line options /work_dir="path to directory" is not fully taken into account.

### ISSUE THREAD

**Issue by christroc77** [OCSInventory-NG/WindowsAgent#251]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General information
Operating system :  Windows 10 enterprise

### OCS Inventory information
Windows agent version :  2.9

### Problem's description
When using the work_dir option, the %PROGRAMDATA%\OCS Inventory NG\Agent\ocsinventory.log file is always used instead of creating a new one in the directory specified by work_dir.

The computer has an agent installed, configured by default to use "%PROGRAMDATA%\OCS Inventory NG\Agent" as the working directory and the Windows service is activated.
When I run a portable version of the agent, the logs are written to %PROGRAMDATA%\OCS Inventory NG\Agent\ocsinventory.log instead of the portable agent directory. 
The problem also occurs on a "normal" version of the agent.
I have encountered this problem before with agent version 2.3.1.3.

**Comment by christroc77** [comment]
No reaction yet. Would this be a desired and therefore normal operation?

**Comment by gillesdubois** [comment]
Hi @christroc77 

Thanks for you report.
We'll provide you a more detailled answer in the following days :)

Regards,
Gilles.

**Comment by christroc77** [comment]
OK, thanks.
cordially

**Comment by christroc77** [comment]
So ? is it finally normal and wanted?

**Comment by christroc77** [comment]
After some research in the source code : OCSInventory Front.cpp =>	`m_csDataFolder += OCSNG_COMMON_APPDATA;`
```

		* Get application data storage path path	
		*
		****/		
		if (!SHGetSpecialFolderPath( NULL, m_csDataFolder.GetBuffer( _MAX_PATH+1), CSIDL_COMMON_APPDATA, TRUE))
		{
#ifdef _DEBUG
			AfxMessageBox( _T( "Unable to initialize OCS Inventory data storage path!"), MB_ICONSTOP);
#else
			_tprintf( _T( "Unable to initialize OCS Inventory data storage path!")); 
#endif
			return FALSE;
		}
		m_csDataFolder.ReleaseBuffer();
		m_csDataFolder += OCSNG_COMMON_APPDATA;
```

So it seems normal.
I unfortunately don't have a Windows environment that allows me to make changes and compile an agent. Neither ZipArchive for 64 bits...

**Comment by christroc77** [comment]
Still no feedback...
Is it so illogical that the log file should be generated in work_dir if used?

**Comment by charleneauger** [comment]
Hi @christroc77 ,

We're sorry for the delay.

We added the issue to our roadmap.
We'll let you know when it's fixed.

Regards,
Charlene
