### ISSUE TITLE
CDMI::DmiString() issue on zero-string

### ISSUE THREAD

**Issue by drTr0jan** [OCSInventory-NG/WindowsAgent#26]
The _CDMI::DmiString()_ function works incorrectly if the second arg is 0.
Ex.:
`csAssetTag = DmiString(dmi, pPointer[0x08]);`
It can be writing incorrect info (a garbage) to csAssetTag if _pPointer[0x08]_==0 (_Asset Tag Number_ byte is zero).

WindowsAgent v.2.3 RELEASE

**Comment by drTr0jan** [comment]
It's need to paste some code to SysInfo/DMI.cpp:51:
```
	if (id == 0)
		return _T( "");
```
after `p += dmi->Length;` at line 50.

**Comment by drTr0jan** [comment]
What about the fix commit?

**Comment by charleneauger** [comment]
Hi @drTr0jan ,

Sorry for the delay, I tested and merged your PR. Thank you for your contribution !

Best regards,
Charlene Auger
