### ISSUE TITLE
Few installed app are not detected by OCS Agent 

### ISSUE THREAD

**Issue by thenamelessthing** [OCSInventory-NG/WindowsAgent#261]
### General information
Operating system :  Windows 10/11

### OCS Inventory information
Windows agent version : 2.9.0.0

### Problem's description
Few installed app are not detected by OCS Agent 

Ex: Git

![image](https://user-images.githubusercontent.com/10235448/200595628-8a5ddec0-4ae6-4118-81d9-e1d030adc310.png)

### Inventory log file ( optional )
*Use github cloud or trusted upload website*

**Comment by charleneauger** [comment]
Hi @thenamelessthing ,

I have Git installed on my machine and it is present in my software.

![Screenshot_20221222_111516](https://user-images.githubusercontent.com/28924550/209113034-ba44dce0-98db-4a50-873c-48c4c1c1fc46.png)

![Screenshot_20221222_111328](https://user-images.githubusercontent.com/28924550/209113075-d01d681c-a7d9-4b61-b267-6559691e6aa9.png)

I don't have a specific explanation for that.

Maybe you can try with the [Userinstalledapps](https://github.com/PluginsOCSInventory-NG/userinstalledapps/releases/tag/2.0) plugin ?
As you can see below, the software is also inventoried by this plugin.

![Screenshot_20221222_111213](https://user-images.githubusercontent.com/28924550/209113125-6884ba6a-446b-489f-81a0-c8eb915c0250.png)

Best regards,
Charlene

**Comment by gillesdubois** [comment]
Hi,

Since there is no answer to this issue, I'll now close it.

Feel free to reopen an issue if the problem persist.

Regards,
Gilles.
