### ISSUE TITLE
Agent Windows 2.10.0.0 - 32 bits version not released

### ISSUE THREAD

**Issue by mtbadi39** [OCSInventory-NG/WindowsAgent#266]
[Agent Windows 2.10.0.0](https://github.com/OCSInventory-NG/WindowsAgent/releases/tag/2.10.0.0)

**Comment by mtbadi39** [comment]
Ping

**Comment by gillesdubois** [comment]
Hi,

We are planning to release the 32 bits version soon.

Regards,
Gilles.

**Comment by charleneauger** [comment]
Hi @mtbadi39 ,

The windows agent has been released in 2.10.1.0 with both versions x64 and x86.

Best regards,
Charlene
