### ISSUE TITLE
Impossible de démarrer le programme car il manque api-ms-win-crt-heap-l1-1-0.dll

### ISSUE THREAD

**Issue by mtbadi39** [OCSInventory-NG/WindowsAgent#267]
Bonjour;
Windows 8.1 Professionnell 64 bits
OCS-Windows-Agent-2.10.0.0_x64

L'installation de l'agent n'affiche aucune erreur, main si on déplace vers : C:\Program Files\OCS Inventory Agent et doubleclik sur **ocsnotifyuser.exe** ou **download.exe** ou **ocsinventory.exe** l'erreur suivant s'affiche :
`Impossible de démarrer le programme car il manque api-ms-win-crt-heap-l1-1-0.dll sur votre ordinateur. Essayez de réinstaller le programme pour corriger ce problème.`

Noter que presque tous les version du **Visual C++ Redistributable** sont installés sur le système (capture d’écran ci-joint)

![ocs_agent_windows](https://user-images.githubusercontent.com/8750684/208289973-ea9aeb91-464d-47d1-9ae7-4c5937b559e2.png)

![ocs_agent_windows_2](https://user-images.githubusercontent.com/8750684/208289992-28db4a16-5e23-4af8-aed9-98a484f04a22.png)

**Comment by TonSilvas** [comment]
installez la mise à jour pour le "Runtime C universel" dans Windows qui résout le problème.
KB2999226
https://support.microsoft.com/fr-fr/topic/mise-%C3%A0-jour-pour-le-runtime-c-universel-dans-windows-c0514201-7fe6-95a3-b0a5-287930f3560c

**Comment by mtbadi39** [comment]
Bonjour @TonSilvas 
la mise à jour KB2999226 est déjà installé (capture d’écran ci-joint) mais le problème persiste toujours.

![KB2999226](https://user-images.githubusercontent.com/8750684/209090689-68be8961-a6ab-470e-939d-6e2e34cc9f6f.png)

**Comment by TonSilvas** [comment]
ma suggestion:
test 1 : supprimez et installez ou réinstallez kb2997 et réinstallez OCS.
Test 2 : Réinstallez Visual C++ 2015 x86/x64 et réinstallez OCS.

si tout échoue : utilisez OCS version 2.8 ou 2.7

Désolé pour mon français, j'utilise un traducteur.

Wellington

**Comment by mtbadi39** [comment]
Hi @TonSilvas 
Also, the OCS Inventory Service was not created, any idea !

**Comment by TonSilvas** [comment]
Yes, it does not create the service either.
In my case the solutions were:
option 1:
install/reinstall Visual C++ 2015
Install/Reinstall KB2999226

Option 2:
Use older versions of OCS 2.7/2.8

**Comment by mtbadi39** [comment]
Hi, 
finally (AL HAMDO LILLAH) it's solved !!
1- remove ocs agent
2- remove all Visual C++ 2015 (x86 and x64)
3- Start with KB2919442, the [March 2014 servicing stack update for Windows 8.1 and Windows Server 2012 R2](https://support.microsoft.com/en-nz/help/2919442/march-2014-servicing-stack-update-for-windows-8-1-and-windows-server-2).
4- Then you need to install KB2919355, the [April 2014 update,](https://support.microsoft.com/en-nz/help/2919355/windows-rt-8-1-windows-8-1-windows-server-2012-r2-update-april-2014) which is a package made up of six separate updates plus an update tool. **These must be installed in the following order** :

- [ ] clearcompressionflag.exe
- [ ] KB2919355
- [ ] KB2932046
- [ ] KB2959977
- [ ] KB2937592
- [ ] KB2938439
- [ ] KB2934018

5- Then you need to install KB2999226, the [Update for Universal C Runtime in Windows](https://www.microsoft.com/en-us/download/details.aspx?id=49071)
6- re-install Visual C++ 2015 Redistributable
7- re-install the latest version of the OCS Inventory NG Agent for Windows

**_hope it helps someone_**
