### ISSUE TITLE
WMI disk S/N hex encoded translation failed

### ISSUE THREAD

**Issue by drTr0jan** [OCSInventory-NG/WindowsAgent#27]
The WMI disk S/N hex encoded translation has broken after upgrade from 2.1.1.1 to 2.3.0.0.
Bug is similar to the [fix #08242c6](https://github.com/OCSInventory-NG/WindowsAgent/commit/08242c64979b65ea93817aa813c75e83dafabe47) (If disk S/N is hex encoded, try todecode it, then ensure S/N is printable before storing it).

Ex., I've the drive with WMI S/N is _434f2d5a393830383753514b3233483057583538_, and I've same SN in WindowsAgent 2.3.0.0 (_&lt;SERIALNUMBER&gt;434f2d5a393830383753514b3233483057583538&lt;/SERIALNUMBER&gt;_), but had correct SN in WindowsAgent 2.1.1.1 (_&lt;SERIALNUMBER&gt;OCZ-8980S7KQ320HXW85&lt;/SERIALNUMBER&gt;_) .

The bug is similar to [#1353559](https://bugs.launchpad.net/ocsinventory-windows-agent/+bug/1353559).

**Comment by charleneauger** [comment]
Hi @drTr0jan ,
What is your Windows version ? 

Regards,
Charlene Auger

**Comment by drTr0jan** [comment]
@charleneauger. Windows 7, Windows Server 2008 and Windows 2008 R2.

There aren't the problem on Windows 8.1 and Windows Server 2012.

**Comment by charleneauger** [comment]
Hi @drTr0jan ,
This bug is fix.

Regards,
Charlene Auger
