### ISSUE TITLE
Systray icon showed when using /no_systray

### ISSUE THREAD

**Issue by matteo-cavalli** [OCSInventory-NG/WindowsAgent#270]
### General information
Operating system :  Windows 11, Windows 10

### OCS Inventory information
Windows agent version : 2.10.1.0

### Problem's description
Hi, i had successfully deployed ocs server inside my company, and i'm testing scripting with powershell (psexec) to deploy massively agent on client. With some test client, windows 11 and windows 10, i've noticed that systray icon is showed, also whwn /no_systray option is used.
My push string is: 

psexec \\COMPUTERNAME -s \\server\sharedfolder\OCS-Windows-Agent-Setup-x64.exe /S /NOSPLASH /SERVER=http://OCSSERVER:8080/ocsinventory /tag="MYTAG" /notag /no_systray

I push this from DC with an administrative account.

are there some errors? ocs server has been installed 7 days ago, so all installation is totally new and clean.

**Comment by charleneauger** [comment]
Hi @matteo-cavalli ,

Any news ?

Regards,
Charlene

**Comment by cavalli-matteo** [comment]
hi i've change company and project during this time, so OCS is not on my path again.
thanks

**Comment by charleneauger** [comment]
Okay no problem. I close this issue.

Regards,
Charlene
