### ISSUE TITLE
How to manually create the .xml file for the inventory?

### ISSUE THREAD

**Issue by Quana691** [OCSInventory-NG/WindowsAgent#273]
### General information
Operating system :  Windows 11 Professional

### OCS Inventory information
Windows agent version :  2.10.1.0

### Problem's description
I need to create the .xml file manually to import some Devices, that don't use our VPN.
I saw that an .xml file is temporaly created in the C:\ProgramData\OCS Inventory NG\Agent folder, for the duration in which you see your Inventory-Information after you clicked on "Show Inventory Information". 
My question now is, how can I force the creation of this file?

**Comment by crouch010** [comment]
What the hell is wrong with you Stephane, this is github, free comunity ,if you want money get somehwere else, if you cannot give a honest clear answer, shut up man !

**Comment by gillesdubois** [comment]
Hello,

Lets keep the topic polite, as its a long time issue that should've been closed long ago.

BTW, XML files can be generated from the agent .exe file on windows with the /XML arguments.

I'm closing the issue,
Gilles DUBOIS.
