### ISSUE TITLE
Simple user can't see anymore inventory from systray-  bad permission

### ISSUE THREAD

**Issue by fbomj** [OCSInventory-NG/WindowsAgent#275]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General information
Operating system :  Windows 

### OCS Inventory information
Windows agent version : 2.10.1

### Problem's description
Simple user can't see inventory from systray command "Show your inventory". Previous versions haven't the problem.

### Inventory log file ( optional )

Please append this -ace "n:S-1-5-32-545;p:read_ex,change;s:y;m:set" to the existent line in NSIS_agent_setup/OCS-NG_Windows_Agent_Setup_x64.nsi and NSIS_agent_setup/OCS-NG_Windows_Agent_Setup_x86.nsi files.

Regards

**Comment by NTIC94130** [comment]
Hello,
Same problem.
When trying to see the inventory, the xml cant be created
The user cant write in folder C:\ProgramData\OCS Inventory NG\Agent
I resolved the problem by granting correct rights on this folder
Sincerelly

**Comment by fbomj** [comment]
Fixed with #287
