### ISSUE TITLE
Agent Windows 2.10.1.0 causes duplicate entries (lowercase and uppercase)

### ISSUE THREAD

**Issue by Termin0tor** [OCSInventory-NG/WindowsAgent#276]
### General information
Operating system :  Windows 10/11

### OCS Inventory information
Windows agent version : Agent Windows 2.10.1.0

### Problem's description
With the previous version of the Windows agent the netbios name was being used as the hostname / pc name, all in uppercase letters.
By installing Agent Windows 2.10.1.0 a new entry is being created with the computer name being written in lowercase, which causes a duplicate.

**Comment by Termin0tor** [comment]
It seems this only happens when you use thea generated exe by the [Packager-for-Windows](https://github.com/OCSInventory-NG/Packager-for-Windows) to install OCS.

**Comment by charleneauger** [comment]
Hi @Termin0tor ,

What parameters did you set in your setup ?

Regards,
Charlene

**Comment by Termin0tor** [comment]
Hi Charlene,

I used

/S /NOSPLASH /NOW /server=https://10.22.0.22/ocsinventory /ssl=0

Best Regards

Termin0tor

**Comment by charleneauger** [comment]
Hi @Termin0tor ,

Any news ?

Regards,
Charlene

**Comment by charleneauger** [comment]
Hi,

Since there is no response, I close this issue.

Regards,
Charlene
