### ISSUE TITLE
ERROR *** AGENT => Failed to send Prolog <HTTP Status Code #500>

### ISSUE THREAD

**Issue by PedroEwen** [OCSInventory-NG/WindowsAgent#282]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General information
Operating system :  Windows 10

### OCS Inventory information
Windows agent version : Windows-Agent-2.3.1.1

### Problem's description
*After installing the agent and the server, I can't perform the inventory, I've changed the agent version several times and it happens every time, can anyone help me?*

### Inventory log file ( optional )

Starting OCS Inventory NG Agent on Tuesday, December 26, 2023 14:58:16.
AGENT => Running OCS Inventory NG Agent Version 2.3.1.1
AGENT => Using OCS Inventory NG FrameWork Version 2.3.1.1
AGENT => Loading plug-in(s)
	DLL PLUGIN => Searching for Plug-in DLL(s) in folder <C:\Program Files (x86)\OCS Inventory Agent\plugins>
	DLL PLUGIN => 0 DLL Plug-in(s) successfully loaded on 0 DLL(s) found
AGENT => Using network connection with Communication Server
	COM PROVIDER => Loading Communication Provider <C:\Program Files (x86)\OCS Inventory Agent\ComHTTP.dll>
AGENT => Using Communication Provider <OCS Inventory NG cURL Communication Provider> Version <2.3.1.1>
AGENT => Sending Prolog
	DID_CHECK => Read DeviceID <my_device> and MACs <my_mac> in file <ocsinventory.dat>
	COM SERVER => Initializing cURL library for sendRequest
	COM SERVER => Using cURL without server authentication
	COM SERVER => Disabling cURL proxy support
	COM SERVER => Disabling cURL SSL server validation support
	COM SERVER => Sending HTTP Post request to URL <http://my_ip/ocsinventory>
	COM SERVER => HTTP Post response received <HTTP Status Code #500>
	COM SERVER => Cleaning cURL library
ERROR *** AGENT => Failed to send Prolog <HTTP Status Code #500>
AGENT => Unloading communication provider
AGENT => Unloading plug-in(s)
AGENT => Execution duration: 00:00:00.

**Comment by gillesdubois** [comment]
Hi,

Error 500 mean you have a server side error.
Check the apache log.

If that's not enough, you can enable 'DBI_PRINT_ERROR" in the z-ocsinventory-server.conf file.

Regards,
Gilles DUBOIS.

**Comment by PedroEwen** [comment]
Hi, Gilles.
 
My apache log is

[Wed Dec 27 10:21:19.319258 2023] [perl:error] [pid 400296] [client my_ip:50615] Can't call method "rollback" on an undefined value at /usr/local/share/perl/5.34.0/Apache/Ocsinventory/Server/System.pm line 

Can you help me?

**Comment by PedroEwen** [comment]
I managed to solve it!

https://ask.ocsinventory-ng.org/11582/ocs-server-2-6-no-communication-with-clients

**Comment by PedroEwen** [comment]
Thanks, Gilles.

**Comment by gillesdubois** [comment]
The link you sent is basically what I would have told you to check next :)
Glad you managed to fix your issue.

Regards,
Gilles DUBOIS.
