### ISSUE TITLE
WindowsAgent not compatible with Windows Server 2003 R2

### ISSUE THREAD

**Issue by StCyr** [OCSInventory-NG/WindowsAgent#29]
Hello,

sur le site http://www.ocsinventory-ng.org/fr/ il est marqué que l'agent Windows est compatible avec `Windows Server 2003 R2`, mais il ne fonctionne pas sur les 2 serveurs `Microsoft Windows Server 2003 R2 Standard Edition`. 

J'obtiens `OCSInventory.exe is not a valid Win32 application`

**Comment by gillesdubois** [comment]
Bonjour,

L'agent n'est plus compatible windows XP / 2003 depuis la version 2.1.1.3
Il faut utiliser la 2.1.1.1 pour avoir une compat XP / 2003 

Cordialement,
Gilles Dubois.
