### ISSUE TITLE
Wrong UUID is shown at Agent

### ISSUE THREAD

**Issue by networker01** [OCSInventory-NG/WindowsAgent#3]
Hello!

On an Inventoried Computer (Windows Server 2008 R2 Enterprise SP1), i have installed OCS-Agent 2.1.0.3. When i check the Hardware-UUID (at cmd: wmic PATH Win32_ComputerSystemProduct get uuid), i get this output:

UUID
0D977C6C-FA6C-27E6-6CFA-E6277070170E

Buth when i tell OCS-Agent to show me the Inventory-Information (OCSInventory.xml), the UUID is:

6C7C970D-6CFA-E627-6CFA-E6277070170E

You see, the first 3 parts of the UUID are shuffled around.

At the OCS-Server 2.1.1, the transmitted UUID is also:

6C7C970D-6CFA-E627-6CFA-E6277070170E

Can you fix this problem? Do you need further information?

Feature Request:

Maybe it could be a good solution, when you take the Windows-UUID to identify the Computer on Windows Systems. You can find it here:

HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Cryptography

MachineGuid

**Comment by dliroulet** [comment]
Hi.

Do you have VMware, Xen or VirtualBox VM ? Could you check if OCS UUID is the same the one used in those tools ?

WMI UUID as the first bytes in wrong order to link UUID with Hypervisor UUID. That's why we use Hypervisor UUID order, and not WMI order.

Cheers
