### ISSUE TITLE
Strange certificates validation behaviour on Windows (7)

### ISSUE THREAD

**Issue by StCyr** [OCSInventory-NG/WindowsAgent#31]
### General informations
Operating system :  Windows 7 64bits

### OCS Inventory informations
Windows agent version : 2.3.0.0

### Problem's description
Using a cacert.pem on Linux Ubuntu 16.04.2, OCSI agent 2:2.0.5-1, curl 7.47.0 to connect to my ocsinventory server works like a charm

Using the **exact same cacert.pem file** on Windows 7 64 bits, the agent can't connect, and I get the following error:

```
WARNING *** COM SERVER => Failed to send HTTP Post request <Peer certificate cannot be authenticated with given CA certificates>
```

### Additional info
I'm renewing my ocsinventory server's certificate. 

Unfortunately, our certificate issuer changed (from Comodo to DigiCert). So, the ocsinventory now has to validate the ocsinventory server's certificate against a new CA.

To make the server certificate transition as smooth as possible my plan is to:

1. Add the new CA certificate to the cacert.pem on all OCSI agents
2. Once all OCSI agents are updated, change the server's certificate to the new (DigiCert) one
3. Optionaly, remoev the old CA certificates from all OCSI agents

This plan seems to be perfectly possible on Linux: Adding the new CA certificate to the cacert.pem file on linux allow authenticating both the old and the new server's certificates.

Unfortunately, on my Windows test machine, adding the new CA certificate to the cacert.pem file doesn't allow authenticating both the old and the new server's certificates; Only the original server certificate is validated successfuly. It's like ocsi/libcurl isn't able to skip over the first CA certificates and use the last CA certificate to validate the new server's certificate.

The original cacert.pem file contains 3 certificates, while the new one contains 4 certificates.

### Question
Is it the OCSI Windows agent that's not using libcurl properly or some inherent limitation of libcurl on Windows?

**Comment by StCyr** [comment]
OK, you may close this issue.

The problem is twofold: 

1. I had not added the (self-signed) certificate of the root certification authority (in my case `C=US, O=DigiCert Inc, OU=www.digicert.com, CN=DigiCert Assured ID Root CA`)
2. (Guessed) Differences of implementation of libcurl on Windows/OpenSSL and Linux/GNUTLS

Because of the 2nd issue, issuing such a command on Windows fails (as it should do) if you don't provide the (self-signed) certificate of the root certification authority in the cacert.pem file:

```
curl -v --capath c:\temp --cacert "C:\ProgramData\OCS Inventory NG\Agent\cacert.pem" https://ocs-server.mycompany.be
```

while the corresponding command on linux works (though, it shouldn't in my opinion):

```
curl -v --capath /dev/null --cacert /var/lib/ocsinventory-agent/https\:__ocs-server.mycompany.be_ocsinventory/cacert.pem https://ocs-server.mycompany.be
```

Because, purportedly,  in the later case, libcurl still uses the default /etc/ssl/certs folder and finds there the root CA certificate.

I'll rather open a bug against `curl`

**Comment by gillesdubois** [comment]
Hi,

Our agents are using the libraires without any modifications ... 
Maybe we need to upgrade our curl version to solve this problem ? ( atm the windows agent is using the 7.47 version )

Regards,
Gilles Dubois.

**Comment by StCyr** [comment]
Hi Gilles,

I'm currently doing some tests with curl on windows and Linux: there seems to be some undocumented implementation differences.

Cyrille

**Comment by charleneauger** [comment]
Hi @StCyr ,
curl librarie has been updated on last Windows Agent versions.

Regards,
Charlene Auger
