### ISSUE TITLE
Teledeployment :Use the advanced options of teledeploy

### ISSUE THREAD

**Issue by keyoneplus** [OCSInventory-NG/WindowsAgent#32]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system :   Window 7 64bit

### OCS Inventory informations
Windows agent version :  2.1.1.3

### Problem's description
*Describe your problem here*
TeleDeployment, using advance teledeploy to deploy a file  for next day . However  after I affect the computer (with advance teledeploy) then proceed to run the agent. The download did not follow scheduled date and proceed to download and deploy the file immediate after agent's inventory ended.  
### Inventory log file ( optional )
    <NAME>DOWNLOAD</NAME>
    <PARAM FRAG_LATENCY="3" PERIOD_LATENCY="1" ON="1" TYPE="CONF" CYCLE_LATENCY="5" TIMEOUT="30" PERIOD_LENGTH="10" EXECUTION_TIMEOUT="120" />
    <PARAM ID="1487231985" SCHEDULE="//2017-02-18 01:00" 

*Use github cloud or trusted upload website*

**Comment by gillesdubois** [comment]
Hi,

What do you mean by deployed ? the package run his install before the scheduled date ? or it just downloaded it before the scheduled date ?

From what i see in your inventory file there is a problem in your SCHEDULE xml node.
I will investigate the issue and comeback to you soon :)

Thanks for your contribution.

Regards,
Gilles Dubois.

**Comment by keyone78** [comment]
Mean when agent completed its inventoried, it will proceed to download the package. (its download before the scheduled date) .  
Maybe the date syntax wrong at server side.

**Comment by gillesdubois** [comment]
Hi @keyone78 ,

When you use the scheduled deployment the package is downloaded BEFORE the installation date.
However the package's installation process only on the scheduled date.

Regards,
Gilles Dubois.

**Comment by keyoneplus** [comment]
Using "launch"  scheduled for two days later . It download the package and launch directly. it did not wait for 2 days later

**Comment by gillesdubois** [comment]
Ji, @keyoneplus ,

Which ocs server verison are you using ?

**Comment by keyoneplus** [comment]
OCS server 2.2.1

**Comment by gillesdubois** [comment]
Hi @keyoneplus ,

I think you should upgrade your server to the 2.3 version.
If you are not in an hurry you should wait 1 week ( approximatly ) a new version will be realeased with a lot of fixes.

Your problem come from the server who send incorrect date format.

From your inventory log : 
`SCHEDULE="//2017-02-18 01:00" `
Should be : 
`SCHEDULE="2017/02/18 01:00" `

Regards,
Gilles Dubois.
