### ISSUE TITLE
Better Information for Debugging

### ISSUE THREAD

**Issue by vollkommenIrrelevant** [OCSInventory-NG/WindowsAgent#33]
Problem: Downloading Agent over https

It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.
General informations

Operating system : Ubuntu 16.04
OCS Inventory informations

Windows agent version : 2.3.0
Problem's description

I installed the Server (including certificate) and with http everything is working fine.
If i'm trying with https, the ocslogon throws
`
Downloading file <https://a.b.c.d/ocsinventory/deploy/ocspackage.exe> without server authentication...SendRequest Error: Failed downloading file !`

With Firefox seems it ok, I can download the ocspackage.exe, install it and everything is fine...
The Message is not very detailed and should inform about the Reason for not downloading to find a solution.

OcsLogon.log
`******************************************************** Starting OCS Inventory NG Logon Installer 2.2.0.0 on 28/02/2017 at 14:09:06 Checking if not already running...OK Parsing command line arguments...OK Searching OCS Inventory NG Agent installed version...OK (0.0.0.0) OCS Inventory NG Agent does not seems to be installed, setup version required.. Download timeout is set to <60000> millisecond. Download does not use HTTP proxy server. Downloading file <https://a.b.c.d/ocsinventory/deploy/ocspackage.exe> without server authentication...SendRequest Error: Failed downloading file !`

**Comment by gillesdubois** [comment]
Hi @vollkommenIrrelevant ,

Indeed, the log file is not giving a lot of informations.
From what you said, it look like you have a certificate problem. For information, OCS Inventory doesn't support wildcard certificate.

Regards,
Gilles Dubois.

**Comment by vollkommenIrrelevant** [comment]
Thanks for response. That's possible, but without more Information it's complicated to find any error. I decided to wait untill situation is more reliable and better to configure.

**Comment by charleneauger** [comment]
Hi @vollkommenIrrelevant ,
The OCSLogon file is no longer used by the new versions of the OCS agent, so we removed it.

Regards,
Charlene Auger
