### ISSUE TITLE
Storage information not correct

### ISSUE THREAD

**Issue by keyoneplus** [OCSInventory-NG/WindowsAgent#34]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system :   Window 7

### OCS Inventory informations
Windows agent version :  2.1.1.3

### Problem's description 
*Describe your problem here*
About the Storage information  Name and Model is being swap.
Check the query on Win32_DiskDrive is show the different.
### Inventory log file ( optional )
*Use github cloud or trusted upload website*
![image](https://cloud.githubusercontent.com/assets/5064672/23840720/945d417c-07e2-11e7-9f48-d63e0672e83d.png)
![image](https://cloud.githubusercontent.com/assets/5064672/23840726/9ca08baa-07e2-11e7-91ba-54beea8bb03b.png)

**Comment by gillesdubois** [comment]
hi @keyoneplus ,

Did you try to update to the 2.3.0.0 version ? 

Regards,
Gilles Dubois.

**Comment by keyoneplus** [comment]
Will look into it.

**Comment by keyoneplus** [comment]
Check  using Agent 2.3.0.0 also have the same issue.

**Comment by gillesdubois** [comment]
Hi @keyoneplus,

I will try to reproduce the issue and come back to you asap.

Regards,
Gilles Dubois.

**Comment by gillesdubois** [comment]
Hi,

This problem has been solved and was not related to the Windows Agent but to the OCSReports interface.
The fix will be in the next version.

Check out this link for more informations :
https://github.com/OCSInventory-NG/OCSInventory-ocsreports/pull/276

Regards,
Gilles Dubois.
