### ISSUE TITLE
Software counted multiple times

### ISSUE THREAD

**Issue by JoeyJoeJoeJrShabadoo** [OCSInventory-NG/WindowsAgent#35]
Operating system :  Win7 Prof. SP1 (6.1.7601)
Windows agent version : Release 2.3.0.0

The way the agent is counting installed programs is wrong in some cases. For example, it's listing a single program on my PC twice with these IDs.
```
{054A5F46-6DCE-4D09-8BC0-170428A4ED56}
{054A5F46-6DCE-4D09-8BC0-170428A4ED56}Visible
```
It's even worse with MS office, which is listed 14 times. This is problematic as the ocs inventory groups software by (display)name. It ends up reporting multiple instances on my computer, although in reality there's only one.

It would be nice to address that issue somehow. Having a brief look at the project repo I noticed that WMI is already utilized to some extent. WMI can perfectly retrieve the list of installed products without duplicates:
`wmic /OUTPUT:%temp%\Installs.txt PRODUCT GET Name,Version`

Thanks a lot.

**Comment by gillesdubois** [comment]
Hi @JoeyJoeJoeJrShabadoo ,

Could you send me specific software name and version in order to be able to test your problem ?

Regards,
Gilles Dubois.

**Comment by JoeyJoeJoeJrShabadoo** [comment]
Hi Gilles,

for example, OCS lists 17x "Microsoft Office 2007 Service Pack 3 (SP3)" on one machine. Just in case that it's useful for you, the following file contains the uninstaller keys that I found carrying that name:
[reg_keys.txt](https://github.com/OCSInventory-NG/WindowsAgent/files/990818/reg_keys.txt)

Here's a complete list of software counted twice or more on that machine (number of counts at the end of each line):
[installs_by_ocs.txt](https://github.com/OCSInventory-NG/WindowsAgent/files/990820/installs_by_ocs.txt)

This is how it looks in ocsreports (only this single machine monitored):
![ocs_inventory_wrong_software_counts](https://cloud.githubusercontent.com/assets/9982651/25914727/96e7b2d2-35bf-11e7-9bf2-367567f23b6a.png)

I don't care about most of that stuff, but for some things like MS office or MS Visual Studio I'd need the correct count.

In contrast here's the output of wmic:
[installs_by_wmic.txt](https://github.com/OCSInventory-NG/WindowsAgent/files/990824/installs_by_wmic.txt)

It lists much more stuff (also weird things like a "readme"), but this can be filtered. Furthermore OCS seems to miss major programs. E.g. this machine has an installation of "VueMinder Pro" that is included in wmic output, but not in OCS. 

Best wishes,
Joey

**Comment by gillesdubois** [comment]
Hi,

The newest versions of the OCS Server do prevent these kind of issues.
Don't hesitate to open a new issue if needed.

Regards,
Gilles Dubois.
