### ISSUE TITLE
Not all printer are inventoried

### ISSUE THREAD

**Issue by valencianista** [OCSInventory-NG/WindowsAgent#37]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system :  W10 64bits

### OCS Inventory informations
Windows agent version : 2.3.0

### Problem's description
Hello. 

My printers are installed on a network print server, and I install the printers on my computer.
And when running the agent, it does not detect networked printers, only local printers. Network printers are not listed on OCS. 

![captura](https://cloud.githubusercontent.com/assets/27975730/25839293/59f2129c-3497-11e7-8f23-63a0cc96ba66.PNG)

regards

### Inventory log file ( optional )
*Use github cloud or trusted upload website*

**Comment by gillesdubois** [comment]
Hi, @valencianista ,

Network printer are not inventoried by default, you need to use a plugin.
Take a look at : plugins.ocsinventory-ng.org

Regards,
Gilles Dubois.

**Comment by valencianista** [comment]
Hi, @gillesdubois 
Installed the listprinters plugin and it does not work.
Attachment capture. Printers do not appear


![captura2](https://cloud.githubusercontent.com/assets/27975730/25912607/292b21ea-35b8-11e7-8e04-5ff08394ef5a.PNG)
