### ISSUE TITLE
Unable to compile OCS-NG_Windows_Agent_Setup.nsi (msvcr140.dll is missing)

### ISSUE THREAD

**Issue by lachmex** [OCSInventory-NG/WindowsAgent#38]
### General informations
Operating system :  Windows 10 Enterprise
+
Microsoft Visual C++ 2005 SP1 Redistributable (x86)
Microsoft Visual C++ 2005 SP1 Redistributable (x64)
Microsoft Visual C++ 2008 SP1 Redistributable (x86)
Microsoft Visual C++ 2008 SP1 Redistributable (x64)
Microsoft Visual C++ 2010 SP1 Redistributable (x86)
Microsoft Visual C++ 2010 SP1 Redistributable (x64)
Microsoft Visual C++ 2012 Update 4 Redistributable (x86 and x64)
Microsoft Visual C++ 2013 Redistributable (x86 and x64)
Microsoft Visual C++ 2015 Redistributable (x86 and x64)

### OCS Inventory informations
Windows agent version : Current from Github

### Problem's description
I have tried to compile OCS-NG_Windows_Agent_Setup.nsi but it failed on:
Error in script "...OCS-NG_Windows_Agent_Setup.nsi" on line 1602 -- aborting creation process

`Call Write_Log
  	    strcpy $installSatus ":("
	    clearerrors
	    File "C:\Windows\System32\msvcr140.dll"
	    Iferrors 0 +5`

according to:

> "msvcr140.dll no longer exists. It is replaced by a trio of DLLs: vcruntime140.dll, appcrt140.dll, and desktopcrt140.dll."

from MS support sites, think that this is issue to use discontinued library or I am wrong ?

**Comment by gillesdubois** [comment]
Hi,

We have updated the NSIS, see the github repository.

Regards,
Gilles Dubois.
