### ISSUE TITLE
Confusing installed softwares list

### ISSUE THREAD

**Issue by StCyr** [OCSInventory-NG/WindowsAgent#39]
### General informations
Operating system :  Windows 7

### OCS Inventory informations
Windows agent version :  2.3.0.0

### Problem's description
The method used to get the list of softwares installed only reports partially about installed Microsfot Updates; It seems that the installed Office updates are reported properly, while the Windows updates are simply not listed at all.

Having only office updates listed here is confusing as it lead us to believe all Microsoft updates are listed here, while it is clearly not the case.

### Additional details
The method used to get the list of softwares installed is to query the SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Uninstall registry hive (GetRegistryApplicationsNT method in Registry.cpp). However, this part of the registry doesn't list Windows updates on Windows 7 (and later?). 

### Possible solutions
It seems that from Windows 7, windows updates are to be found via other means (see https://stackoverflow.com/questions/5102900/registry-key-location-for-security-update-and-hotfixes)

**Comment by kchassaing** [comment]
I have the same problem. 
The Microsoft Updates (Security Update KBxxx and Update KBxxx) are listed as softwares only on some PCs. On half of my pcs (170 of 300) these softwares are listed, and the other part no.

I tried to force an inventory directly on one of these pc. At the second forced check the microsoft updates where been updated on my ocs server. It's like if the others checks have take too much time to execute correctly the entire inventory of the softwares. But i can't do it on the 130 remaining pcs.

Have you a solution to get them by the software part of ocs ?
Thank you.

**Comment by kejones999** [comment]
Hi folks,

 There's a lot of concerns about software inventories not matching real-life from a the number of posts on the subject. From my experience it's actually a lot more complicated under-the-hood and it'll take some time to make things really work well. I'll write my knowledge down and hopefully it'll give Gilles and co some inspiration. Given the complexity though, it might take me a few days! I'll be back (probably with something Word-processed to make it easier to read!).

Regards,
Keith
Keith

**Comment by MyTheValentinus** [comment]
Hello and Thanks @kejones999, i'm waiting your message.

**Comment by JoeyJoeJoeJrShabadoo** [comment]
That would really be great, @kejones999 , thanks in advance for your efforts.

**Comment by sokatra** [comment]
perhaps it has something to do with this issue
WMI GetHotFixes randomly report 0 objects
https://github.com/OCSInventory-NG/WindowsAgent/issues/18
Kind regards
