### ISSUE TITLE
OCS Inventory NG Agent Version 2.3.0.0 not support win10

### ISSUE THREAD

**Issue by nntu** [OCSInventory-NG/WindowsAgent#45]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system :  Centos 7 server , window 10 x64 client

### OCS Inventory informations
Windows agent version : OCS Inventory NG Agent Version 2.3.0.0

### Problem's description
*Describe your problem here*
not update in server 
### Inventory log file ( optional )
*Use github cloud or trusted upload website*

[OCSInventory.txt](https://github.com/OCSInventory-NG/WindowsAgent/files/1251198/OCSInventory.txt)

**Comment by keyoneplus** [comment]
in the log file, it will restart the agent inventory when it reach  port(s) found. I have encounter that before. When i set the Debug=2 it happen. So I just set it to Debug=1 in ocsinventory.ini the problem did not occur.

**Comment by nntu** [comment]
yeah . when i set debug = 1 it work.
 thanks

**Comment by gillesdubois** [comment]
See https://github.com/OCSInventory-NG/OCSInventory-ocsreports/issues/284
