### ISSUE TITLE
Device ID generation: Incorrect behavior

### ISSUE THREAD

**Issue by realitix** [OCSInventory-NG/WindowsAgent#47]
### General informations
Operating system :  Windows 10

### OCS Inventory informations
Windows agent version : Master (Debug)

### Problem's description

Hello,
My client is using OCSInventory-NG on a large fleet of machines. We found out that when some PC reboot, the device id is reloaded. This is annoying because we are using OCS with GLPI, when the Device ID is reloaded, it creates a duplicate in GLPI.
After lot of digging in the code, here my conclusion of this behavior:

- In my case, Device ID reloading is done because of MAC addresses.
- `CSysInfo::getNetworkAdapters` gets back MAC Address
- Usually, `CIPHelper::GetNetworkAdapters` is used to collect MAC, if there is an error, `CSNMP::GetNetworkAdapters` is used.
Theses two methods are not working the same ways and returns completely different result.
- At boot time, sometime, OCS-Agent it started before the Ethernet card is enabled by Windows.
-> If the card is disabled, `CIPHelper::GetNetworkAdapters` returns 0 and `CSNMP::GetNetworkAdapters` is called. Of course it changes the MAC collecting process and Device Id is regenerated.

#### Why that behavior ?

`CIPHelper::GetNetworkAdapters` collects only MAC address with interface associated, that's the current algorithm.

### Proposal

My proposal allows to get back all Ethernet card although they are not enabled.
Moreover, it is very simple compared to the current alogirythm.

- Like now, get back `IfTable` and loop through the `MIB_IFROW` structures.
- New filtering: filter only row with `dwType == IF_TYPE_ETHERNET_CSMACD` and with `dwPhysAddrLen == 6`.
- Remove duplicate and we are done !

This is very simple compared to the actual solution and it prevents unexpected id reloading.

I wait for your opinion,
Thanks.

Jean-Sébastien Bevilacqua
Linagora

**Comment by gillesdubois** [comment]
Hi,

Thx for your feedback, there is already a similar issue here : https://github.com/OCSInventory-NG/WindowsAgent/issues/13

Indeed, your proposal is a good solution to prevent OCS from regenerating the DeviceID.
We need to check what's the impact on our server and check the inventoried data integrity on a large fleet but I think we will apply solution like this to solve the problem. 

Atm, if you want to prevent GLPI from creating duplicate you can create an import rule (on GLPI) that merge computers on specific conditions. (If not already set)

As far as I understand, it's for one of your client, you may have to wait a little for the next release since the 2,3,1 has been released this morning.

If you have a visual studio environment, you will be able to compile an Agent from the trunk when a fix will be released.

Regards,
Gilles Dubois.

**Comment by realitix** [comment]
Thanks for your answer @gillesdubois.
I can submit the PR if you want ?

**Comment by gillesdubois** [comment]
Of course, contributions are always welcome.
We will review the PR once submitted and merge it if everything is OK.

Regards,
Gilles Dubois.

**Comment by realitix** [comment]
Hello @gillesdubois,
I am trying to build OCS-Agent but without success.
When I execute `OCS_Make_Required_Libs.bat`, I get the error `cannot open file 'libeay32.lib'` when building `snmp`.
Do you know how I can build this library ?

**Comment by gillesdubois** [comment]
libeay32.lib refer to openssl are you sure openssl is properly compiled ?
You need to launch the bat file from the directory where it's stored since we are using relative path.

Regards,
Gilles Dubois.

**Comment by realitix** [comment]
Yes I launch the bat file from the good folder. For all dependencies, I am using the exact version specified in the Readme. I have lot of problem with snmp.
I use the 7.1 SDK so it should be good but Visual Studio 2017 so maybe a problem.
Are you using VS 2017 ? If someone in your team can compile it on Windows 10, would it be possible to send me an archive with all the project and dependencies compiled ?
We can talk by mail (and in French) to avoid spamming this thread if you want.

Thanks,
Jean-Sébastien

**Comment by gillesdubois** [comment]
Hi,

Yes, it will be better to not spam this thread with problems that aren't directly related to the issue.
Send me your mail so we can continue our conversation. 

Regards,
Gilles Dubois.
