### ISSUE TITLE
GetIfTable() in SysInfo/IPHelper.cpp doesn't support unicode characters in the Network adapter's description

### ISSUE THREAD

**Issue by drTr0jan** [OCSInventory-NG/WindowsAgent#51]
The problem is similar #28.

The GetIfTable() function returns ANSI-formatted network adapter's description in the MIB_IFROW structure. But it's recommended to use GetIfTable2() or GetIfTable2Ex() functions which return the Unicode description in the MIB_IF_ROW2 structure.

Ex.:
I've a network adapter with description _Гигабитное сетевое подключение Intel(R) 82566DM-2_ (Gigabit network adapter Intel(R) 82566DM-2). But I receive `<DESCRIPTION>¨£ ¡¨â®¥ á¥â¥¢®¥ ¯®¤ª«îç¥¨¥ Intel(R) 82566DM-2</DESCRIPTION>` in the WindowsAgent.

Operating system :  Windows 8.1 Russian
Windows agent version : 2.3.1.0

**Comment by charleneauger** [comment]
Hi @drTr0jan ,
Is it just your network adapter's description who is ANSI-formatted or all of your inventory ?

Regards,
Charlene Auger

**Comment by drTr0jan** [comment]
@charleneauger, some network adapter's description on some PCs from my network (about 400 PCs from 500), Other inventory (ex. memory, video cards, controllers) are correctly UTF8-formatted.

**Comment by charleneauger** [comment]
@drTr0jan, I can give you a bug fix in private, can you contact us at contact@ocsinventory-ng.org ?
Regards,
Charlene
