### ISSUE TITLE
OCS Agent 2.3.1 for Windows - ¿memory leak?

### ISSUE THREAD

**Issue by pchamo** [OCSInventory-NG/WindowsAgent#52]
Operating system :  Windows 7, 10, 2012 Server
Windows agent version : 2.3.1

I have the Resources Monitor opened and the assigned memory keeps growing, and also, there is a very notorius and evident difference in the memory consumption among several computers revised. Here some data, one for a Windows 10 computer and one for a Windows 2012 Server:

Windows 10 computer

Initital values:
Commit (reserved memory for OcsService): 98 MB
Working Set (memory in use): 13 MB
1 hour later:
Commit (reserved memory for OcsService): 103 MB (+5 MB)
Working Set (memory in use): 17 MB (+4 MB)

Server Windows 2012

Initital values:
Commit (reserved memory for OcsService): 44 MB
Working Set (memory in use): 48 MB
01:20 hours later:
Commit (reserved memory for OcsService): 49 MB (+5 MB)
Working Set (memory in use): 53 MB (+5 MB)

And OcsSystray.exe has: 3 MB reserved, and no more than10 MB of memory used in all computers and servers revised.

Just after restarting the windows 10 computer, and the Resources Monitor shows only:

Commited memory: 6 MB
Working Set: 13 MB

By the way, if I use the Task Manager (taskmgr.exe) instead the Resource Monitor, the values of used memory are (total physical memory reserved for virtual processes):

Windows 10 computer: 4 MB, OcsSystray.exe: 1.5 MB

Well, I revised both a Windows 10 computer and a Windows 2012 Server with OcsAgent 2.3.0 and the commited and working set are just around 5 MB for the first one and 5 and 10 MB for the server. So it seems to me, is there a memory leak bug?

Thank you
![memory-usage](https://user-images.githubusercontent.com/14299138/31738012-e819a430-b40e-11e7-8587-8a8131f350fe.png)

**Comment by charleneauger** [comment]
Hi @pchamo ,
This bug has been fixed 7d9b3ffd079e68d74431ee1e2fc3cae1a664ebf5

Regards,
Charlene Auger
