### ISSUE TITLE
OCSInventory 2.3.1.0 seems to ignore "other" network adapter

### ISSUE THREAD

**Issue by cadegenn** [OCSInventory-NG/WindowsAgent#56]
### General informations
Operating system :  windows

### OCS Inventory informations
Windows agent version : 2.3.1.0

### Problem's description
Starting with OCS 2.3.1.0, the inventory only list wired network adapter. It no longer list wifi, bluetooth, other network adapters.

Anyway, thank you for the great (and hard) work

**Comment by charleneauger** [comment]
Hi @cadegenn ,
Your problem has been solved with the version 2.3.1.1, there's still a problem with the mask and the subnet number but I will open an issue for this bug.
Thankx for your support !

Regards,
Charlène Auger

**Comment by charleneauger** [comment]
#61
