### ISSUE TITLE
Install Date

### ISSUE THREAD

**Issue by mickythekiller** [OCSInventory-NG/WindowsAgent#6]
I don't see install date
could be retrieve from regedit or wmi
thanks to include this functionnality in the 2.2 version

**Comment by gillesdubois** [comment]
Hi,

This functionnality is already present you just need to update your columns view.
![software install date](https://cloud.githubusercontent.com/assets/9396603/21541295/7296b922-cdb5-11e6-9522-f4688bbafdb6.png)

Regards,
Gilles Dubois.

**Comment by mickythekiller** [comment]
Salut,

je parlais de la date d’install de windows 

merci
