### ISSUE TITLE
 OCS newsletter how to remove

### ISSUE THREAD

**Issue by rogerio18011** [OCSInventory-NG/WindowsAgent#63]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system :Ubuntu 16.04  

### OCS Inventory informations
Windows agent version :  Agent Version 2.3.0.0

### Problem's description
*Describe your problem here*

Informativo do OCS como retirar

![image](https://user-images.githubusercontent.com/34197251/33520065-cce01622-d79a-11e7-8476-f1c1ceba61f7.png)

### Inventory log file ( optional )
*Use github cloud or trusted upload website*

**Comment by gillesdubois** [comment]
Hi @rogerio18011 ,

Note :  There is a newer version available. Think to upgrade ;) 

To solve your problem you need to : 
- Go to config -> Label file configuration menu 
- Remove the text in the textfield and validate.

Message should vanish on the next agent you setup.

Regards,
Gilles Dubois.
