### ISSUE TITLE
ERROR *** DOWNLOAD => Cannot  lock directory <C:\ProgramData\OCS Inventory NG\Agent\download>

### ISSUE THREAD

**Issue by ajavor** [OCSInventory-NG/WindowsAgent#64]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system :  server ocs 2.3.1 (on debian jessie), client - windows 10 pro ver.2.3.1.1

### OCS Inventory informations
Windows agent version : 2.3.1.1

### Problem's description
Everything was working properly and the packages were also installed without a problem until now. On client stations on which Microsoft has updated Windows 10 to ver.1703, there is a problem with the lockdown of the download directory. The first installation package is done and can no longer lock the download directory.

The strangest thing is that it does not help to disable the "OCS Inventory Service" service at the client station and remove the download directory (c: \ ProgramData \ OCS Inventory NG \ Agent \ Download) because the "lock" file is still being used by another application / process (and is not is the download.exe process).

Any idea? The situation is starting to frustrate.

### Inventory log file ( optional ) - download.log
==============================================================================
Starting OCS Inventory NG Package Download and Setup Tool on Wednesday, December 06, 2017 06:23:42.
DOWNLOAD => Running OCS Inventory NG Download Version 2.3.1.1
DOWNLOAD => Using OCS Inventory NG FrameWork Version 2.3.1.1
DOWNLOAD => Using network connection with Communication Server
DOWNLOAD => Using Communication Provider <OCS Inventory NG cURL Communication Provider> Version <2.3.1.1>
DOWNLOAD => Starting new period of 10 cycles
DOWNLOAD => Parsing directory <C:\ProgramData\OCS Inventory NG\Agent\download> for packages
DOWNLOAD => No package found, exiting
DOWNLOAD => Unloading communication provider
DOWNLOAD => Execution duration: 00:00:00.

==============================================================================
Starting OCS Inventory NG Package Download and Setup Tool on Wednesday, December 06, 2017 07:24:44.
DOWNLOAD => Running OCS Inventory NG Download Version 2.3.1.1
DOWNLOAD => Using OCS Inventory NG FrameWork Version 2.3.1.1
DOWNLOAD => Using network connection with Communication Server
DOWNLOAD => Using Communication Provider <OCS Inventory NG cURL Communication Provider> Version <2.3.1.1>
DOWNLOAD => Starting new period of 10 cycles
DOWNLOAD => Parsing directory <C:\ProgramData\OCS Inventory NG\Agent\download> for packages
DOWNLOAD => Package <1510236830> verified and added to process queue
DOWNLOAD => Downloading package fragment <1510236830-1>
DOWNLOAD => Building package <1510236830>
DOWNLOAD => Executing action <EXECUTE> for package <1510236830>
DOWNLOAD => Sending result code <SUCCESS> for package <1510236830>
ERROR *** DOWNLOAD => Cannot  lock directory <C:\ProgramData\OCS Inventory NG\Agent\download>
DOWNLOAD => Unloading communication provider
DOWNLOAD => Execution duration: 00:10:45.

**Comment by ajavor** [comment]
uninstall client, restart windows, install client again - resolve problem.

**Comment by jagarsoft** [comment]
Excuse me, but I cant see a valid solution restart a windows **SERVER**!! only because OCS has a problem managing locking directory ;-(

**Comment by bud4** [comment]
Same Problem!
