### ISSUE TITLE
Error Code 1062 = The service has not been started

### ISSUE THREAD

**Issue by HassanAkbar** [OCSInventory-NG/WindowsAgent#65]
### General informations
Operating system :  
Windows 10

### OCS Inventory informations
Windows agent version : 
OCS Windows Agent 2.3.1.1

### Problem's description

I am trying to run a build of OCS Windows Agent 2.3.1.1. I am getting this when I press "Run OCS Inventory NG Agent Now" I get this: 
Error Code 1062 = The service has not been started

I know that the service has the stopped state but why it is not starting ? What could be wrong here ??
 Secondly, If I start the service manually then on pressing "Show Inventory Information":

Failed sending control message to OCS Inventory Service... Error code 109 = The pipe has been ended

Secondly, I don't know can this be a problem with an External Dependencies ?
Because in curl-7.53.1 there is no Makefile.msvc.names. Secondly, it create libcurl.lib and the batch file uses libcurl_imp.lib [here](https://github.com/OCSInventory-NG/WindowsAgent/blob/master/External_Deps/OCS_Make_Required_Libs.bat#L133)
Any help in this regard will be appreciated...

**Comment by Mant1kor** [comment]
Not enough info.
How did you install Agent?
Show you agent conf file(in Program Data dir).

**Comment by charleneauger** [comment]
Hi @HassanAkbar ,
Libraries and batch file has been updated in last Windows Agent versions.

Regards,
Charlene Auger
