### ISSUE TITLE
Windows 2003 x64 agent general error

### ISSUE THREAD

**Issue by fgendorf** [OCSInventory-NG/WindowsAgent#66]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system :  Windows 2003 x64

### OCS Inventory informations
Windows agent version : v2.3.1.1

### Problem's description
I've just updated to most recent version of OCS Agent and some legacy machine it stop to work,
The error when I try execute is "OCSInventory.exe is not a valid Win32 Application"

### Inventory log file ( optional )
*Use github cloud or trusted upload website*

**Comment by gillesdubois** [comment]
Hi,

2003 Server is not supported anymore by our newest agent versions.
If you want to run our agents on these old versions of windows you need to use the following version : 
https://github.com/OCSInventory-NG/WindowsAgent/releases/tag/2.1.1.1

Regards,
Gilles Dubois.
