### ISSUE TITLE
Windows Agent - Wireless card Inventory malfunction

### ISSUE THREAD

**Issue by lucafwp** [OCSInventory-NG/WindowsAgent#67]
### General informations
Operating system : Windows 10  (1703)

### OCS Inventory informations
Windows agent version : 2.3.1.1

### Problem's description
The agent does not detect the wireless network adapter unless it is connected to a wireless network.
Attached logs are taken from an HP 850 G3 but this issue is present on other machines too.
If the inventory is run being connected on a lan network the card "Intel(R) Dual Band Wireless-AC 8260" will not be added to the generated XML.

### Inventory log 
[OCSInventory.log](https://github.com/OCSInventory-NG/WindowsAgent/files/1698642/OCSInventory.log)
[SysInfo.log](https://github.com/OCSInventory-NG/WindowsAgent/files/1698643/SysInfo.log)

**Comment by Eon9D** [comment]
Thats a good hint. Ive noticed that the IPdiscover shows alot of already invetoried clients.
Opening the computer (shown as hostname) I cannot find the MAC address that is shown in IPDiscover - indeed the WIFI adapter is completly missing.
- The client was connected by LAN and inventoried.
- Computer undocked and no inventory was triggerd
- IPDiscover scanns and and doesnt't know the MAC and lists it as unknown device.


What can we do to help to analyse the issue?

**Comment by Eon9D** [comment]
Update. Also in the opposite direction:
![image](https://user-images.githubusercontent.com/32479943/70916914-b10fd780-201c-11ea-9a0a-c5ebbea3bcea.png)

This is from a Latitude 7490 that was connected to WIFI while the inventory was made.
LAN was not connected.
The notebook does have a physical LAN Port: https://www.dell.com/en-en/work/shop/dell-notebooks/latitude-7490-laptop/spd/latitude-14-7490-laptop#features_section

**Comment by gillesdubois** [comment]
Hi,

This issue has been fixed since a long time, we forgot to close it.

Thanks.
Gilles.
