### ISSUE TITLE
Agent is not sending info to server

### ISSUE THREAD

**Issue by deconya** [OCSInventory-NG/WindowsAgent#73]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General information
Operating system :  
Windows 7
### OCS Inventory information
Windows agent version : 
2.3.1.1
### Problem's description
*Describe your problem here*
Agent send connection but not info about laptop
### Inventory log file ( optional )
*Use github cloud or trusted upload website*

From server only receive:
192.168.1.52 - - [05/Mar/2018:16:04:19 +0100] "POST / HTTP/1.1" 200 6309 "-" "OCS-NG_WINDOWS_AGENT_v2.3.1.1"

From client:
	Starting OCS Inventory NG Agent on Monday, March 05, 2018 16:04:22.
AGENT => Running OCS Inventory NG Agent Version 2.3.1.1
AGENT => Using OCS Inventory NG FrameWork Version 2.3.1.1
AGENT => Loading plug-in(s)
	DLL PLUGIN => Searching for Plug-in DLL(s) in folder <C:\Program Files\OCS Inventory Agent\plugins>
	DLL PLUGIN => 0 DLL Plug-in(s) successfully loaded on 0 DLL(s) found
AGENT => Using network connection with Communication Server
	COM PROVIDER => Loading Communication Provider <C:\Program Files\OCS Inventory Agent\ComHTTP.dll>
AGENT => Using Communication Provider <OCS Inventory NG cURL Communication Provider> Version <2.3.1.1>
AGENT => Sending Prolog
	DID_CHECK => Read DeviceID <USER-PC-2018-02-28-16-43-08> and MACs <08:00:27:82:D1:4A00:00:00:00:00:0000:00:00:00:00:0000:00:00:00:00:00> in file <ocsinventory.dat>
	COM SERVER => Initializing cURL library for sendRequest
	COM SERVER => Using cURL with server authentication
	COM SERVER => Disabling cURL proxy support
	COM SERVER => Enabling cURL SSL server validation support using CA Bundle <C:\ProgramData\OCS Inventory NG\Agent\cacert.pem>
	COM SERVER => Sending HTTP Post request to URL <http://ocs.int>
	COM SERVER => HTTP Post response received <HTTP Status Code #200>
	COM SERVER => Cleaning cURL library
AGENT => Prolog successfully sent
	AGENT => Prolog Frequency set to 10 hour(s)
	AGENT => Inventory on startup option set to  
AGENT => Unloading communication provider
AGENT => Unloading plug-in(s)
AGENT => Execution duration: 00:00:00.

I check apache conf and Im using debian jessie. I installed all again into server but I continue reproducing the problem. If I use Linux agent all goes nice.

**Comment by charleneauger** [comment]
Hi @deconya ,

Can you test with 2.7 version ?

Regards,
Charlene Auger
