### ISSUE TITLE
Malware in WindowsAgent 2.3.1.1.zip

### ISSUE THREAD

**Issue by SecMan123** [OCSInventory-NG/WindowsAgent#74]
### General information
Operating system :  Windows

### OCS Inventory information
Windows agent version : 2.3.1.1

### Problem's description
Hello,
we try to download the Windows Agent 2.3.1.1, but our Malware Protection tool blocks the download due to detected malware.
Please fix this issue ASAP, otherwise we are not able to use this tool due to company security policies.

**Comment by charleneauger** [comment]
Hi @SecMan123 ,
The affected file has been removed from the latest versions of the OCS Agent.

Regards,
Charlene Auger
