### ISSUE TITLE
Duplicate computer in ocs

### ISSUE THREAD

**Issue by nguironnet** [OCSInventory-NG/WindowsAgent#75]
### General information
Operating system :  windows 7 SP1 and windows 10

### OCS Inventory information
Windows agent version : 2.3.1.1

### Problem's description
I have some duplicates computers from some computers (deployed by cloning software, so the base is the same).  The result is i have 2 computers in ocs for the same computer.

### Inventory log file ( optional )
When it goes wrong i have in the log file : 
AGENT => Sending Prolog
	DID_CHECK => Read DeviceID <xxxxxxxxxx-2018-03-13-10-06-08> and MACs <94:65:9C:5E:54:2094:65:9C:5E:54:2094:65:9C:5E:54:2094:65:9C:5E:54:2094:65:9C:5E:54:2094:65:9C:5E:54:20> in file <ocsinventory.dat>
DID_CHECK => MAC Address changed new:<20:47:47:CE:40:39> old:<94:65:9C:5E:54:2094:65:9C:5E:54:2094:65:9C:5E:54:2094:65:9C:5E:54:2094:65:9C:5E:54:2094:65:9C:5E:54:20>
DID_CHECK => Generating new unique ID for device <xxxxxxxxxx>

on the next inventory i have this
AGENT => Sending Prolog
	DID_CHECK => Read DeviceID <xxxxxxxxx-2018-03-16-08-18-52> and MACs <94:65:9C:5E:54:20> in file <ocsinventory.dat>
	DID_CHECK => writing DeviceID <xxxxxxxxxxxx-2018-03-16-08-18-52> and MACs <20:47:47:CE:40:3994:65:9C:5E:54:20> in file <C:\ProgramData\OCS Inventory NG\Agent\ocsinventory.dat>

The problems occurs not at every inventory, 1 time during 1 week with every 6 hours inventory for 10 computers (not always the same) on 826 computers on the network.

What's the problem ?

**Comment by charleneauger** [comment]
Hi @nguironnet ,
This bug has been fix with the pull request #79 

Regards,
Charlene Auger

**Comment by rroseselavy42** [comment]
Any timeline on when this will pull request will be rolled into a release?

**Comment by charleneauger** [comment]
Hi @rroseselavy42 ,

The release will be made in about a month :)

Regards,
Charlene Auger
