### ISSUE TITLE
Agent tries to install new package after the last one started a reboot

### ISSUE THREAD

**Issue by Tarbos** [OCSInventory-NG/WindowsAgent#78]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General information
Operating system :  Windows 10 1709

### OCS Inventory information
Windows agent version : 2.3.1.1

### Problem's description
When you deploy a package with the option to reboot afterwards, OCS deploys the package, starts the Windows reboot but does not stop there waiting for the reboot.
Instead it starts the next package deployment while Windows starts to shutdown resulting in errors for this package.

### Inventory log file ( optional )
*Use github cloud or trusted upload website*

**Comment by sokatra** [comment]
Question .. .. what do you mean with the reboot option ? is the reboot option in your executed script, or is the reboot option part of the server functionality in package deployment ?

**Comment by Tarbos** [comment]
> Question .. .. what do you mean with the reboot option ? is the reboot option in your executed script, or is the reboot option part of the server functionality in package deployment ?

The reboot option is part of the deployment and available when you choose the "advanced options of teledeploy":
![image](https://user-images.githubusercontent.com/4512075/89054650-76637100-d359-11ea-90c5-425650c79b5a.png)
![image](https://user-images.githubusercontent.com/4512075/89054664-7c595200-d359-11ea-8cbb-e32645033de8.png)

**Comment by gillesdubois** [comment]
Hi @Tarbos 

We don't recommend to use reboot option when deploying more than one package.

Regards,
Gilles.
