### ISSUE TITLE
Bad datas send for CPU

### ISSUE THREAD

**Issue by AnaelMobilia** [OCSInventory-NG/WindowsAgent#8]
Hello,

I have new computers which are inventoried as :
- PROCESSORT : AMD A4 PRO-7300B APU with Radeon HD Graphics [1 core(s) x86_64]
- PROCESSORN : 1
- USERAGENT : OCS-NG_WINDOWS_AGENT_v2.1.1.1

This processor type is dual core : http://processors.specout.com/l/1834/AMD-A4-PRO-7300B / http://www.ldlc.com/fiche/PB00173128.html

Same problem for :
- PROCESSORT : AMD Athlon(tm) II X2 B24 Processor [2 core(s) x86_64]
- PROCESSORN : 1
- USERAGENT : OCS-NG_WINDOWS_AGENT_v2.1.1.1
- PROCESSORT : AMD Athlon(tm) II X2 215 Processor [2 core(s) x86_64]
- PROCESSORN : 1
- USERAGENT : OCS-NG_WINDOWS_AGENT_v2.1.1.1
- PROCESSORT : AMD Athlon(tm) Dual Core Processor 4450B [2 core(s) x86_64]
- PROCESSORN : 1
- USERAGENT : OCS-NG_WINDOWS_AGENT_v2.1.1.1

Could you, please, advise for these problems ?

Regards

**Comment by gillesdubois** [comment]
Hi,

Can you please tell me which version of the windows agent you are using ?

A new ocs windows agent version has been uploaded recently maybe you should try it and tell me if you problem has been fixed.

Here is the link : https://github.com/OCSInventory-NG/WindowsAgent/releases/download/2.1.1.3/OCSNG-Windows-Agent-2.1.1.3.zip

Thanks you for contributing ocs inventory project.
Regards, Gilles Dubois

**Comment by AnaelMobilia** [comment]
Hi Gilles,

I add on the original message the version of the agent (always the last OCS-NG_WINDOWS_AGENT_v2.1.1.1).

I try the 2.1.1.3 version and keep you in touch.
Regards
Anael

**Comment by gillesdubois** [comment]
Hi,
 
CPU detection has been improved in 2.3RC your problem should be resolve.

Regards,
Gilles Dubois.
