### ISSUE TITLE
Windows agent motherboard info not getting relayed properly

### ISSUE THREAD

**Issue by wcom939** [OCSInventory-NG/WindowsAgent#85]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General information
Operating system :  Windows 10 Pro fully updated

### OCS Inventory information
Windows agent version : 2.3.1.1

### Problem's description
Motherboard information listed on the agent properties window should be relayed properly to the bios section in the OCS inventory web:
![image](https://user-images.githubusercontent.com/16446451/40578263-d84477ec-60de-11e8-989d-a5978927719d.png)
![image](https://user-images.githubusercontent.com/16446451/40578266-e2a194cc-60de-11e8-8bd4-877f5e4402f2.png)

**Comment by ricardosarda** [comment]
Got the same problem too.

**General information**

Operating system : Windows 10 Pro fully updated

**Server informations**

Perl version : v5.26.1
Mysql  version : 5.7.22

**Server installation method**
Install sh

**OCS Inventory information**

Windows agent version : 2.3.1.1

**Comment by charleneauger** [comment]
Hi @wcom939 @ricardosarda ,
This bug has been fixed with PR [https://github.com/OCSInventory-NG/OCSInventory-Server/pull/161](url) on the OCS server.

Regards,
Charlene Auger
