### ISSUE TITLE
Could not compile from sources

### ISSUE THREAD

**Issue by drTr0jan** [OCSInventory-NG/WindowsAgent#88]
### General information
Operating system :  Win8.1

### OCS Inventory information
Windows agent version : 2.3.1.1
Visual Studio 2015 SP3

### Problem's description
It's impossible to build the WindowsAgent from sources.
First of all, the last version of the ZipArchive Library requires v.141 toolset instead default 140.
Then the building of OCS_Make_Required_Libs.bat and OCSInventory.sln requires an openssl library, but the library is not compiled by default because there is a "comment" jump in OCS_Make_Required_Libs.bat (inserted in OCSInventory-NG/WindowsAgent@fd05aa2) removes the openssl library building.

**Comment by charleneauger** [comment]
Hi @drTr0jan ,
This bug has been fixed with PR #118 

Regards,
Charlene Auger
