### ISSUE TITLE
Installer for Agent v2.1.1.3 failed

### ISSUE THREAD

**Issue by AnaelMobilia** [OCSInventory-NG/WindowsAgent#9]
Hello,

On a w7 pro 64bits computer (internal : 181) :

------
Creating directory <C:\ProgramData\OCS Inventory NG\Agent>...
Création du dossier : C:\ProgramData\OCS Inventory NG\Agent
Création du dossier : C:\ProgramData\OCS Inventory NG\Agent\Download
SetACL allowing Users / Power users read/write permissions on <C:\ProgramData\OCS Inventory NG\Agent>.
Result: error
SetACL propagating inherited permissions on <C:\ProgramData\OCS Inventory NG\Agent\Download>.
Result: error
Trying to determine if service was previously installed.
Yes.
Trying to stop service and kill processes...
Is Service <OCS Inventory Service> running.
Yes.
Trying to stop Service <OCS Inventory Service>.
Ok
Is Service <OCS Inventory Service> running.
No - Waiting 1 second(s) for Service to stop...
Trying to kill process OcsSystray.exe...Result: 0
Trying to kill process OcsSystray.exe...Result: 603
Trying to kill process OcsService.exe...Result: 603
Trying to kill process OCSInventory.exe...Result: 603
Trying to kill process download.exe...Result: 603
Trying to kill process inst32.exe...Result: 603
Waiting 10 seconds for processes to terminate...
Copying new files to directory <C:\Program Files (x86)\OCS Inventory Agent>...
Destination : C:\Program Files (x86)\OCS Inventory Agent
Windows XP or higher detected, installing default cURL library and MS CRT/MFC 9.0...
Extraction : libcurl.dll
Impossible d'écrire : C:\Program Files (x86)\OCS Inventory Agent\libeay32.dll
------

The problem is the same if the previous agent v2.1.1.1 is manually uninstalled before.
No problem for reinstalling v2.1.1.1 agent

Regards

**Comment by gillesdubois** [comment]
Hi,

Did you try to run the setup as an administrator ?

As you can see at the start of your setup log : 
SetACL allowing Users / Power users read/write permissions on .
Result: error
SetACL propagating inherited permissions on .
Result: error

This bug come from a SetACL problem ... i will try to find a fix as soon a possible.

Regards, Gilles Dubois.

**Comment by AnaelMobilia** [comment]
I used an administrator account.
Same problem when I right click on the installer and use "Run as administrator"

**Comment by gillesdubois** [comment]
Ok i'm on it i will notify you want the fixed installer will be available.

**Comment by gillesdubois** [comment]
Hi, 

a new setup will be created this week-end.

Regards, Gilles Dubois.

**Comment by gillesdubois** [comment]
Hi,

In some case setacl can't get write permissions for specific files.
This problem will be fixed in the 2.2 release (beta available here : https://github.com/OCSInventory-NG/WindowsAgent/releases/tag/2.2Beta) 

Regards,
Gilles Dubois.

**Comment by tempman5** [comment]
I have this same problem with 2.9.0.0 agent (x64 version) when I try upgrade from 2.3 to 2.9 in a windows client with 2.3 agent installed.
I run the command as administrator from a cmd.exe (as administrator): OCS-Windows-Agent-Setup-x64.exe /S /NOSPLASH /NOW /UPGRADE /SSL=1 /CA=cacert.pem /TAG=xxx /SERVER=https://xxx/ocsinventory
