### ISSUE TITLE
Catch IPv6 info

### ISSUE THREAD

**Issue by ivancp** [OCSInventory-NG/WindowsAgent#91]
Hello,
Is there an option to enable catch the ipv6 address from remote computer and add as column in computers list?

Operating system :   Windows 10
Windows agent version : 2.3.1.1
OCS Inventory Version: OCSNG_UNIX_SERVER_2.5

Thanks in advance

**Comment by kapouik** [comment]
try in 2.6 : it is possible to see ipv6 informations when you add the ip address column.
