### ISSUE TITLE
"OcsLogon.exe" file is missing in "OCSNG-Windows-Agent-2.4.0.0.zip"

### ISSUE THREAD

**Issue by Tanarri** [OCSInventory-NG/WindowsAgent#95]
Hi,

I downloaded the recent V2.4 file "OCSNG-Windows-Agent-2.4.0.0.zip".
In this ZIP file the "OcsLogon.exe" file is missing.

In older releases this file was inclued.

Greetings
TanarRi

**Comment by gillesdubois** [comment]
Hi,

This file is no longer needed. You can check out our new documentation.

OcsLogon was generating a lot of false positive on antivirus which prevented some IT Services to install our software.

Regards,
Gilles Dubois.
