### ISSUE TITLE
Ipconfig and computer has 2 ipaddress but only 1 is recorded in ocs

### ISSUE THREAD

**Issue by pchamo** [OCSInventory-NG/WindowsAgent#96]
### General information
Operating system :  Microsoft Windows Server 2008 R2 Standard

### OCS Inventory information
Windows agent version : 2.3.1.1

### Problem's description

I have a computer with 2 ipaddress but only 1 is recorded in ocs, please look: http://prntscr.com/ki3qcs

### Inventory log file ( optional )

Running ocs with DEBUG=2 these lines are recorded:

AGENT => Launching hardware and software checks
	INVENTORY => Loading Download history
	INVENTORY => Logged on user ID is <Administrator>
	INVENTORY => Operating System is <Microsoft Windows Server 2008 R2 Standard 6.1.7601 Service Pack 1>, description <>
	INVENTORY => Operating System uses 64 bits memory address width
	INVENTORY => Computer domain or workgroup is <xxxxxxxxxxxx.local>
	WARNING *** INVENTORY => Failed to retrieve user domain
	INVENTORY => System Manufacturer <VMware, Inc.>, System Model <VMware Virtual Platform>, System S/N <VMware-xx xx xx xx d8 99 7b c0-d8 xx e0 0e a3 40 00 xx>, Bios Manufacturer <Phoenix Technologies LTD>, Bios Date <09/17/2015>, Bios Version <6.00>, Motherboard Manufacturer <Intel Corporation>, Motherboard Model <440BX Desktop Reference Platform>, Motherboard S/N <None>
	INVENTORY => 2 processor(s) Intel(R) Xeon(R) CPU E5-2650 v2 @ 2.60GHz [1 core(s) x86_64] at 2600 MHz
	INVENTORY => OS Memory 4096 MB, OS Swap size 8189 MB
	INVENTORY => 64 memory slot(s) found
	INVENTORY => 2 input device(s) found
	INVENTORY => 4 system port(s) found
	INVENTORY => 7 system slot(s) found
	INVENTORY => 5 system controller(s) found
	INVENTORY => 9 storage peripheral(s) found
	WARNING *** INVENTORY => Failed to retrieve sound devices
	WARNING *** INVENTORY => Failed to retrieve modems
	INVENTORY => 4 network adapter(s) found
	INVENTORY => 4 system printer(s) found
	INVENTORY => 1 video adapter(s) found
	INVENTORY => 1 system monitor(s) found
	INVENTORY => Default IPv4 address is <xxx.xx.1.64> (only 1 IP address)
	INVENTORY => Registered company <>, registered owner <Windows User>, Product ID <55041-01...>
	INVENTORY => Product key <MAK or V...>

**Comment by pchamo** [comment]
Well, I tried ocsinventory-agent 2.4 and solved the problem :)

**Comment by charleneauger** [comment]
Hi @pchamo ,

Your problem is solved, I close the issue.

Best Regards,
Charlene Auger
